### ISSUE TITLE
103.1 Nonce already used error with large list retrieval

### ISSUE THREAD

**Issue by tuol** [tripit/api#10]
I am using the C# connector to retrieve a list of air objects. The written code works perfect for an account that has ~80 air objects. These items can be retrieved without a problem.

However, while trying to retrieve items from an account that has > 200 Air objects, it throws a "103.1 / nonce already used" error.

URL: https://api.tripit.com/v1/list/object?traveler=all&past=true&type=air

Am I overlooking some sort of paginate-implementation that I should have done?

**Comment by tariqislam** [comment]
Hi tuol,

You are correct in that there is pagination that needs to be used when retrieving large result items. The API documentation for that section got inadvertently deleted, very sorry about that, but here it is now:

http://tripit.github.com/api/doc/v1/index.html#pagination

Please let me know if there are any other questions.

Tariq
TripIt | Developer Advocate

**Comment by tuol** [comment]
Thanks for the info, however; following the documentation, I still get the same Nonce already used error:

The request I`m making is: https://api.tripit.com/v1/list/object?traveler=all&past=true&type=air&page_num=1 which still fails, but only with accounts with a lot of data.

If I understand the documentation correctly, I am to expect the default number of 5 trips?

Would you please be so kind as to check this and if possible confirm that this functionality is working as it should?

**Comment by tariqislam** [comment]
Hi tuol,

Could you send me the code that you are using to make this api request?
Also please send me all params that you are passing, and I will check it
out.

Please send the code + instructions to tariq@tripit.com

Thanks.

## Tariq Islam

TripIt  |  Developer Advocate

On Mon, Jul 16, 2012 at 11:23 AM, tuol <
reply@reply.github.com

**Comment by tuol** [comment]
Hi Tariq, 

I've made a test-project in VS to show you the problem. On the 21th last month I've sent this by email to tariq@tripit.com. On the 27th I've send an email to the same email address to check if you have received my example.

So far I haven't heard anything back and worry that I've ended up in an overactive spam filter.

Can you please let me know if you've received my email? Title would be the same as this issue.

Thanks!

**Comment by tariqislam** [comment]
Hi tuol,

Please check your email for an update. Thanks.

Tariq
