### ISSUE TITLE
Add another account as a developer/admin to my app

### ISSUE THREAD

**Issue by aglaser** [tripit/api#100]
I've tried looking in the developer menu and in this issue browser but I can’t find an option to add another email / account as an admin for my app. Is it possible to do this?

**Comment by tariqislam** [comment]
Hi,

Unfortunately it is not possible to add another email / account specifically as an admin for an app. However, there is a workaround: for the TripIt account that owns/manages the application, you can add multiple email addresses to that TripIt account that different users perhaps would use to sign in. See the link:

https://www.tripit.com/account/edit/section/email_settings

Hope that helps.

Tariq
