### ISSUE TITLE
About the oauth_callback in the API 

### ISSUE THREAD

**Issue by xinlishang** [tripit/api#105]
I read the doc about oauth_callback here http://tripit.github.io/api/doc/v1/#authentication_section. But I am still didn't get it. Sorry I am kind of new. In step 2, we will lunch browser to browse https://www.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>. After user input username/password, it should return a token AND redirect to the callback URL. The thing is how do I collect the token in redirect URL. Typically, how do I design the URL. I tried an arbitory URL like www.google.com, it failed.

**Comment by tariqislam** [comment]
Hi,

The redirect url is usually a url on your server, whereby when we redirect the user to that URL, your server will be able to obtain the oauth_token from the url query string and use it appropriately.

Please take a look at http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html which details how to make an OAuth call.

Thanks.

Tariq

**Comment by xinlishang** [comment]
yes. that works. Thanks.
