### ISSUE TITLE
Windows 8 RT and tripit/csharp_binding_v1 Integration 

### ISSUE THREAD

**Issue by flighthero** [tripit/api#106]
Hello, 
We are trying to integrate an app with TripIt for Windows 8 RT. 
We can't submit an app because test results by Windows App Certification Kit are not OK:
- TripIt.dll didn't pass  NXCheck
- TripIt.dll didn't pass SafeSEHCheck.

Detailed report: https://dl.dropboxusercontent.com/u/34047766/report2.pdf
Any plans to add support for Windows 8 RT in the nearest future? Or any workarounds that may help to solve this?

**Comment by tariqislam** [comment]
Hi,

At the moment we do not support Windows 8 RT. By any chance do you have/know of the code changes necessary to make TripIt.dll pass the NXCheck and SafeSEHCheck? If so, please feel free to submit a git pull request for the appropriate source file.

Thanks.

Tariq
