### ISSUE TITLE
106.300000 attempted to fetch an access token with an unauthorized request token

### ISSUE THREAD

**Issue by ajkagy** [tripit/api#107]
I'm getting a valid request token, but when trying to get an access token I'm receiving this error message.  The request for the access token looks valid and has the token/token secret from the request token in the request.  Any help would be appreciated.

<Response><Error><code>401</code><detailed_error_code>106.300000</detailed_error_code><description>attempted to fetch an access token with an unauthorized request token</description></Error></Response>

**Comment by tariqislam** [comment]
Hi,

So sorry for the late reply... could you please provide more details, if you are still experiencing this problem? It may help to follow this example of implementing/making a complete OAuth1 call to TripIt:

http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html

Thanks.

Tariq

**Comment by DheerajJariwal** [comment]
Hello,
I am also facing same issue can you please solve this and this link is not working.

Thanks
Dheeraj Jariwal
