### ISSUE TITLE
API to get flight schedules

### ISSUE THREAD

**Issue by sindizzy** [tripit/api#108]
I am looking for an API that I can use in my Android app. What the app does is simply let the user look for a flight and then based on the results either add that to their TripIt account or I will manually add it to their local calendar. In the beginning I am only interested in one US airline since its really meant for their employees. Can the API do this and if so is there a cost involved? Do I need to provide a TripIt link or interface? Do you have an example?

**Comment by tariqislam** [comment]
Hi,

Our API does not provide any flight lookup services, sorry.

Tariq
