### ISSUE TITLE
iOS Integration

### ISSUE THREAD

**Issue by surfmaster96** [tripit/api#11]
Hi,
   I was wondering if there was a way to integrate TripIt Api using the iOS WebKit/WebView using HTML coding, or if there is a source code for iOS Objective-C clients.

Thanks

**Comment by tariqislam** [comment]
Hi,

We do not have a public iOS Objective-C client. Since our API simply returns data, you could build a webkit-based application to display that data.

Please let me know if you have any other questions.

Tariq Islam
TripIt  |  Developer Advocate
