### ISSUE TITLE
We can't use the web plugin. Chrome says Refused to display because X-Frame-Options is set to SAMEORIGIN.

### ISSUE THREAD

**Issue by bryanchug** [tripit/api#113]
Using Chrome 36.0.1985.18 beta on Mac OS X 10.9.2

Refused to display 'https://www.tripit.com/uhp/addToTripIt?p=1&api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXX&domain=XXXXXXXXXX&protocol=http:' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by mphearn** [comment]
We are also having this issue. We cannot activate our Tripit/ClubHub integration. Are there any updates on this?

**Comment by tariqislam** [comment]
Hi guys,

We are working on this at the moment. Will send updates as soon as I get them. Thank you very much for your patience!

Tariq

**Comment by mphearn** [comment]
Are there any updates on this issue?

thanks,
Michael

On Mon, Jun 2, 2014 at 5:10 PM, Tariq Islam notifications@github.com
wrote:

> Hi guys,
> 
> We are working on this at the moment. Will send updates as soon as I get
> them. Thank you very much for your patience!
> 
> Tariq
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tripit/api/issues/113#issuecomment-44891725.

## 

Michael Hearn, PMP
PO Box 660675-14300
Dallas, TX 75266-0675
Cel: (239) 707-5391
Fax: (214) 580-5137
Skype: byike__
mphearn@gmail.com

**Comment by tariqislam** [comment]
Hi guys,

This issue should be resolved, Chrome should not be giving that error anymore.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Closing this issue since there are no more reports of problems.
