### ISSUE TITLE
Invalid Token Key - Can't figure out why

### ISSUE THREAD

**Issue by jeffklee** [tripit/api#114]
We are getting invalid token key errors when trying to submit itineraries. I have requested new token credentials several times but with each new token I still get the same error. All the details are below. Any idea what we are doing wrong?

We are posting to: https://api.tripit.com/v1/crsLoadReservations

Authorization Header: OAuth realm="https://api.tripit.com",oauth_consumer_key="6aa582f342201c334a23580673ef8af8a2408ce4",oauth_nonce="9498387d277da82bc6b47faf3fb0aa94",oauth_timestamp="1401571081",oauth_signature_method="HMAC-SHA1",oauth_version="1.0",oauth_token="d094e3ea9da171a82e70444bc4f61306acdb7df0",oauth_signature="1deYqfxxjd4xPYihI5Piq3FRavQ%3D"

POST payload: <CrsRequest><AirObject><is_client_traveler>true</is_client_traveler><booking_site_name>Amtrav</booking_site_name><booking_site_phone>(866) 284-5774 (312) 525-9805</booking_site_phone><booking_site_url>www.amtrav.com</booking_site_url><record_locator>XXXXXXXXXX</record_locator><supplier_conf_num>XXXXXX (Virgin America)</supplier_conf_num><total_cost>474.00</total_cost><Segment><StartDateTime><date>2014-06-02</date><time>09:15:00</time></StartDateTime><EndDateTime><date>2014-06-02</date><time>10:30:00</time></EndDateTime><start_city_name>Los Angeles, CA</start_city_name><end_city_name>San Francisco, CA</end_city_name><marketing_airline>Virgin America</marketing_airline><marketing_flight_number>935</marketing_flight_number><seats>01F</seats></Segment><Segment><StartDateTime><date>2014-06-04</date><time>08:00:00</time></StartDateTime><EndDateTime><date>2014-06-04</date><time>09:30:00</time></EndDateTime><start_city_name>San Francisco, CA</start_city_name><end_city_name>Los Angeles, CA</end_city_name><marketing_airline>Virgin America</marketing_airline><marketing_flight_number>1930</marketing_flight_number><seats>01F</seats></Segment></AirObject><TripCrsRemark><record_locator>1424477682</record_locator><notes>Thanks for booking with us!</notes></TripCrsRemark></CrsRequest>

Response: <Response>
    <Error>
        <code>401</code>
        <detailed_error_code>106.100000</detailed_error_code>
        <description>invalid token key: d094e3ea9da171a82e70444bc4f61306acdb7df0</description>
    </Error>
</Response>

**Comment by tariqislam** [comment]
Hi,

You application is approved only for 3-legged OAuth authentication. The CRS endpoints require 2-Legged authentication (http://tripit.github.io/api/doc/v1/crs.html#authentication_section) -- please email api-support@tripit.com requesting 2-Legged OAuth for your application in order to use this endpoint.

Thanks.

Tariq
