### ISSUE TITLE
OAuth Login with Google Account

### ISSUE THREAD

**Issue by joeydong** [tripit/api#117]
The OAuth login page does not offer a "Login with Google" option but your main website does. Do you have a solution for this?

![b3d1c6ba-f6f9-11e3-96f4-3412b613192a](https://cloud.githubusercontent.com/assets/434294/3333061/5567c340-f7ee-11e3-8c1c-dcd5e085ac65.png)
![a7376c20-f6f9-11e3-9922-0c23c702c4c0](https://cloud.githubusercontent.com/assets/434294/3333062/56850198-f7ee-11e3-8d7f-5762d76e929d.png)

**Comment by hadees** [comment]
+1

**Comment by johnroa** [comment]
+1

Plus, the default oAuth screen is sign UP, not IN

![image](https://cloud.githubusercontent.com/assets/575278/3421105/79d7cf86-fed8-11e3-974d-ed434eb31947.png)

**Comment by tariqislam** [comment]
Thanks for the feedback guys. We will look into this to see whether we will support this kind of functionality.

Best regards,

Tariq

**Comment by joeydong** [comment]
any updates on this feature?

**Comment by bgilly** [comment]
I'd like to know if there are any updates as well, please. I have quite a few users complain about this, and have had to issue refunds because of it.

**Comment by emunsing** [comment]
I just wanted to flag this as an issue that is still present and still affects my usability- I have repeatedly received bug complains from users who click through to log in with Facebook/Google/Yahoo, then can't get back to my callback.  Any type of workaround would be extremely helpful.

**Comment by sareninden** [comment]
These items are still open and are extremely user unfriendly. The argument that it will cause to many redirects is not really valid (anymore). Take for example Feedly, they can do it with google, facebook, twitter, microsoft and more account types.

**Comment by VickiWis** [comment]
Hi sareninden,

Thank you for using TripIt Api.

We are aware of the desire to be able to log in with via Facebook/Google/Yahoo through the API.  This is currently in the queue for one of our development teams to work on.  Unfortunately, I can not give you a date as to when this issue will be addressed.

Thanks,

Vicki

**Comment by bgilly** [comment]
Hi Vicki, any updates since you last posted about this?

**Comment by VickiWis** [comment]
Hi bgilly, unfortunately this is not a priority for the first half of this year.  I will make sure to re-evaluate it the second half and let you know.
