### ISSUE TITLE
OAuth stopped working

### ISSUE THREAD

**Issue by tarynsauer** [tripit/api#119]
We set up oauth for our account, but it suddenly stopped working yesterday and we're now getting 401. (However, we were able to connect successfully last week.) 

We tried to fix this issue by re-rolling the API Secret and regenerating the oauth keys, however, we keep getting a "Page Not Found" message when attempting to allow access through https://www.tripit.com/oauth/authorize?oauth_token=<<oauth_token>>&oauth_callback=<<oauth_callback>>    (Step  2: Obtain User Authorization). We used the oauth token from Step 1 and a callback of http://axustravelapp.com/auth/tripit/callback. This is the process that worked for us last week...has anything changed that would be causing this issue? What does this error mean, and do you see anything in our procedure that could be causing it?

**Comment by hliss** [comment]
Hi @tarynsauer,

Apologies for how little-monitored our issues list is.

If it helps, the /access_token requests from your app on that day weren't presented with authorized request tokens (the oauth_token field in the /access_token request).

If you're still having OAuth issues, can you please email api-support@tripit.com with the following, and we'll be able to find more info to help you debug. Thanks!
- When API call was made
- Complete details of API call
  - consumer key, and any other tokens used for OAuth (except api secret)
  - API endpoint hit
  - API payload
  - HTTP Request/Response headers
  - Complete reply from our server
