### ISSUE TITLE
Problem POSTing /create with JSON

### ISSUE THREAD

**Issue by dmedvinsky** [tripit/api#12]
I have trouble creating a Trip object using JSON serialization. (Worked for me in XML format, but I don't want to parse XML response with JavaScript when I have a JSON option which is kind of native for JavaScript).

I tried `https://api.tripit.com/v1/create`, `https://api.tripit.com/v1/create/format/json`, `https://api.tripit.com/v1/create?format=json`, and tried including `format=json` in the payload.

With some combinations server does understand that I'm trying to make a JSON request, but when it does, it responds with 401 and bad signature error.

I tried both including and excluding query parameters in the signature string.
I tried both including and excluding payload parameters in the signature string.

Anyways, I'm stuck. Please, can you give me some pointers on how to proceed.

Here are some examples of my signature strings.

```
POST&https%3A%2F%2Fapi.tripit.com%2Fv1%2Fcreate%2Fformat%2Fjson&format%3Djson%26json%3D%257B%2522Trip%2522%253A%257B%2522start_date%2522%253A%25222012-07-08%2522%252C%2522end_date%2522%253A%25222012-08-07%2522%252C%2522primary_location%2522%253A%2522Las%2520Vegas%252C%2520NV%2522%252C%2522is_private%2522%253Atrue%257D%257D%26oauth_callback%3Doob%26oauth_consumer_key%3De096424466762ff8db52d558ba515ada04a52ca7%26oauth_nonce%3D304D5D773A763D43%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1341737016%26oauth_token%3D81847cc152f4d86430c2fb3d5bf268e8d91e5259%26oauth_version%3D1.0
POST&https%3A%2F%2Fapi.tripit.com%2Fv1%2Fcreate%2Fformat%2Fjson&json%3D%257B%2522Trip%2522%253A%257B%2522start_date%2522%253A%25222012-07-08%2522%252C%2522end_date%2522%253A%25222012-08-07%2522%252C%2522primary_location%2522%253A%2522Las%2520Vegas%252C%2520NV%2522%252C%2522is_private%2522%253Atrue%257D%257D%26oauth_callback%3Doob%26oauth_consumer_key%3De096424466762ff8db52d558ba515ada04a52ca7%26oauth_nonce%3D717843533726483F%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1341737056%26oauth_token%3D81847cc152f4d86430c2fb3d5bf268e8d91e5259%26oauth_version%3D1.0
POST&https%3A%2F%2Fapi.tripit.com%2Fv1%2Fcreate&json%3D%257B%2522Trip%2522%253A%257B%2522start_date%2522%253A%25222012-07-08%2522%252C%2522end_date%2522%253A%25222012-08-07%2522%252C%2522primary_location%2522%253A%2522Las%2520Vegas%252C%2520NV%2522%252C%2522is_private%2522%253Atrue%257D%257D%26oauth_callback%3Doob%26oauth_consumer_key%3De096424466762ff8db52d558ba515ada04a52ca7%26oauth_nonce%3D4F6A556F49233860%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1341737082%26oauth_token%3D81847cc152f4d86430c2fb3d5bf268e8d91e5259%26oauth_version%3D1.0
```

**Comment by tariqislam** [comment]
Hi Dmitry,

While we accept json-formatted string as input, the data format being sent
to our server should still be x-www-form-urlencoded. Please take a look at
the appropriate API client library (https://github.com/tripit/) to see the
implementation of this functionality.

Thanks.

## Tariq Islam

TripIt  |  Developer Advocate

On Sun, Jul 8, 2012 at 1:48 AM, Dmitry Medvinsky <
reply@reply.github.com

**Comment by dmedvinsky** [comment]
Sorry for the delay. I finally got back to it and figured it out:

For TripIt to figure that I'm doing the JSON request, I have to pass `?format=json` in the query string, so I'm doing the request for `https://api.tripit.com/v1/create?format=json`.

But I MUST NOT include that query parameter in the signature string. Even though OAuth specification explicitly says query parameters should be included in the signature string: http://oauth.net/core/1.0/#anchor14

And this is the bug in TripIt OAuth API.

**Comment by dmedvinsky** [comment]
@tariqislam As for data being encoded as `x-www-form-urlencoded`, that's how I did it in the first place, having payload be in the following format:

```
json=urlencoded_json_data
```

**Comment by tariqislam** [comment]
Hi Dmitry,

Thank you for the detailed post below. I will check with our engineering
team to look at this issue.

## Tariq Islam

TripIt  |  Developer Advocate  |  1-415-401-1143 x7143  |  tariq@tripit.com

On Tue, Jul 17, 2012 at 12:13 AM, Dmitry Medvinsky <
reply@reply.github.com

**Comment by tariqislam** [comment]
Hi Dmitry,

I now have a couple of comments on this issue:
1. Are you using any of our OAuth1 client bindings (http://tripit.github.com/api/)? Please use those preferably, as they have been tested to work with our OAuth1 server, and handle oauth_signature creation automatically.
2. The correct url to POST to is https://api.tripit.com/v1/create and not https://api.tripit.com/v1/create?format=json
3. When POSTing JSON-formatted data to https://api.tripit.com/v1/create, the POST body should include (in url-encoded format):
   a. format=json
   b. json=json-string-of-form-key-value-parameters
4. If you are using your own OAuth1 client, please make sure the string you use to create the oauth_signature conforms to OAuth1 RFC5849 (http://tools.ietf.org/html/rfc5849 Section 3.4.1.1. String Construction). In particular, the three examples of your signature base strings do not have the eligible parameters sorted in alphabetical order. A sample signature base string from which the oauth_signature can be computed is:

POST&https%3A%2F%2Fapi.tripit.com%2Fv1%2Fcreate&format%3Djson%26json%3D%257B%2522Trip....JSON_PAYLOAD_OMITTED....true%257D%257D%26oauth_consumer_key%3D...%26oauth_nonce%3D...%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D...%26oauth_token%3D...%26oauth_version%3D1.0

Please let me know if there are issues.

## Tariq Islam

TripIt  |  Developer Advocate

**Comment by dmedvinsky** [comment]
> In particular, the three examples of your signature base strings do not have the eligible parameters sorted in alphabetical order.

I don't see how they aren't sorted in my examples but, whatever. It works now, so thanks a lot for your help. :cake:

**Comment by alexbird** [comment]
I've also tried pretty much every combination I can think of, and still cannot create any objects.  

Your documentation could seriously do with some complete json examples!  It is a bit bizarre that the examples are mostly XML, but you recommend that we use JSON.

I am using the iOS binding from github.  It works fine with xml, but when I modify it to post JSON, I always get:
{"code":401,"detailed_error_code":104.1,"description":"invalid signature"}

Here's a sample request:
POST /v1/create HTTP/1.1
Host: api.tripit.com
User-Agent: Skyscanner/3.0 CFNetwork/548.1.4 Darwin/11.4.2
Content-Length: 228
Accept: _/_
Content-Type: application/x-www-form-urlencoded
Authorization: OAuth oauth_consumer_key="57642b25d933b93f91f0976136a11e1f6f11ba6c", oauth_token="7e462bc4a22db31b492b44d0699bd6649bf55e69", oauth_signature_method="HMAC-SHA1", oauth_version="1.0", oauth_nonce="4400677330218241212", oauth_timestamp="1349814710", oauth_signature="aiUb4OutScPa%2FrtgYpaEmZCsWxA%3D"
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive
Proxy-Connection: keep-alive

format%3Djson%26json%3D%7B%22Trip%22%3A%0A%20%20%20%7B%22start_date%22%3A%222009-12-09%22%2C%0A%20%20%20%20%22end_date%22%3A%222009-12-27%22%2C%0A%20%20%20%20%22primary_location%22%3A%22New%20York%2C%20NY%22%0A%20%20%20%7D%0A%7D

My signature strings are, I guess, provided by [auth authorizeRequest:request], which is working fine for XML.

Thanks,
Alex

**Comment by tariqislam** [comment]
Hi Alex,

My apologies for the shortage of JSON-style examples in the documentation, we are working on that. As for sending JSON objects through API calls, I found an oversight in our Objective-C binding whereby JSON is not being handled. The binding will be updated shortly in github, but before that, you can patch up your code in the following way:
1. in TripIt.h:

These are the new definitions:
- (void)performCreateObjectWithString:(NSString *)postString isJson:(BOOL)isJson;
- (void)performReplaceObjectOfType:(NSString *)objType withId:(NSString *)objId withString:(NSString *)postString isJson:(BOOL)isJson;
1. in TripIt.m:

Replace with these functions:

// Performs the 'create' API call
// http://tripit.github.com/api/doc/v1/index.html#method_create
- (void)performCreateObjectWithString:(NSString *)postString isJson:(BOOL)isJson{
  
  NSString *urlStr = [NSString stringWithFormat:@"%@/create", baseApiUrlStr];
  NSMutableString *post = [NSMutableString stringWithCapacity:100];
  if (isJson) {
      [post appendString:@"format=json&json="];
  }
  else {
      [post appendString:@"format=xml&xml="];
  }
  [post appendString:postString];
  
  [self performApiFetch:urlStr 
                 isPost:true
         withXmlString:post];
  }

// Performs the 'replace' API call
// http://tripit.github.com/api/doc/v1/index.html#method_replace
- (void)performReplaceObjectOfType:(NSString *)objType 
                          withId:(NSString *)objId 
                      withString:(NSString *)postString 
                          isJson:(BOOL)isJson {
  
  NSString *urlStr = [NSString stringWithFormat:@"%@/replace/%@/id/%@", baseApiUrlStr, objType, objId];
  NSMutableString *post = [NSMutableString stringWithCapacity:100];
  if (isJson) {
      [post appendString:@"format=json&json="];
  }
  else {
      [post appendString:@"format=xml&xml="];
  }
  [post appendString:postString];
  
  [self performApiFetch:urlStr 
                 isPost:true
         withXmlString:post];
  }

Thanks.

Tariq
Developer Advocate | TripIt

**Comment by alexbird** [comment]
Hi Tariq,

Thanks, that seems to do the trick.  I can't quite see the difference between what you've done and what I did, but there must be some detail I missed!  I was very glad to find your reply this morning.

Another problem with my request is that I was including 'is_client_traveler', because the example AirObject request in   the documentation does, but this is a read-only field.

I was a little surprised to find that 'marketing_airline_code' is a read-only field. 
Wouldn't it be more reliable to  send the IATA code for the airline than the display name we have for them? 

Another surprise was that some elements must be supplied in a fixed order.  This is relatively hard to do with most json libraries.  I had to add a library that included an ordered dictionary to ensure these elements validated.

Thanks,
Alex

**Comment by tariqislam** [comment]
Hi Alex,

Yes, the elements need to be specified in a certain order as specified in the xsd, even when submitting JSON -- a bit unintuitive for JSON, but it's needed.

For the marketing_airline_code, we recommend that you pass in the airline's IATA code in the r/w <marketing_airline> element, and the response will have the display name returned in that field and the code returned in the r/o <marketing_airline_code> field.

Let me know if you have any other questions.

Best regards,

Tariq Islam
Developer Advocate | TripIt

**Comment by tariqislam** [comment]
Hi Alex,

The Objective C API binding has been updated in github -- it includes a change as to how the OAuth flow works (it now uses the web browser instead of a webview during user authentication to TripIt). Please use the updated API binding, as the OAuth flow change is necessary to comply with the TripIt API's Terms of Use. My apologies for the inconvenience caused.

Tariq Islam
Developer Advocate | TripIt
