### ISSUE TITLE
How to fetch only newest segments?

### ISSUE THREAD

**Issue by pogarek** [tripit/api#121]
HI
Imagine a scenario:
1. user forwards trip to tripit and it has been added. The trip contains booking information for a travel, but it may not contain e-ticket yet. 
2. User forwards a new itinerary to trip it. The same flights are there, maybe different booking classes, but it contains a e-ticket yet.

After point 1, only one segment (for a particular flight) will be present by Dev api.
After point 2, two segments will be presented: they will be almost the same, except id, modified time, e-ticket etc. 

So I want to fetch a data , which is up to date. I don't know, if user provided e-ticket or not. I don't know how many Segments will be returned. I only want the most recent one. Like it is visible on tripit.com 

Is there a way to get it, without getting all trips and AirObjects and filtering them first?

Best regards

**Comment by hliss** [comment]
Hiya,

(As usual, apologies for the late reply and the lack of regular monitoring here).

Try using the `modified_since` parameter on http://tripit.github.io/api/doc/v1/index.html#method_list to retrieve only objects that have been modified since that timestamp. Hope that helps!

**Comment by pogarek** [comment]
HI
Thank you for the answer.
Later I have discovered, that for this trip there was a conflict, which tripit didn't dected and didn't prompted a User for an action. 
After removing duplicated travels (the same connections, but different booking id), data returned is ok.

Best regards
