### ISSUE TITLE
Is there such a thing as a "company" developer account?

### ISSUE THREAD

**Issue by markkrenek** [tripit/api#122]
We want to use the TripIt API in our mobile app. Can we sign up for a developer key as a company, or does an individual with an existing TripIt personal account have to do that? What happens if that person leaves the company? How does the company manage the account?

**Comment by tariqislam** [comment]
Hi Mark,

Any email address can be used but companies usually set up a unique email address for the app registration, such as tripitapi@company.com. So, in essence, a company can sign up, but it it still owned by one entity (the entity can be a person or a company, and we do not differentiate between the two). As a company, you would have to manage the account that you sign up for TripIt with, say in case an employee leaves, etc.

Hope that helps.

Tariq
