### ISSUE TITLE
TripIT template issues - Standard TripIt Hotel Only Template

### ISSUE THREAD

**Issue by shijumhnsaves** [tripit/api#123]
Hi,

We are facing some issue in sending the tripit template to plans@tripit.com. and we seems the travel itinerary is not recording in tripit. here is the template we used . Please lets us know if there any issue in the template we used.

Standard TripIt Hotel Only Template (begins at TripIt Approved)

TripIt Approved

Booking confirmation # :
Booking date :
Booking site name :
Booking site phone :
Booking site web-page :

Hotel Information

Hotel name :
Hotel address :
Hotel phone :
Hotel confirmation # :
Guest name :
Check-in date :
Check-out date :
Check-in time :
Check-out time :
Room type :
Room description :
Number of nights :
Number of guests :
Number of rooms :
Frequent guest # :
Cancellation remarks :
Booking rate :
Total cost :
Notes :
Restrictions :

End of Hotel Information

Thanks
Shiju

**Comment by tariqislam** [comment]
Hi Shiju,

The forum here is for questions on TripIt's API. With regards to your question on parsing emails, please contact support@tripit.com with this information, and they will be happy to direct your query to the appropriate data mapping team.

Best regards,

Tariq
