### ISSUE TITLE
Oauth integration problems

### ISSUE THREAD

**Issue by jeffklee** [tripit/api#124]
A couple years ago we set up a link between our corporate travel booking tool (www.Amtrav.com) and TripIt to allow the exchange of itineraries. A few months ago it stopped working – the oauth authorization process fails at the last step with a message:

<Response><Error><code>401</code><detailed_error_code>106.200000</detailed_error_code><description>unable to find authorized request token with key 9fc727bf06b4e34c3cfe266d6838e1953bcb9697</description></Error></Response>

For example, a recent attempt we made was to:

https://api.tripit.com/oauth/access_token

Headers:

realm="https://api.tripit.com",oauth_consumer_key="6aa582f342201c334a23580673ef8af8a2408ce4",oauth_nonce="111ef25e2b30d03ba38a2f3868514046",oauth_timestamp="1408484163",oauth_signature_method="HMAC-SHA1",oauth_version="1.0",oauth_token="9fc727bf06b4e34c3cfe266d6838e1953bcb9697",oauth_token_secret="f242b4884763f3ec0cbf1fe1501b13d21a9e1dc6",oauth_signature="3YPcZGSIshP1XP6EQxPAIDeHK58%3D"

Do you have any idea what the problem might be?

Any help would be greatly appreciated, as we’ve been stuck on this problem for quite some time.

Our consumer_key is 6aa582f342201c334a23580673ef8af8a2408ce4.

**Comment by hliss** [comment]
Hi Jeff, 

Request tokens last for 5 minutes. It looks like for this specific request, the access_token request came more than 5 minutes after the request token was issued. 

Additionally, in this forum, I'll suggest that you double-check your oauth signatures for your calls to the crsLoadReservations endpoint. 

Very happy to discuss specifics of either of the above more privately; please drop api-support@tripit.com a line with the following:
- When API call was made
- Complete details of API call
  - consumer key, and any other tokens used for OAuth (except api secret)
  - API endpoint hit
  - API payload
  - HTTP Request/Response headers
  - Complete reply from our server

Thanks!
