### ISSUE TITLE
Sample requests XML or JSON for getting or creating air object, car object etc

### ISSUE THREAD

**Issue by pradeepsimha143** [tripit/api#125]
Hi team,

We are using a pro account of the trip it and we are using api to inetegrate with our app. I am going through this documentation:
http://tripit.github.io/api/doc/v1/
Basically I want to know is there any sample requests available for creating car object, lodge object etc. In the docs I can see only for Trip object and air object but not finding more information for other object types. Is there any example requests available for other objects? It would be great if someone helps in us in this.

Thanks,
Pradeep

**Comment by ChunhuaDeng** [comment]
we are interest these sample requests also. where to get it?
we can be reached on my email.
