### ISSUE TITLE
Authenticate via Facebook?

### ISSUE THREAD

**Issue by markkrenek** [tripit/api#126]
I'm building an iOS app with TripIt integration. Ultimately I call https://m.tripit.com/oauth/authorize which presents the login web view. Many users only log in to TripIt via Facebook SSO. They don't have/know their TripIt username/password. Is there a way to support authentication via Facebook?

**Comment by hliss** [comment]
Hi Mark,

We'll keep trying to figure this out. I think (memory accuracy permitting) we left it out because third-party login in one's own OAuth authorization page can lead to a browser error (too many redirects). Still, not a great experience for sure. Can't commit to timelines, but we will keep trying to figure out a good solution. Thanks!

**Comment by hliss** [comment]
Looks like this is the same as #117 but for a different login provider. (We haven't forgotten!)

**Comment by emunsing** [comment]
I just wanted to flag this as an issue that is still present and still affects my usability- I have repeatedly received bug complains from users who click through to log in with Facebook/Google/Yahoo, then can't get back to my callback.  Any type of workaround would be extremely helpful.

**Comment by sareninden** [comment]
These items are still open and are extremely user unfriendly. The argument that it will cause to many redirects is not really valid (anymore). Take for example Feedly, they can do it with google, facebook, twitter, microsoft and more account types.

**Comment by garyhooper** [comment]
Can you provide an ETA on an update for this?

**Comment by VickiWis** [comment]
Hi garyhooper,

Thank you for using TripIt Api.

This issue is currently in the queue for one of our development teams.  Unfortunately, I can not give you a date for when this issue will be addressed.  Just know that it will be fixed.

Thanks,
Vicki
