### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by tuol** [tripit/api#13]
Since this is an issue list, I'm not sure if this is the right place to post a wish/idea... 

Upon working with your API (exporting flights, lodging etc.) it is tough testing. There are a lot of variables in the objects that can be empty / vary. 

Of course one'll try to catch this where possible, but there will be exceptions that reveal themselves with large volumes of "real life" data, breaking the application on deployment in the wild.

So far I've been harvesting TripIt accounts from friends and customers to import/test stuff from, but it's unprofessional and troublesome.

It would be superb if you would offer a test account (maybe with just read permission), filled to the brim with many trips, and slowly growing; mimicking a super user.

Otherwise it would be cool if there would be a button for developers to fill their own account with something like a predefined testset with a couple of dozen trips.

**Comment by tariqislam** [comment]
Hi,

Sorry, no we don't have/offer anything like that.

Tariq Islam
TripIt | Developer Advocate
