### ISSUE TITLE
OAuth Logout via API?

### ISSUE THREAD

**Issue by benedmunds** [tripit/api#130]
Hey,

I don't think this is actually an issue as much as a support request.  How do I logout a user via the TripIt OAuth API?

Thanks!

**Comment by hliss** [comment]
Hiya Ben, sorry for the delay in monitoring this board. There isn't really a concept of a session in the API, so there's not really anything to log out of. You, as the developer, can actively forget the user's token, which would achieve the same goal. The user may also revoke the token's validity via the TripIt website (https://www.tripit.com/account/edit/section/applications).

Hope that helps.

**Comment by benedmunds** [comment]
That does.  Thanks!
