### ISSUE TITLE
How can i get the client upcoming tourplan ?

### ISSUE THREAD

**Issue by renjithsraj** [tripit/api#138]
Hi all,

Iam python django developer i going to create a  api for getting user infornmation , any one help to do this api intgreation

**Comment by Varnan** [comment]
Hi,
   How can I get Users information and upcoming trips using TripIt user ID and TripIt Password

**Comment by hliss** [comment]
Hiya.

@renjithsraj: perhaps the [python api bindings](https://github.com/tripit/python_binding_v1) will be of use

@Varnan: You generally shouldn't be using basic authentication for API access. Please see the [authentication section](http://tripit.github.io/api/doc/v1/index.html#authentication_section) in the API documentation. Here you can find details on OAuth and, if needed for testing purposes, how to ask for basic auth for your own account.
