### ISSUE TITLE
Need help mapping our car itineraries

### ISSUE THREAD

**Issue by teddyp1** [tripit/api#139]
Hello. I need help mapping our car itineraries correctly. Several years ago TripIt mapped our (AmTrav's) air and hotel itineraries. We (AmTrav) is a vendor partner with our name and logo on your partner page. Somewhere along the line though our car itin was either not mapped or not mapped properly. Can someone on the TripIt side map it for us? Or tell us who to speak with? Thanks.

**Comment by hliss** [comment]
Hi Teddy, can you please contact support@tripit.com with at least the email address you used to send it in? We can identify the email that way. Thanks!

Is this related to #135, by the way?

**Comment by teddyp1** [comment]
Hi. Much appreciate the quick response and direction. Thanks for your help!! And yes, this is related to #135.

**Comment by teddyp1** [comment]
Actually, as we are a travel management company, the emails that we send to tripit are all technically from the email address of the traveler. I'll let support@tripit.com know that though.
