### ISSUE TITLE
How to get Request token

### ISSUE THREAD

**Issue by ksubham** [tripit/api#14]
I am very new to Oauth. And My task is only to get trip details for a user.No create/delete/replace anything of that sort.

I created a application after signing in http://www.tripit.com/developer.
Instantly i got key and Secret which i stored in 
oauth_consumer_key and consumerKey_Secret 
I also stored Signature method and version and dynamically generating noonce value and timestamp.
All good till here.

Now Please check and let me know if Endpoint is correct and I need to know which method or how can i generate Oauth_token_secret and Oauth_token

```
    Http h = new Http();
    HttpRequest req = new HttpRequest();
    req.setMethod('GET');
    req.setEndpoint('https://api.tripit.com/oauth/request_token'); // Is this correct endpoint //1st issue???????

req.setHeader('Authorization','OAuth    realm=\"https://api.tripit.com/\",oauth_consumer_key=\"'+oauth_consumer_key+'\",oauth_token=\"'+oauth_token+'\",oauth_nonce=\"'+nonceValue+'\",oauth_signature_method=\"'+oauth_signature_method+'\",oauth_timestamp=\"'+timeStamp+'\",oauth_version=\"'+oauth_version+'\",oauth_signature=\"'+signature+'\"'); 
```

 // 2nd Issue  Is this correct =OAuth    realm=\"https://api.tripit.com/\" ????????
//3rd and most critical from wher to get the value of oauth_token and secret?? which method or how will i get this ???

Regards,
Subham

**Comment by tariqislam** [comment]
Hi Subham,

Please check your email regarding communication on this issue.

Thanks.

Tariq

**Comment by Neaimy** [comment]
Hi Tariq, 
I have the same issue, I also created a application after signing in http://www.tripit.com/developer.
I'm using C#.Net with ASP.Net to connect  to tripit account I may need to create/delete/replace trips with my application.

Thanks, 
Neaimy

**Comment by tariqislam** [comment]
Hi Neaimy,

Please look at our developer documentation (http://tripit.github.io/api/doc/v1/index.html#authentication_section) for the details on using OAuth1. Unfortunately we do not have an API binding for the languages you specified, but you may be able to use open-source OAuth1 libraries (http://oauth.net/code/) to integrate with us. This post (http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html) also details the implementation of an OAuth consumer.

Thanks.

Tariq

**Comment by Neaimy** [comment]
Hi Tariq, 

Thank you very much... I'll check it.

Regards, 
Neaimy
