### ISSUE TITLE
¿Se puede cambiar el domino para usar los plugins de Tripit?

### ISSUE THREAD

**Issue by itoCorp** [tripit/api#140]
los plugins de tripit de pueden usar en cualquier pagina o solo en la que se registro al momento de llenar el formulario de obtencion de la clave de los plugins o despues de obtener la clave de los plugins se puede cambiar el dominio que se introduce al llenar el formulario de registro para obtener la clave

![pantallazo](https://cloud.githubusercontent.com/assets/11720677/6897888/06725d7e-d6bc-11e4-9c30-dba752738e1e.png)

**Comment by hliss** [comment]
Hiya,

Apologies for the delay here. The domain of the hosting page must match the domain in the app configuration. The entire qualified URL isn't necessary, as the plugin can live anywhere on the website of that domain. Only the domain has to match. If you're using the plugin on a development domain, I might suggest creating a second developer key to use in development. That way, you don't need to configure your app on the fly and your non-production environments will continue to work. Hopefully this helps you!

(Si requieres la respuesta en Español, porfavor haznoslo saber, gracias!)

**Comment by itoCorp** [comment]
Hola Harold,

Me podrías dar la respuesta en español por favor

Mil Gracias por tu atención

Saludos y Gracias

Fernando Salazar H.
Tripit
Ito Corp S.A.S
email: fernandosh@itotm.com mailto:diegomo@itotm.com
Teléfono: +574-448-4862
Dirección: Cra 25 # 3-45 Of. 531
Medellín, Colombia

ADVERTENCIA.

La información contenida en este correo electrónico y sus anexos son propiedad privada y exclusiva de ito Corp S.A.S, está dirigida exclusivamente a su destinatario y puede contener datos de carácter confidencial protegidos por la ley. Si usted no es el destinatario de este mensaje por favor infórmenos y elimínelo a la mayor brevedad. Cualquier indebida retención, difusión, distribución, divulgación o copia del mismo está prohibida por la ley.

 WARNING.

The information contained in this e-mail and its attachments is private and exclusive of ito Corp S.A.S, is intended for the use of the individual or entity to which it is addressed, and may have confidential data. If you are not the intended recipient, please immediately send it back and delete the received message. Any retention, dissemination, distribution or copy of this message is strictly prohibited by law.

**Comment by hliss** [comment]
Hola,

Una disculpa por la tardanza. El dominio de la pagina debe ser el mismo que el dominio que introduzcas en la aplicación. La dirección completa del URL no es necesaria, el plugin puede vivir en cualquier pagina del dominio, solo el dominio tiene que ser el mismo.

Si estas usando un plugin en un dominio bajo la función de programador, lo que te sugiero es crear una llave adicional para usarla en esta función en especifico. De esta manera podrás configurar tu aplicación con mas tranquilidad ya que todo seguirá funcionando normalmente en las otras pantallas de no-programación.

Espero esta explicacion te sea de utilidad!
