### ISSUE TITLE
Get unfiled items

### ISSUE THREAD

**Issue by cdemyanovich** [tripit/api#142]
I'm viewing an unfiled rail item on the website. The URL in the browser address bar looks something like this: `https://www.tripit.com/reservation/show/id/nnnnnnnnn`. Can I use the `nnnnnnnnn` to get just this unfiled rail item? I've tried several requests based on the API documentation, but I haven't been able to obtain a response that contains anything other than `timestamp` and `num_bytes` values.

**Comment by hliss** [comment]
Hiya,

You should be able to retrieve the item with that ID, provided you have an authorized token for the owner of the item. The URL should look like `https://api.tripit.com/v1/get/rail/id/nnn`. If this still fails, what HTTP response code do you get back?

**Comment by cdemyanovich** [comment]
Looking back, I think I was trying to get production rail item with my test credentials instead of production ones. Thanks and sorry for the noise.

**Comment by hliss** [comment]
:smile: Cheers!
