### ISSUE TITLE
Unable to get AirObjects using free TripIt account

### ISSUE THREAD

**Issue by UXVirtual** [tripit/api#144]
We’re connecting up the TripIt API to our application and are having some issues getting AirObjects to return from the API. The Trip Objects and NoteObjects return correctly when [https://api.tripit.com/v1/list/trip](https://api.tripit.com/v1/list/trip) or [https://api.tripit.com/v1/list/object/type/note](https://api.tripit.com/v1/list/object/type/note) is called, however we receive no AirObjects when querying [https://api.tripit.com/v1/list/object/type/air](https://api.tripit.com/v1/list/object/type/air) using a free TripIt account.

When the same request is made using a pro account we do get the list of AirObjects.

Both accounts have the same Trip information loaded into them with the same flight data which was forwarded to the TripIt email address.

**Comment by hliss** [comment]
Hiya. This one raises an eyebrow! Can you please contact api-support@tripit.com with some more details (like the name of your app and the free/pro account usernames)? That, we'll have to dig into. Thanks!

(Will close the GitHub ticket as there's not much more to do here, but we'll take it up via email.)
