### ISSUE TITLE
basic web auth is not activated for this account

### ISSUE THREAD

**Issue by pasupulaphani** [tripit/api#145]
curl -k -D /dev/tty --user ****_:**_*\* https://api.tripit.com/v1/list/trip
HTTP/1.1 401 Unauthorized
Server: nginx
Content-Type: text/xml; charset=utf-8
Date: Fri, 26 Jun 2015 23:58:48 GMT
Connection: close
Set-Cookie: BIGipServertripit-web=1912720138.20480.0000; path=/

<Response><Error><code>401</code><description>basic web auth is not activated for this account</description></Error></Response>

**Comment by pasupulaphani** [comment]
I can login with the same username and password but cannot do a curl

**Comment by hliss** [comment]
Hiya, please see the web auth section here: http://tripit.github.io/api/doc/v1/index.html#authentication_section

TripIt support (support@tripit.com) can enable basic auth for your account by request. Drop a line or visit https://www.tripit.com/uhp/feedback to make the request for your account.

Please do remember that basic auth is intended for development/sandbox use only and we categorically do not recommend this scheme for production use. 

Cheers!

**Comment by pasupulaphani** [comment]
Cheers for the prompt reply.
