### ISSUE TITLE
IOS Integration issue

### ISSUE THREAD

**Issue by niksan93** [tripit/api#15]
Hi, I'm trying to implement tripIt integration into my ios app (implementation on objective-c) but I have some problems.

I have two apps with API Keys:

84c0f50f6c2b6c0386bb5040b17cf904b6a12862
and
cda8fd3673ae5e0c5ded20d87c7d19941bbdb490

At first there was a problem error &quot;invalid signature&quot; and I'm not really sure that it is solved.
Why is there such a problem if I just use the library that I was told you are using (Kaboomerang)?

Now if request token stage is completed on the stage of authorization the same url as shown in this blog 
http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html
&quot;https://www.tripit.com/oauth/authorize?oauth_token=df919acd38722bc0bd553651c80674fab2b46508&amp;oauth_callback=http%3A%2F%2Fwww.tripit.com%2Fhome&quot;

but with my oauth_token.

And this page tells me &quot;401102.1consumer key not present in request&quot;

What am I missing here?

**Comment by tariqislam** [comment]
Hi niksan93,

I was unable to reproduce the error that you obtained. Can you please provide more details:
- what exactly are you executing, in what order
- what url(s) are you hitting
- what are the responses for each request
- what is the key of the consumer you're using
- what is the approximate time/timezone of the incident

Thanks.

Tariq

**Comment by niksan93** [comment]
The problem with invalid signature dissappeared like on one sunny day.
And the problem with "401102.1consumer key not present in request"
I was using the wrong url "api.tripi/authorization" instead of "www.tripit/authorization" or smth

Thanks.

**Comment by tariqislam** [comment]
We have an Objective C API binding now! 

https://github.com/tripit/objective_c_binding_v1
