### ISSUE TITLE
About getting access_code 

### ISSUE THREAD

**Issue by egorvas** [tripit/api#150]
Hi I trying to use tripit api for my android application.
But I faced with a problem access_code receiving.

I use same code as in your java bindings. I have this command in it:

provider.retrieveAccessToken(consumer, verificationCode.trim());

When verificationCode you setting manually from console line by oauth_token. 

Why you do it? You can get this code from consumer.getToken().
And did you really sure that its correct code? Because my provider.retrieveAccessToken not working anyway. Thankyou.

**Comment by tariqislam** [comment]
Hi,

I testing out the example code that creates a new OAuth1 request token by executing in the command line (not android app):

```
java -cp tripit-api.jar:lib/*:. com.tripit.auth.OAuthAccessTokenGetter -key API_KEY -secret SECRET
```

I was able to complete the OAuth1 authorization and obtain the access token and key, so I can verify that this binding is working in the command line using Java 8.

And, yes, it is true that the value of the verification code that TripIt returns is the same as the request token key. However, this is an implementation detail within TripIt's OAuth1 implementation -- if you look at the OAuth1 spec, the two values (request token and verification code) do not have to be identical. Hence, it is safest to use the verification code returned by the server after the callback.

Hope that helps!
