### ISSUE TITLE
Viewing and accepting invites

### ISSUE THREAD

**Issue by kpaulisse** [tripit/api#151]
This API does not seem to support:
- Viewing a list of pending invitations you have received
- Accepting any such invitations

Is this supported but undocumented? If not supported now, will it be in the future? Thanks in advance.

**Comment by hliss** [comment]
Hiya Kevin,

We don't plan to support public invitation and connection APIs; at least not in the near future. Out of curiosity, though, what use case do you have in mind? Feel free to ping api-support@tripit.com if you'd prefer not to share specifics here. Thanks for the feedback!

**Comment by kpaulisse** [comment]
I was thinking of writing a script for Hubot (https://hubot.github.com/) so that people could get information in a chat room pulling details from their TripIt accounts, or those of others.

Hubot can do all sorts of interesting things (see for example http://www.wired.com/2015/10/the-most-important-startups-hardest-worker-isnt-a-person/ ). Some existing non-work integrations are telling you when the next Caltrain leaves or what food trucks are around, for example.

My plan to implement this would be for Hubot to have a TripIt account for himself, and then people would add him as a friend so he could access their plans. I'd need the "accept an invite" API call so that Hubot could accept friend requests from people who added him. I guess an alternate approach would be for Hubot to store the oauth tokens for all the TripIt users he knows about and directly access their accounts...

**Comment by hliss** [comment]
Ahh, yeah! You'd get much better data with a direct API integration. Even as a connection, there's not much data you can get via the API unless the user also shares trips individually, which would result in massive API responses for your user! Getting an API token is the way to go.
