### ISSUE TITLE
Not All Entries Downloading

### ISSUE THREAD

**Issue by sdsilverman** [tripit/api#154]
We are using:

https://api.tripit.com/v1/list/object

to get a full list of the upcoming objects for a given user.  In the past, this has worked flawlessly.  But we have found a new bug has emerged so that sometimes we get only a partial list of the items.  For a user whom we were able to investigate fully (using their account), we are talking about 10 items but only 2 items are being returned.  Interestingly, if we add the "type" filter for a given entry not showing up, it will be correctly provided.  It is only in the case where a type is left out and we are expecting all entries does the problem occur.

More interestingly is if we go into the tripit.com web interface and add an entry manually, it is included in the list.  It is the case that some existing entries are not being provided when we issue the command.

Just to squash any thoughts on the page_size changes forthcoming, this is not an issue as the number of entries we have tested with are below the default page_size.

If a TripIt support person contacts me I can provide an account where this is easily verified.

Thank you.

-Scott

**Comment by hliss** [comment]
Hiya Scott, thanks for writing in.

We recently added pagination to this endpoint; the email address registered to this application should be been notified. Can you please double-check that the pagination parameters you're sending (if any) or receiving match, and are sane? See http://tripit.github.io/api/doc/v1/index.html#pagination for details. If that doesn't explain the issue, then we'll figure more out!

If you'd like to provide more identifying details, an email to api-support@tripit.com will suffice, and we'll clear this up.

-Harold
