### ISSUE TITLE
Python example program requires a consumer and authorized key/secret.  Where can I find the consumer key?

### ISSUE THREAD

**Issue by willpowersdev** [tripit/api#156]
I think the authorized key/secret is what's shown on the developer console, if I'm not mistaken.  How do I find the consumer key/secret?  The syntax for the example.py file is as follows:

example.py api_url consumer_key consumer_secret authorized_token authorized_token_secret

**Comment by hliss** [comment]
Hi @gyrocade, the developer console at https://www.tripit.com/developer shows your app's consumer key and secret. The authorized key and secret will be per-user. See http://tripit.github.io/api/doc/v1/index.html#authentication_section for more info! Hope that helps.

**Comment by willpowersdev** [comment]
Could you describe the type of object or objects that gets sent to the callback for Step 3, after the user has authorized the app to access TripIt?  Also, what should the callback return, if anything?  A function signature would be nice to have.

Will

**Comment by hliss** [comment]
After the user authorizes (clicks "Allow" at https://www.tripit.com/oauth/authorize), they'll be redirected back to your `callback_url` with an extra `oauth_token` parameter appended. This doesn't contain the request token secret. Then, you can continue on to Step 3 to attempt to exchange the authorized request token for an access token!
