### ISSUE TITLE
API for cusotmer signup.

### ISSUE THREAD

**Issue by cpu8080** [tripit/api#159]
Hi, 
Is there an API available to register a customer automatically for TripIt?

We currently have a web application where a customer signs up and would like to add the option to automatically create a TripIt account for the customer via an API.

Thanks.

**Comment by hliss** [comment]
Hiya,

There isn't such an API available for a few reasons. An API consumer shouldn't be able to set credentials for a user! That's between the user and TripIt. Given a newly created account would be unconfirmed, it wouldn't be able to grant API access to your application anyway. 

Your best bet would be to initiate the standard TripIt OAuth authorization, at which point they can create a TripIt account with their own credentials and continue with authorizing your app!
