### ISSUE TITLE
JSON data through Python binding?

### ISSUE THREAD

**Issue by emunsing** [tripit/api#162]
I can't figure out a way to set the 'format' parameter from within the provided Python bindings- is it possible to set this for JSON data? I don't see anywhere that a default format value is set, and have hacked a local version which writes the format as a url_arg in the _do_request() method, but this could conflict with the use of the replace_ methods. Any better recommendations?

**Comment by vsejpal** [comment]
Hi @emunsing,

Thanks for reporting this issue. We are currently investigating the issue. Will comment with any further updates on this.
