### ISSUE TITLE
Notification CallBack URL authentication

### ISSUE THREAD

**Issue by MortenVelling** [tripit/api#163]
Hi,
does the TripIt Notification API support authentication on the CallBack URL? Specifically, I am wondering if it is possible to use an Azure Service Bus Relay endpoint as a CallBack URL? This would require support for SAS based authentication (https://azure.microsoft.com/en-us/documentation/articles/service-bus-shared-access-signature-authentication/).
Regards,
Morten

**Comment by prasadkarkera** [comment]
Hi Morten,

You can use any endpoint as a callback URL. The only requirement is that the url should start with http/https. After authentication we will simply callback to the url provided by you. We cannot add special headers when we make this request. But if there are tokens present in the callback url we will not drop them when we callback.

Let me know if you have any further questions. 

Thanks
Prasad

**Comment by MortenVelling** [comment]
Thanks. Could you provide me with the IP range that the notification calls will come from? Also, would it be possible to get some sample notification messages?
Regards,
Morten

**Comment by prasadkarkera** [comment]
Hi Morten,

The notifications should come from 12.129.29.80 or 12.129.29.81

Regarding sample notification message, please take a look at the last section of the documentation in http://tripit.github.io/api/doc/v1/notification.html

The notification messages are a simple POST to the callback url. There will be nothing in the POST body but the callback URL will be appended with the fields mentioned in that documentation. 

Thanks
Prasad
