### ISSUE TITLE
Hook for trip distances?

### ISSUE THREAD

**Issue by emunsing** [tripit/api#164]
I'd like to pull the distances for each trip into my app. The user's website profile lists this information, showing current year and lifetime total distances- including trips which have been entered manually and do not have flight information.  Is this information available through the API? I have only been able to find distance data for air segments, and not for manually entered trips or trips without an air segment. 
    I realize that one option is to create this data on my side based on lat/lon differences, but if the data is available in the API I would prefer to use that.

**Comment by VickiWis** [comment]
Hi,

You are correct that in our api we only give the distance for air segments, and that is only if we can obtain that information.  The current year and lifetime total distances that you found in the user's profile is computed internally, but is probably not computed to the accuracy that you may desire.

If you want accurate distances for each trip in your app, I would recommend that you determine that using your own computations as there are a variety of ways this can be computed.

Thanks,

Vicki
