### ISSUE TITLE
"consumer key not present in request"

### ISSUE THREAD

**Issue by buddikab** [tripit/api#165]
URL:- https://api.tripit.com/oauth/request_token

Headers:-  Authorization :  Basic myemail:myemailpassword

i used above request format to request a token by postman, but i am having below message. I went through below documents also. can I know how to request a token in proper way. what is the "password of secretpassword" of mine

**DOCUMENTS**:-
"The web authentication scheme relies on HTTP's authentication RFC to authenticate clients of the TripIt API using a TripIt username (i.e. email address) and password. This authentication scheme may be limited or turned off by default in future versions of the TripIt platform and therefore should not be relied upon for production application development. It is a very simple and useful way to get started with the API. "

**ERROR MESSAGE:**-
<Response>
    <Error>
        <code>401</code>
        <detailed_error_code>102.100000</detailed_error_code>
        <description>consumer key not present in request</description>
    </Error>
</Response>

**Comment by prasadkarkera** [comment]
Hi,

Thank you for using our TripIt api.

From your request above it seems to me that you are trying to use web authentication to request an oauth token. Below is an explanation that should help.

There are two different ways of authentication that we support.
1. Web Authentication
2. Oauth

Both the authentication mechanisms are mutually exclusive and you can use either of them to get data from TripIt for a user.

### Web Authentication:

If you intend to use web authentication, for eg. getting trip data, all you have to do is 
1. Create a new request GET request in postman for https://api.tripit.com/v1/list/trip. 
2. Select  'Basic Auth' in the Authorization tab. 
3. Enter your username and password. Click update request. (Postman will convert this to base64 encoded string and attach it to header)
4. Hit Send

You don't have to obtain an oauth token.

### Oauth:

If you intend to use oauth for authentication, you will have to create a consumer application by going to https://www.tripit.com/developer/create. You will be given a consumer key and secret key.

After that follow the 'Step 1: Obtaining a Request Token' documentation in http://tripit.github.io/api/doc/v1/index.html

For obtaining a token using https://api.tripit.com/oauth/request_token you will need the following parameters. (Explanation of the each parameter is mentioned in the documentation. 
1. oauth_consumer_key  
2. oauth_nonce  
3. oauth_signature  
4. oauth_signature_method  
5. oauth_timestamp  
6. oauth_version

Except oauth_consumer_key, postman auto generates everything else. 

Let me know if that helps. 

Feel free to contact if you need further help in this. 

Best
Prasad

**Comment by igordossantos** [comment]
How can I retrieve the oauth_consumer_key?

**Comment by brianheineman** [comment]
@igordossantos You can obtain an OAuth consumer key by creating a consumer application at https://www.tripit.com/developer/create

**Comment by vijayanandh-globalizeme** [comment]
Hi,

I tried the above mentioned. Even though I got the same error. 
I have generated API key&Secret key and set as consumer key & consumer secret correspondingly in Postman application. But it returns "Consumer key is not present".

Thanks in Advance.
