### ISSUE TITLE
ios integration with tripit

### ISSUE THREAD

**Issue by mkatragadda** [tripit/api#166]
Hi

I'm trying to integrate tripit with IOS .As I'm doing basic authentication for my integration just wondering what values should be provided for the oauth_token in the below URL.Do I still need to use OAuth authentication for tripit launch from app as this is only for development purpose .

https://m.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>

**Comment by vsejpal** [comment]
Hi @mkatragadda,

Thanks for using our API. 

If you have Basic WebAuth turned on for your account, then you do not need to perform any OAuth authorization. You could directly make API calls using a base-64 encoded string that represents your username and password like this
`Base-64-encode(your_email@gmail.com:your_password)`

Once you have this base-64-string, you could make an API call this this:
`curl -X GET -H "Authorization: Basic <base-64-string>" "Content-Type: application/x-www-form-urlencoded" -d '' "https://api.tripit.com/v1/list/trip"`

You can find more info in the _Web Authentication_ section of our API documentation here:
http://tripit.github.io/api/doc/v1/index.html

Hope that helps!

**Comment by mkatragadda** [comment]
Hi vsejpal

Thanks for the reply.I'm not  trying api integration.I'm trying to launch tripit login page without oauth from mobile app. Please let me know if it can be done without OAUTH 

https://m.tripit.com/oauth/authorize?oauth_token=&oauth_callback=

**Comment by vsejpal** [comment]
It sounds like you are trying to present TripIt's login page to users of your app. They will login to TripIt using their TripIt account details. Is that correct?

Our login page is at: _https://www.tripit.com/account/login_ and it is mobile-optimized. This page can be launched from mobile without any OAuth integration
