### ISSUE TITLE
What are the limitations of the free tripit API compared to the Pro one ?

### ISSUE THREAD

**Issue by sangimed** [tripit/api#168]
The title says it all.

**Comment by VickiWis** [comment]
Sangimed,

From the API documentation: Any TripIt API client that is authorized to request data from the API on behalf of a TripIt user that happens to be a TripIt Pro subscriber will automatically receive Pro data in the <Response> objects.  

This is only available for TripIt API clients and not for the general public users of the free API.

Thanks,

Vicki
