### ISSUE TITLE
Is the API still supported?

### ISSUE THREAD

**Issue by kngspook** [tripit/api#169]
Is the TripIt API still supported? For months now I've been getting API errors on authentication, despite using the official clients.

**Comment by VickiWis** [comment]
Hi,

The TripIt API is still supported and working.  Are you trying to use web
authentication or Oauth?  If you are using Oauth, what is the consumer
application that you are using?

Thanks,

Vicki

**Comment by kngspook** [comment]
Hi Vicki,

I'm using OAuth.

I'm not sure how to answer the second question, about the consumer application. I've registered my own project and am using my own API key/secret while I'm developing it. I'm not sure how to identify which one though; it's just called "Calendar" right now in the dev center?

Thanks!

**Comment by kngspook** [comment]
Also, FWIW, I also tried:
1. waiting a few days to see if it was a quota issue
2. trying from another IP
3. registering a second project in the dev center and testing with that
4. testing API access from other open source TripIt projects to rule out my own implementation

**Comment by VickiWis** [comment]
Hi,

To help you figure out a solution, can you send an email to
api-support@tripit.com?

Also, could you please include the following:
1. When was the last time you tried to access the api?
2. What are the steps that you use to access it?

Thanks,

Vicki
