### ISSUE TITLE
Renew oauth token

### ISSUE THREAD

**Issue by niksan93** [tripit/api#17]
Hi!
When I connect to a tripit once, can I save request token and token secret and when I open my app next time, get the access token  using the request token I saved, without authorization.
Or can I save the access token and secret and get access to protected resources with that saved token?

**Comment by tariqislam** [comment]
Hi,

Following the OAuth1 flow, a user should only need to authorize your app once. Hence, for that user, you should only need to request his/her access token + secret once from TripIt, after which you should save that access token/secret and reuse it for all future API calls.

Thanks.

Tariq
TripIt | Developer Advocate
