### ISSUE TITLE
Unable to find authorized request token

### ISSUE THREAD

**Issue by DheerajJariwal** [tripit/api#170]
Hello,

I am using tripit api for this i have created a account on tripit and get api key or secret key.by calling https://api.tripit.com/oauth/request_token I got a oauth token and oauth token secret.
but when i used this token it always gives me unauthorized error.
can you please resolve my issue.

Thanks
Dheeraj jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj, 

Thank you for using TripIt Api. 

The next step in your auth process is to redirect the user to the following page for getting authorization. 

Basically if you open a browser and paste the below url with the tokens you received in first step, you will be able to see a page to allow or deny the request. Once you click Allow, you are good to go for the Step 3.

`https://www.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>`

Follow http://tripit.github.io/api/doc/v1/index.html for the Step 3 and 4. 

Let me know if that helps. 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello,

Thanks for reply.
When i got request token and hit browser with given url : https://www.tripit.com/oauth/authorize?oauth_token=f73ad8d59415611d6f15e1c230675182a92e07fa&oauth_callback=%3Coauth_callback%3E

it always gives Access request failed error.i have also used c# code of it provided on Git in this request token is genreated but after parsing the request token it gives 401 Unauthorized error,

Can you please tell me how to resolve this issue.

Thanks
Dheeraj jairwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

I see in the url you have pasted the `oauth_callback=%3Coauth_callback%3E`, it should be a valid URL. 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Prasad,

Thanks for your reply my problem is solved now but i have a question for you.please see this.

One thing i also ask i want tracking of flight in my app.like if the flight is cancelled or delayed then i want something to inform my users for this.
so how push notification work in this.for this i will have to purchase tripit pro and what are the step to implement this.?

Thanks
Dheeraj Jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

Good to know that your authorization issue has been resolved.

We do not provide push notifications for flight alerts from our developer api. However, if your app users have TripIt app installed and they are subscribed for pro then they will get flight alerts. 

For developer api, we do send notifications whenever a change occurs in users trips. Please see below documentation for our notifications api.
http://tripit.github.io/api/doc/v1/notification.html

Please feel free to contact us with any further information.

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Prasad,

i would like to tell you my requirement.

I am creating a app.in which i used tripit api for providing my users to live tracking api.
in this my app user will registered a flight using tripit api.

so my first question is :
1.Every time when i call the api to get the flights then i will get the updated details?
2.http://tripit.github.io/api/doc/v1/notification.html according to this url i will get push notification from TripIt when a change occurs in a user's trips.so this changes is made automatically when the flight time is  changed.
3.for eg. i have registers a flight on 23-nov-2016 at 9.PM.so if the flight timining is changes due to some reason so will i get a notification or any updated result to know the changing time.

Thanks
Dheeraj Jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

The answer to your questions is Yes. You will get updated details for every time you call our api to get air object details and you will get notification for the mentioned use cases in second and third question.

I also want to bring this to your knowledge that we only monitor flights for users who have a pro subscription. So if a user of your app doesn't have TripIt pro we wont monitor his/her flight and we will not update the flight timings. 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Prasad,

Thanx for you reply.

I have one Question for you.
as i used tripit api in my mobile project.first i have to request for a token,after that as mentioned in documentation i got a token and secret key.i didn''t understand step 2. why would application redirect to tripit url.actually i do not want to redirect my user to this url.can i do external login like i hit tripit url via code?

Means every user who used my app must be create account in tripit.?

there is any solution for that.

and the second Question is : 

i mailed tripit to enable Basic authentication.when it will be on i wll not need OAuth authentication?

And the third one : 

when my app user add there flight data using tripit api then i would get everytime update details for thier flight so for that i need tripit pro sunscription or normally i will get updated information.

Thank's
Dheeraj jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

Every user who uses your app would need to have an account in TripIt. Third party apps asking the user to get access to their data, is standard OAuth process, just like you would do from Google or Facebook.

If you are using basic authentication you are not required to use OAuth authentication. 

For getting updated flight data for users, your users will need TripIt pro subscription.

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Prasad,

Actually i don't need OAuth authentication.for basic authorization i already mail tripit support but yet my account is not on for basic authentication.

can you enable my account for basic authentication.

Thanks
Dheeraj jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

The support team should get in touch with you regarding this. When did you mail them? 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Prasad,

I mailed them on 7th nov. after that i mailed again yeterday. please solve this if you can.

Thanks
Dheeraj Jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

I emailed the contacted the support team and they mentioned that they have already enabled web authentication for your account (ScreenName: dheerajjariwal)
Is there an error you are getting when you try to use it?

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Prasad,

![i71 cimgpsh_orig](https://cloud.githubusercontent.com/assets/11678177/20335191/856b62c8-abe6-11e6-9550-4f923f4fb5f6.png)

I got this error when using basic web authentication.

Thanks
Dheeraj Jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

The email address associated with your TripIt account is dheerajjariwal@gmail.com. I see in the above screenshot it is dheerajjairwal@gmail.com

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello parsad,

I got the issue thanks for that.

one thing is when i add any trip in tripit and want to get update flight information of that then i have to subscribe for tripit pro?

Thanks
Dheeraj Jariwal

**Comment by prasadkarkera** [comment]
Do you have a trip under that account?

**Comment by DheerajJariwal** [comment]
Hello parsad,

This issue is also solved. i had not add any trip now i added trip under my account and get the data successfully. but please tell me about my last Question that is : **one thing is when i add any trip in tripit and want to get update flight information of that then i have to subscribe for tripit pro?**

Thanks
Dheeraj jariwal

**Comment by prasadkarkera** [comment]
You are correct Dheeraj. You need to be subscribed to TripIt pro. 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Parsad,

did tripit support email forwarding.like if i forward mail my e-ticket to tript then it gives my xml data of that?
is it possible ?

Thanks
Dheeraj jariwal

**Comment by prasadkarkera** [comment]
Hi Dheeraj,

Not sure if I understand your question correctly. But, if you forward your e-ticket to TripIt, TripIt will create a trip itinerary out of it and when you request the trip details like you did earlier, it will give you xml data for that trip. 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Parsad,

The sample code which is given in Guithub for c#.in this basic web authentication code is missing can you provide me that,

Thanks
Dheeraj Jariwal

**Comment by DheerajJariwal** [comment]
Hello Parsad,
when my app user forward there e-ticket to to me and i forwarded that to plan@tripit.com.
so i want to get the information of my app user in the xml file is it possible?

Thanks
Dheeraj jariwal

**Comment by prasadkarkera** [comment]
Yes, that would add the e-ticket into your account as your trip. Then you do the same api call you did earlier to get the trip details in xml. 

Thanks
Prasad

**Comment by DheerajJariwal** [comment]
Hello Parsad,

Oky when my app user forward e-ticket to me and then i forwarded it to my tripit account and trip is added as my trip.but when i get the details then i will not get any information of the user who forwarded e-ticket.there is any way to get atlest his email id.

Thanks
Dheeraj jariwal

**Comment by hliss** [comment]
Hi,

This is really not how you should be using TripIt nor how an end user should be using your application. 

If you'd like to develop an app to deal with bookings made by other users, **they should have TripIt accounts** and they should forward their emails to plans@tripit.com themselves. It won't do you any good to have others' trips in your account. 

Then, the user can authorize your application to use their TripIt account via OAuth (see Authentication at http://tripit.github.io/api/doc/v1/index.html), and you can fetch their data this way. There's no support for the method you describe because it's a bit of an anti-pattern.

Hope that helps.

-Harold

**Comment by devcrux** [comment]
Hello Parsad,

I'm try to get the trip object after passing through authentication successfully but I keep getting the response below:

 <Response><Error><code>401</code><detailed_error_code>104.100000</detailed_error_code><description>invalid signature</description></Error></Response>

My code have been working before but suddenly stopped without any changes made to it.

I have attached my code snippet (VS 2105, UWP).

Kindly help out.

Thanks
- Oludayo

[gettripcode.txt](https://github.com/tripit/api/files/601863/gettripcode.txt)
