### ISSUE TITLE
Invalid Signature - Is the API still supported?

### ISSUE THREAD

**Issue by devcrux** [tripit/api#171]
Hello,

I'm try to get the trip object after passing through authentication successfully but I keep getting the response below:

401 104.100000 invalid signature

My code have been working before but suddenly stopped without any changes made to it.

I have attached my code snippet (VS 2105, UWP).

Kindly help out.

Thanks

- Oludayo

[gettripcode.txt](https://github.com/tripit/api/files/601865/gettripcode.txt)

**Comment by hliss** [comment]
(Closing old issue -- please do file a new one or reopen should this still be an issue, or contact api-support@tripit.com with specific questions for debugging outside public github issues.)
