### ISSUE TITLE
Generic Email Format for Itinerary Imports

### ISSUE THREAD

**Issue by bpholt** [tripit/api#172]
Is there a generic email format I can use to send lodging information to my users in a way that they can easily forward to TripIt and have it added to an itinerary? If it's documented somewhere I will adapt the emails we send to guests accordingly.

**Comment by hliss** [comment]
Hi @bpholt, this page should have all the info you need. Cheers!

https://tripit.zendesk.com/hc/en-us/articles/226108747-Vendor-confirmation-email-support
