### ISSUE TITLE
OAuth2 after getting apikey and apisecret

### ISSUE THREAD

**Issue by kavithasubin** [tripit/api#175]
I registered our organization's app in TripIt.I got both api key and apisecret.
How can I get Oauth2 with apikey and apisecret.I am not clear from api documentation

Thanks
Kavitha

**Comment by hliss** [comment]
OAuth 2 is currently not supported via the TripIt API. You can use OAuth 1.0a to access the API as soon as you've registered your key! You can find the OAuth guide here: http://tripit.github.io/api/doc/v1/index.html
