### ISSUE TITLE
Create Trip Api

### ISSUE THREAD

**Issue by kavithasubin** [tripit/api#176]
I have done basic auth in jdeveloper.
GetTrip API ,ListTrip API are working.
Create Trip API is giving 400error while giving trip object request xml  from API document.
URL used:https://api.tripit.com/v1/create
Is Oauth required to avoid this?

**Comment by hliss** [comment]
Hi @kavithasubin, I see that basic auth is enabled for you. Your `POST` requests to `v1/create` the day you opened this issue did not contain the `xml` parameter in the post body. In http://tripit.github.io/api/doc/v1/index.html#method_create, note: 
> The client must POST a single Request object as the value of the request parameter `xml` in the POST body of the request.

Start there? Alternatively, you may post JSON with the `json` request parameter.
