### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by cemre** [tripit/api#177]
My app also stopped working without me making any modifications. To make it easier for you to debug, I tried executing the sample `get_request_token.php` that comes in the PHP binding package. I'm getting the same "104 invalid signature" error.

I added some debug statements in the bindings to verify how the request is being made. Everything looks right to me here.

base: POST&https%3A%2F%2Fapi.tripit.com%2F%2F%2Foauth%2Frequest_token&oauth_consumer_key%3D498dd84cfa98be525336966ec65e9ef69e651893%26oauth_nonce%3D4e5bce15737c33c25ce6cb5cc8db6616%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1482726701%26oauth_version%3D1.0

key: //my api secret//&

hash: 2zJoIy3naAbtHlOr+n+oyuL+3rw=

**Comment by mamund** [comment]
this is blocking some year-end reporting for me. hope this gets sorted ASAP.

**Comment by hliss** [comment]
Hiya,

After some research, I have one question for you, @cemre and @mamund: Is this limited to the PHP bindings? 

I've found that changing the bindings (`tripit.php`) from `'/oauth/request_token'` to `'oauth/request_token'` seems to work, calling the file like `php get_request_token.php https://api.tripit.com {key} {secret}`. I'm not sure enough in what changed to push this change to the bindings live at the moment, but hopefully this is a sufficient workaround to resolve your immediate blockers.

**Comment by cemre** [comment]
Harold's suggestion solved my issue. Thanks harold!
