### ISSUE TITLE
OAuth_signature incorrect

### ISSUE THREAD

**Issue by kavithasubin** [tripit/api#178]
Hi
 I tried with below link to get OAuth_request_token.Getting error as Invalid Oauth_Signature.

https://api.tripit.com/oauth/request_token?oauth_consumer_key=11f648c768bf2fa26039f14e9cecefc8749b29fc&oauth_timestamp=1482858797&oauth_signature_method=HMAC-SHA1&oauth_nonce=a2F2aXRoYS5zdWJpbkB3YXkuY29tMTI=&oauth_signature=MTZlNmJhZTM3ZTViMTA3NWQwYmRlNmE5NDQ1MTBkZDQwMDQ1MGE1Mg==&oauth_version=1.0

How should I get correct OAuth signature??
![invalid signature](https://cloud.githubusercontent.com/assets/24724777/21505065/e41885ce-cc18-11e6-81fd-0867e0011a5a.png)

**Comment by kavithasubin** [comment]
Hi,
As i mentioned earlier i was getting 401-Invalid Signature error when trying to fetch request token. In SoapUI i am getting 400 Bad Request error.
Can you confirm whether my API Key is still valid and active ? Is that the reason for my errors?
Please respond ASAP. My whole integration is blocked.

Thanks
Kavitha
Way.com

**Comment by hliss** [comment]
Hi @kavithasubin, your application is still active. I'd not use a browser to issue request_token HTTP requests; you will want to issue these requests with those OAuth parameters in the `Authorization` header.

If you are using the PHP bindings as noted in #177, try the solution there (or a similar one if that's the issue you are having!)

I also see that your application had some successful attempts at the `oauth/request_token` API later in the day; did you resolve this issue?

**Comment by kavithasubin** [comment]
Thanks Harold. Will look into it.

**Comment by kavithasubin** [comment]
Hi ,

I got unauthorized oauth token and token secret. While trying to authorize it, i am giving the callback url as https://www.tripit.com . i am getting a success response 200. I logged into the site, But i am not sure from where i am supposed to confirm it. I didn't get any email.
Plz help on that.

**Comment by kavithasubin** [comment]
I am getting Invalid form submission in postman. Plz respond

**Comment by kavithasubin** [comment]
![screen shot 2016-12-29 at 1 21 07 pm](https://cloud.githubusercontent.com/assets/24724777/21555109/fa9b5b84-cdc9-11e6-84a2-7a84e212d46b.png)

**Comment by hliss** [comment]
Addressed in #179, closing this issue.
