### ISSUE TITLE
oauth step2: Access Request Failed

### ISSUE THREAD

**Issue by kavithasubin** [tripit/api#179]
Hi,
I am getting the below error at step 2 (oauth 1.0)
**Access Request Failed
Please go back to the application or website where you began the process and try again.**

Do i need to make any changes in my account? Plz respond asap.

Thanks
Kavitha
Way.com
![screen shot 2016-12-30 at 11 32 25 am](https://cloud.githubusercontent.com/assets/24724777/21571432/45f51d4e-ce84-11e6-96f2-0ef781961946.png)

**Comment by hliss** [comment]
You need to provide a fully qualified callback URL to this request, URL scheme (http/https) included. That's why these requests were rejected today.
