### ISSUE TITLE
Getting 400 error for POST

### ISSUE THREAD

**Issue by kavithasubin** [tripit/api#180]
We tried to GET trip service from your API.It is working while doing basic authorization.

But below posting is giving error.
POST https://api.tripit.com/v1/create

[xmlrequest.txt](https://github.com/tripit/api/files/679359/xmlrequest.txt)(Please check the posted xml)

Response:

 The invocation resulted in an error: .

<Response>
<Error>
<code>400</code>
<description>Input cannot be null or an empty string.</description>
</Error>
</Response>

Is this website problem?
How can we solve this problem?
............................................................................................
We got this mail from you:
Hi @kavithasubin, I see that basic auth is enabled for you. Your POST requests to v1/create the day you opened this issue did not contain the xml parameter in the post body. In http://tripit.github.io/api/doc/v1/index.html#method_create, note:
The client must POST a single Request object as the value of the request parameter xml in the POST body of the request

**Comment by hliss** [comment]
Hi, yes, like I said in #176, this string must be given as the value of an `xml` query string parameter in your request body. That's still not present, so the request will fail with a 400.
