### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by iphilgoodtahiti** [tripit/api#181]
Hi,
Is There somebody who could explain why request Invitation doesn't work?
I tried this :
`<Request>
   <Invitation>
      <EmailAddresses>
         <email_address>xxx@gmail.com</email_address>
      </EmailAddresses>
      <TripShare>
         <trip_id>99999999</trip_id>
         <is_traveler>true</is_traveler>
         <is_read_only>false</is_read_only>
         <is_sent_with_details>true</is_sent_with_details>
      </TripShare>
   </Invitation>
</Request>`

and response is :
SimpleXMLElement Object
(
    [timestamp] => 1483141097
    [num_bytes] => 274
    [Error] => SimpleXMLElement Object
        (
            [code] => 400
            [description] => Attempted to unserialize unknown entity type: Invitation
            [entity_type] => Invitation
            [timestamp] => 2016-12-30T15:38:17
        )

)

Thanks

**Comment by hliss** [comment]
Hi @iphilgoodtahiti, try using `/v1/invite` instead of `/v1/create`, and I'll make sure we update our documentation!

**Comment by iphilgoodtahiti** [comment]
Hi @hliss, thanks a lot! I added function in tripit.php... I never found this information in documentation... Happy New Year!
