### ISSUE TITLE
Planner

### ISSUE THREAD

**Issue by iphilgoodtahiti** [tripit/api#183]
Hi and Happy New Year !
How could I use API to generate travels as a planner only and share them to corresponding travelers email address ?
Thanks
Regards,
Philippe

**Comment by prasadkarkera** [comment]
Hi @iphilgoodtahiti, 
After you create a trip you will have to make a separate call to /v1/invite. That should help you share your trip with corresponding travelers.

**Comment by iphilgoodtahiti** [comment]
Thank you @prasadkarkera,
but I would like to be able to create several trips for different travelers and use my TripIt account as planner only. It seems it's not possible...

**Comment by prasadkarkera** [comment]
Yeah you are right, at the moment its not possible to create a trip as a planner.
