### ISSUE TITLE
Can't Unit Test requestToken, access_token from PHP CLI

### ISSUE THREAD

**Issue by sujit-baniya** [tripit/api#185]
How can I test the endpoints using PHPUnit from PHPCLI? I tried a lot with OAuth but no success.

**Comment by prasadkarkera** [comment]
Can you tell me on which step of Oauth are you getting an error?

**Comment by sujit-baniya** [comment]
When I tried to use the API via browser, I was redirected to signin and  able to authorize the token by signing in from browser and that gave me token and secret.

But in PHPUnit, I'm unable to authorise the token as it doesn't redirect to signin via phpunit or cli and gave me error of unauthorized token.

So, Is there any endpoint for signing in instead of browser redirection?

**Comment by prasadkarkera** [comment]
Since your TripIt app is trying to access a user's resources, we need explicit permission from the user to allow your app to access the user's resources. 
There is no other way to get the user's permission.

**Comment by prasadkarkera** [comment]
You can always switch to basic authentication where you pass the user's username and password to gain access to the user's resources.
