### ISSUE TITLE
Access Request Failed IOS

### ISSUE THREAD

**Issue by andriypohorilko** [tripit/api#186]
Hello. Could somebody provide clear explanation, what urls should I provide when authorize Tripit account? I found example to authorize bitbucket account:

let oauth2 = OAuth2CodeGrant(settings: [
            "client_id": "my_swift_app",
            "client_secret": "C7447242",
            "authorize_uri": "https://github.com/login/oauth/authorize",
            "token_uri": "https://github.com/login/oauth/access_token",   // code grant only
            "redirect_uris": ["myapp://oauth/callback"],   // register your own "myapp" scheme in Info.plist
            "scope": "user repo:status",
            "secret_in_body": true,    // Github needs this
            "keychain": false,         // if you DON'T want keychain integration
            ] as OAuth2JSON)

oauth2.authorize()

**Comment by vsejpal** [comment]
Thank You for your query @andriypohorilko!

For auth-grant look at Step 2 of our official [api documentation ](http://tripit.github.io/api/doc/v1/index.html#authentication_section), specifically the `oauth_callback` parameter.

> This is the callback URL that TripIt will use upon successful access token authorization. This parameter is optional if you associated a URL with your application when you registered it and obtained your OAuth consumer key and secret. If you supplied a URL when you registered the application, providing this request parameter will override that value. If neither the application URL is set nor the oauth_callback parameter is supplied the user will get an error when taken to the /oauth/authorize page and will be unable to authorize the access token. It is highly encouraged that you explicitly provide an oauth_callback URL when linking to the /oauth/authorize page. Providing this URL gives you the flexibility of defining a different URL that is associated with your action on which you can provide marketing text and a description of your application and what it does.

Hopefully that helps!

**Comment by andriypohorilko** [comment]
Thanks for a reply! What oauth_callback and where should I provide?

**Comment by vsejpal** [comment]
Hi @andriypohorilko,

For authorizing the request token, you will need to redirect users to our authorization URL which looks like `https://m.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>`

> NOTE:
 It is extremely important that you clearly redirect the user to the TripIt URL so they have confidence that they aren't being phished for their TripIt username and password. This means you should make sure on a regular browser that the frame you use to redirect the user has the address bar of the frame clearly visible. On a mobile device such as an iPhone you should launch Safari and not use the embedded WebView class.

Once the user enters her/his TripIt credentials on the authorization form, you may want to return this user back to your site/app.

`oauth_callback` parameter could be supplied the exact URL of your site/app where you would like TripIt to re-direct user's browser to upon successful authorization.

More Reading: https://oauth.net/core/1.0/#auth_step2

**Comment by andriypohorilko** [comment]
Thanks, but where can I get oauth_signature for Step1?

**Comment by vsejpal** [comment]
Hi @andriypohorilko,

The `oauth_signature` value is supposed to be generated based on the signing algorithm. If you are developing using Java, PHP, Objective-C, Ruby, C#, Earlang, PERL or Python, checkout one of our SDKs a.k.a "[bindings](https://github.com/tripit)". These SDKs abstract away the need for you to generate the signature altogether.

To see how our Python binding works (as an example), checkout my response [here](https://github.com/tripit/python_binding_v1/issues/3)

Thanks
