### ISSUE TITLE
TLS 1.0 no longer supported

### ISSUE THREAD

**Issue by mhallin79** [tripit/api#187]
Hi there,

I been using the API since 2012 and as of last week every request to create a new trip returns an error similar to this,

`An error occurred while processing your request. Reference #25.279c3e17.1492494540.4d23a21`

Any way of getting more details as to what the problem is? 

Cheers!

Mikael

**Comment by hliss** [comment]
Hiya,

It looks like your app is able to send traffic -- can you please confirm that it's working, or is `create` alone still throwing an error like the above? Thanks!

**Comment by mhallin79** [comment]
Hi Harold,

Many thanks for responding.

Yeah I managed to get it semi working. A couple of days after posting this request I noticed that the error message changed from 

> An error occurred while processing your request.  

to

> 404 - Not found 

This change in the response was actually quite helpful for my troubleshooting as not knowing if the API is still active and supported led to the inevitable question - have the new owners, Concur decided to close it down?

First I double checked that it was definitely not something we had done, and I cross referenced our API logs with deployment logs and as you can see from this picture we didn't do any deployments around the time the errors started (all times in UTC),
![image002](https://cloud.githubusercontent.com/assets/5432014/25302716/cf3c8644-2787-11e7-808a-b07ddd2957ab.jpg)



And here you can see how it "just stopped working" (times in AEST),
![image004](https://cloud.githubusercontent.com/assets/5432014/25302725/2e7ceb8a-2788-11e7-993e-872a1db83b4b.jpg)

So determined to solve the problem I then fired up Google Postman and used my OAuth credentials to post my XML to `https://api.tripit.com/v1/create`. I now got an `401 - Unauthorized` response. So I tried something less complex and hit the `https://api.tripit.com/v1/list/trip` with a GET request and it worked. 

In the absence of any response from TripIt support this was great as it confirmed that the API was still active.

Long story short I then noticed that when my server hit the API the 404 was returned by an Apache server,
![image005](https://cloud.githubusercontent.com/assets/5432014/25302667/923b7300-2786-11e7-9085-cf04df61fb2a.jpg)

And when I used Google Postman the API response was returned by a NGINX server,
![image006](https://cloud.githubusercontent.com/assets/5432014/25302674/cfd71098-2786-11e7-8f1d-81f2e32c56b0.jpg)

Thus I was able to make the conclusion that there must be a network layer issue. Playing around a little bit more I realised that the 404 was returned when using TLS 1.0 and it worked when TLS 1.1 or 1.2 was used.

As my servers do support TLS 1.0, 1.1 and 1.2 it took me a while to figure out why TLS 1.0 was used instead of 1.2 but once I did I could force my app to hit the API using TLS 1.2 and I could successfully retrieve profiles, list trips & get details of a trip. We are still using the supplied [C#
 binding from 2012](https://github.com/tripit/csharp_binding_v1).

However after all this I do still get an `401 - Unauthorized` response when trying to create a new trip or add new objects to an existing trip. 

This is causing a bit of an issue as when we "synchronise" trips that were created prior to the 11th of April it causes the unwanted side effect of empty trips as we are allowed to remove old objects but not authorized to create new ones.

This is leaving our clients with empty trips in their TripIt library until there is a solution to this issue. We have made a conscious decision to remove these objects until we can create new one as its our view that no data is far better then incorrect data.

Example from my API log retrieving a trip, deleting objects and trying to add new objects to the trip,
![issues](https://cloud.githubusercontent.com/assets/5432014/25302777/97c9858e-2789-11e7-9282-53e736a24deb.png)

Additionally we are unable to create new trips for any new bookings post 11 April. 

I am well aware that the above is a very long explanation of my journey but hopefully it will help someone else to figure out the TLS 1.0 issue much faster then I did.

And if anyone else out there is using the Microsoft stack then this is the magic oneliner that forces TLS 1.2 in .Net 4
```
            // In .Net 4.6 and above TLS 1.2 is default.
            // In .Net 4.5 we need to explicitly set it like this, 
            // ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            // In .Net 4 we need to force it like this,
            ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
```
I have created a [pull request](https://github.com/tripit/csharp_binding_v1/pull/3) in the GitHub C# binding for you to review (as the project targets .Net 3.5 I'm not sure it will work so I left the code commented out).

I do appreciate if you can assist me in getting the 401 issue resolved as soon as possible as we have a lot of clients complaining.

Many thanks!

Mikael

**Comment by hliss** [comment]
@mhallin79 **Great** call stumbling across TLS versioning! We are indeed deprecating support for TLS 1.0 HTTP-wide (as is percolating through the industry in the first half of this year). That, of course, helps distill down the multiple issues contributing to the errors you see.

It looks like your v1/create calls are throwing 401s due to an invalid OAuth signature (which should be reported in the response body). That's where to continue looking. Please do note that, admittedly idiosyncratically, the POSTed XML or JSON should be in a query string in the POST body, e.g., `xml=<...` or `json={...`. If you need more help tweaking the OAuth base string calculations, please email api-support@tripit.com for some off-public-forum debugging. 

I'm sure you can tell by now, but I can definitively state that the API is still supported in its entirety. I'll additionally have us update all bindings to include and enforce support for TLS 1.2. (This may involve your pull request being closed and replaced with actual code!) 

Hopefully this is able to help resolve your issues quickly and get all your users' trips synced! Thank you!

**Comment by mhallin79** [comment]
Thanks for your response Harold!

I'm all for removing TLS 1.0 support and we also have that on our 2017 road map. 

As part of our API logging mechanism we do log the response body but unfortunately we had a hack to intercept any 401 and re-throw them as a TripItAuthorisationException enabling us to add some business logic to prompt the user to re-authenticate our application. As such the response body wasn't logged so I didn't have access to the detailed error. 

Having said that I don't think the detailed error was much help as the reason for the 401 was actually due to me changing the content type from `application/x-www-form-urlencoded` to `application/xml` while troubleshooting the 404. In my naivety I thought surely posting a `web form` to an API must be the issue as the payload is XML. How wrong was I! And your response above about the idiosyncrasy of how to post the XML greatly assisted me to pinpoint the issue. Maybe a future enhancement to the the API could return a [415 Unsupported Media Type](https://httpstatuses.com/415) instead of a 401?

I have changed the content type back now and it all seems to work as prior to the 11th of April.

Thanks for your help!

Mikael
