### ISSUE TITLE
Failed to get a TripIt authorization URL

### ISSUE THREAD

**Issue by alexihg** [tripit/api#188]
Hello can you please help Im getting this exception,
 Failed to get a TripIt authorization URL

Please note that we have an api that creates the request-autorization succesfully on test enviroments.

**Comment by hliss** [comment]
Hiya,

I need to ask for more information here as to why this would happen. Feel free to privately send your client ID to api-support@tripit.com to positively identify the cause.

The most common issue in this case is an expired request token; if you wait more than five minutes to authorize the request token or later to exchange an authorized request token for an access token, you will not be able to proceed and must re-start the OAuth authorization process by obtaining a new request token.

Hopefully this helps; if you're experiencing errors within a five-minute window, please do identify your application and we'll get it sorted.
