### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by nchem** [tripit/api#189]
I am trying to get a token but always facing an invalid signature. 

http://term.ie/oauth/example/client.php
endpoint: https://api.tripit.com/oauth/request_token
consumer key: 9d7016992599289c0f8e30bf8bb813dc721f6e74

I contacted the support and they told me that my account was not authorized and they grant me the right. 

But still I am facing a problem. 

Request: https://api.tripit.com/oauth/request_token?oauth_version=1.0&oauth_nonce=e1e80fd9c6248c75b8380843dddfa38b&oauth_timestamp=1493217404&oauth_consumer_key=9d7016992599289c0f8e30bf8bb813dc721f6e74&oauth_signature_method=HMAC-SHA1&oauth_signature=CzTn4KkoENaT%2BuXIQXrxrYz3pnM%3D

<Response>
<Error>
<code>401</code>
<detailed_error_code>104.100000</detailed_error_code>
<description>invalid signature</description>
</Error>
</Response>

Can you help please?

**Comment by nchem** [comment]
Can someone help please? :(

**Comment by prasadkarkera** [comment]
Hi,

You need to send a POST request with the data in the Authorization header

Thanks
Prasad
