### ISSUE TITLE
Timeout when requesting auth token

### ISSUE THREAD

**Issue by cspeper** [tripit/api#19]
I'm using oauth-tripit gem (in Rails), but all my request_token POSTs time out.

I copied the headers from one of the oauth requests before it was made and I can make the same POST with curl and the response comes back fine with a valid token:

curl -X POST --header 'authorization:OAuth oauth_body_hash="2jmj7l5rSw0yVb%2FvlWAYkK%2FYBwk%3D", oauth_callback="http%3A%2F%2Flocalhost%3A3000%2Fauth%2Ftripit%2Fcallback", oauth_consumer_key="?????????????????????????????????", oauth_nonce="eCI2gghWlgsx5pyM9VfEjgfRNmRA18Ir8BkepMAfas", oauth_signature="NZ2FwcxJHDC9fvDrk9vLX8RXbfI%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345477683", oauth_version="1.0"' --header '_/_'  --header 'OAuth gem v0.4.6' --header '0' https://api.tripit.com/oauth/request_token

(I removed the consumer_key in this ticket)

Is there any reason why the API wouldn't respond to a request from rails but would from curl? How could it tell the difference?

Let me know if there's any other relevant information I could share.

Thanks,
Scott

**Comment by cspeper** [comment]
I resolved this issue by installing my Ruby with SSL.  It might be a good idea to respond with a more useful message rather than timing out.

**Comment by tariqislam** [comment]
Thank you for the feedback, we will take that into consideration.
