### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by MortenVelling** [tripit/api#191]
Hi,
I am performing a HTTP GET to https://api.tripit.com/v1/list/trip/include_objects/true/modified_since/1491347468?page_num=1&page_size=200
The request submitted is:
**GET https://api.tripit.com/v1/list/trip/include_objects/true/modified_since/1491347468?page_num=1&page_size=200 HTTP/1.1
Content-Type: application/xml; charset=utf-8
Authorization: OAuth realm="https://api.tripit.com/", oauth_consumer_key="******", oauth_nonce="399811", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1493252031", oauth_token="******", oauth_version="1.0", page_num="1", page_size="200", oauth_signature="MI%2b%2bjj%2f9kzAZbZ9Nh8tv8jroP2M%3d"
Host: api.tripit.com
Accept-Encoding: gzip, deflate
Connection: Keep-Alive**

What would cause the TripIt API to return the following response?:
**HTTP/1.1 404 Not Found
Server: Apache
Content-Type: text/html; charset=iso-8859-1
Content-Length: 16
Date: Thu, 27 Apr 2017 00:13:52 GMT
Connection: keep-alive

File not found."**

all characters included - that means the " at the end too.

This happens on some servers but not on others, so obviously this could very well be tied to a local problem of sorts, but I was wondering if you had a take on it?

Regards,
Morten

**Comment by hliss** [comment]
Hi @MortenVelling, please try connecting with TLS version greater than 1.0? I'd suggest 1.2 to be extra safe.

**Comment by MortenVelling** [comment]
Hi Harold,
has TripIt made any changes to support TLS versions recently? This solution has been running for 2 years, and I haven't come across this issue until a couple of months ago? The initial handshake to establish the secure channel seems to be successful viewed through Fiddler.
Regards,
Morten

**Comment by MortenVelling** [comment]
Hi Harold,
we are using BizTalk 2013 to connect to the TripIt API. BizTalk by default uses TLS 1.0, and one actively has to change registry and reboot the server to force it to use TLS 1.2. Since this has not been done on the servers in question, I am farily confident we have been using TLS 1.0 in the past 2 years without any problems.
Do you see any changes on your side that could have caused this change in behaviour?
Regards,
Morten

**Comment by hliss** [comment]
Hi @MortenVelling, can you please validate whether this is still happening? I think we were able to pinpoint this. Thanks!

**Comment by MortenVelling** [comment]
Hi @hliss , yes that resolved the problem right away. Sorry for not confirming sooner. In the meantime I have learned from other sources that TLS 1.0 support is being removed from the APIs on 15/5. Can you please confirm? Two weeks notice on a change like this seems pretty short, to be honest. Will this affect all aspects of TripIt (website, embedded pages, APIs, etc.)?
Regards,
Morten

**Comment by hliss** [comment]
Hi @MortenVelling, thanks for confirming that it's been working and of course thank you for using the API for so long! I can confirm that TLS 1.0 support will be removed for all HTTPS requests (web, API, etc.), as TLS 1.0 no longer fits our security protocol standards. Website users using TLS 1.0 will see an informational page advising them to upgrade their browsers. API users, however, will simply be unable to connect via https. We're always available to help and answer questions if needed.
