### ISSUE TITLE
TripIt OAuth login screen doubles as a sign up form

### ISSUE THREAD

**Issue by bohwaz** [tripit/api#193]
If you enter an email address that doesn't have a tripit account in the TripIt OAuth login screen, Tripit will silently create an account with that email address.

This is pretty confusing behaviour for the user frankly, as if you do a typo in your email address it will just look like everything is fine, but you won't get your own data.

This is confusing and it is not even advertised on the sign in page.

**Comment by garyhooper** [comment]
The default for the OAuth pages should be Sign In, not Sign Up.

**Comment by VickiWis** [comment]
Hi Gary,

Thank you for using TripIt Api.

Yes, this is a known problem and has currently been put into the queue for one of our development teams.  Unfortunately, I do not have an estimated date for when they will work on this issue.  Just know that it will be fixed.

Thanks,

Vicki

**Comment by hliss** [comment]
Hi @bohwaz @garyhooper: just following up to let you know that the fix for this has been rolled out and you should no longer see new accounts created for erroneous sign-in attempts.

**Comment by bohwaz** [comment]
Thanks @hliss this is closing our client bug.
