### ISSUE TITLE
TripIt API forwarding to Carey limousine service when near airports?

### ISSUE THREAD

**Issue by willpowersdev** [tripit/api#195]
I'm not sure if this is coming through TripIt or if it's just part of the local airport wifi, but it seems like TripIt is launching the Carey limousine app after signing in.  Can I get a confirmation of this?

**Comment by VickiWis** [comment]
Hi gyrocade,

Thank you for using the TripIt Api.

TripIt does not launch the Carey limousine app, so it must be part of the local airport wifi.  Sorry that you are experiencing this issue.

Thanks,

Vicki
