### ISSUE TITLE
Is there a way to forward users directly to the Sign In page instead of the Sign Up page?

### ISSUE THREAD

**Issue by willpowersdev** [tripit/api#197]
I'm using the GTM OAuth 1 toolkit for iOS, and it appears that there is no way around TripIt's redirection once it receives a request token to the Sign Up page.  Please correct me if I am mistaken.

We are planning on integrating TripIt into a very large AAA app with millions of active users, so I would like to get this working properly.

If it isn't possible to correct where the redirect goes, is it possible to create a custom TripIt login on our end that forwards the username and password to TripIt and then receives the authentication token?

**Comment by garyhooper** [comment]
I have TripIt integrated with OAuth1.  It is going to the TripIt sign up page; I have not found a way to display the Sign In page as opposed to the Sign Up message.  I message users in advance to warn them.

**Comment by hliss** [comment]
Hiya, thanks for bringing up the default. We'll evaluate the traffic patterns we see, and if it makes sense, we'll change default signed-out behavior to sign in rather than sign up.

**Comment by hliss** [comment]
Closing this issue -- we did evaluate the traffic patterns and sign-up did prevail. 

However, try appending `&is_sign_in=1` to the URL! That gave me the correct page when I just tried it. :) Can't guarantee this will always work, but should give you a breather for the foreseeable future.
