### ISSUE TITLE
Places normalized to English

### ISSUE THREAD

**Issue by Amantel** [tripit/api#198]
Hello! 

Is there a way to get primary address in English?

For example, for the city of Malmo I get 
`address:"Malmoe, Sweden"
city:"Malmo"
country:"SE"
latitude:"55.600000"
longitude:"13.000000"
state:"Skåne"
zip:"200 01"`

I need to get state as "Skane" to pass to some other API's. Is there a string I can put in my request to get in English?

**Comment by hliss** [comment]
Hi @Amantel, great question! We currently do not localize or translate any address components. What you see is exactly what we were able to extract from a confirmation email or what was posted to our API (and geolocation extensions such as the "state"), and data therein can contain Unicode.

You should be able to find libraries in your programming language of choice to normalize Unicode strings to ASCII; they appear to implement methods defined by the Unicode Consortium here: http://unicode.org/reports/tr15/ (this may be more information than you want!). Hope that helps!
