### ISSUE TITLE
Travel Stats?

### ISSUE THREAD

**Issue by khargy** [tripit/api#199]
Is there any way to use the API to get the Travel Stats? (The box on home page that shows Trips/Days/Distance/Cities/Counties).

**Comment by VickiWis** [comment]
Hi @khargy, that is a great question!  Currently we do not have an endpoint to support travel stats.  The stats that you see on the home page are calculated dynamically.  You could create your own travel stats by obtaining all the users trips and calculating the stats that you want.  Thanks for your input.

**Comment by khargy** [comment]
Thanks, I was thinking about calculating it myself, but calculating the distance traveled seemed kinda complicated. I was able to get the data I need from a screen scrape for now.
