### ISSUE TITLE
Basic authentication fails using C# sample code

### ISSUE THREAD

**Issue by jhazelwood** [tripit/api#20]
Hi,

I created a TripIt account this morning and had the support team enable basic authentication.

I tried the following using the C# sample code:

```
        WebAuthCredential cred = new WebAuthCredential("emailaddress", "password");

        TripIt.TripIt ti = new TripIt.TripIt(cred);

        TripIt.TravelObject.Response resp = ti.ListTrip();
```

I get back a 401 - Unauthorized

I also tried the curl call from your Web Authentication example.  This gets a 401 as well but with the message "consumer key not present in request".

Am I missing something?

**Comment by tariqislam** [comment]
Hi,

I would like to help you, but I need more details to debug the situation. Could you please provide details such as:
- Your oauth consumer key
- Around what date/time you performed the request
- The request and response headers and content, and url you are making the API call to
- Any other parameters/settings you are using

Thanks.

Tariq
TripIt | Developer Advocate

**Comment by jhazelwood** [comment]
Hi Tariq,

Do I need an oauth consumer key to do basic authentication?  I thought I could explore the api and then implement oath.

Thanks,

Jon

**Comment by tariqislam** [comment]
Hi Jon,

Yes, you do not need an OAuth key to explore the API using the basic authentication. Could you give me your email address/user name for the account which you  had basic authentication enabled? You can email it to me at tariq@tripit.com.

Thanks.

Tariq
