### ISSUE TITLE
Can the API be used to directly Log In to an existing account without visiting the website?

### ISSUE THREAD

**Issue by willpowersdev** [tripit/api#202]
I would like to design a custom log in for our app.

**Comment by aksharachaturvedi** [comment]
You can probably do this using 'Web Authentication'. This is disable by default so you'll have to send an email to 'support@tripit.com' to get it enabled. 

Please, refer to the authentication section of the api documentation for more details. http://tripit.github.io/api/doc/v1/index.html#authentication_section
