### ISSUE TITLE
How to get user home airport using API

### ISSUE THREAD

**Issue by Amantel** [tripit/api#204]
Hello! 
Is it possible to get user home airport using API? 
I tried both /list/trip and /get/profile/**ref** and in both cases I have profile without user private information, including the airport. 

Thanks in advance!

**Comment by k-wiz** [comment]
Hello! 
Only the profile owner can view private profile information. Unfortunately home airport is NOT available at all via the API (but home city is).

**Comment by Amantel** [comment]
Jepp, that is what I gathered from the behavior :) 
Thanks!
