### ISSUE TITLE
TripIt API (Populating a flight-tracking or trip planning application)

### ISSUE THREAD

**Issue by osbornegus1** [tripit/api#208]
Looking to add the API to our website.
Specifically referring to the Use Cases as listed in the Developer API section;

--Providing an "Add to TripIt" link on a travel booking confirmation page
--Sending TripIt flight arrival details to schedule airport pick-ups
--Populating a flight-tracking or trip planning application with a TripIt traveler’s upcoming flights

We are particularly interested in no3.

We would like to utilize how TripIt captures user flight/itinerary information from emails. Allowing us to add that information (user needs to approve entry) to our website/database. We do not have an Application at this point.

Can we incorporate the API to our website in this fashion? Do the users need the TripIt app installed?

**Comment by gazure** [comment]
Hi there!

Yes, you can TripIt's API to grab TripIt users' flight and itinerary information into your application. As you said, users need to approve your access to their data at TripIt, details on how to do this can be found in the [v1 API documentation](http://tripit.github.io/api/). Users do not necessarily need to have the mobile app installed as they can manage their itineraries at the [TripIt website](https://www.tripit.com) too.

Hope your development goes well!

**Comment by rsdsonu** [comment]
Hi,

i am developing API for Our own APP. We want to know can we use tripit API for sending confirmation mail to our own mail ID and that flight info should be populate in our own APP is that possible with tripit API.

please help me regarding this if is there any knows

Thanks

**Comment by hliss** [comment]
Hi @rsdsonu, you are able to retrieve travel plans that have been forwarded to plans@tripit.com from your authorized users. There aren't any "custom" email addresses; all forwarded mail goes through plans@tripit.com. Thanks!
