### ISSUE TITLE
OAuth Clarification

### ISSUE THREAD

**Issue by IanGClifton** [tripit/api#21]
I'm trying to integrate TripIt into a mobile app, so the first step is OAuth support.  Everything seems to be working except that the final step (getting the authorized access token via https://api.tripit.com/oauth/access_token) is failing with a 401:

<Response><Error><code>401</code><detailed_error_code>104.1</detailed_error_code><description>invalid signature</description></Error></Response>

I noticed that the TripIt documentation for step 3 (http://tripit.github.com/api/doc/v1/index.html) lists the oauth_token_secret as a required parameter; however, the official documentation does not include it at all (http://oauth.net/core/1.0/#auth_step3).  Whether including it or not, I'm getting the same error.

**Comment by tariqislam** [comment]
Hi Ian,

Could you give me more details on the issue? E.g. http headers sent/received, http payload sent/received, url/post parameters, and the corresponding signature?

If you are building an iOS app, I strongly suggest using our Objective-C API binding (https://github.com/tripit/objective_c_binding_v1) for OAuth and making API calls.

Thanks.

Tariq
Developer Advocate | TripIt
