### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by igordossantos** [tripit/api#210]
All, 

I am a newbie to writing coding hitting API. I'm a database developer, mainly working with SQL in the Microsoft word. 

I need to grab data from TripIt to create reports for my team/organization and I'm having hard time figuring this out. I need to grab Trip, Flight, Hotel, Car and other data points to build reports. 

I have tried making API calls using curl and PoweShell but have not had any luck. 

I have also downloaded a Chrome plug-in to make the initial call but still no luck and I'm sure the issue is me and my lack of familiarity with the tool and API calls. 

Where am I stuck at: 

The API document (http://tripit.github.io/api/doc/v1/index.html) mentions: 

"To obtain a request token POST the following request parameters to the URL: https://api.tripit.com/oauth/request_token"

I'm doing a POST to http://tripit.github.io/api/doc/v1/index.html using the following parameters/values: 

oauth_consumer_key = 41 characters API Key string  from my App (extracted from https://www.tripit.com/developer) - Is this information sesitive?
oauth_nonce = Random text value, da39a3ee5e6b4b0d3255bfef95601890afd80709
oauth_signature = Do not know what to pass here
oauth_signature_method = HMAC-SHA1
oauth_timestamp = ${timestamp()}, resolved to 1518031851760
oauth_version = 1.0

POST Request: 
POST /oauth/request_token?oauth_consumer_key=123abc&oauth_nonce=da39a3ee5e6b4b0d3255bfef95601890afd80709&oauth_signature=&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1518031851760&oauth_version=1.0 HTTP/1.1
Content-Length: 0
Host: api.tripit.com

Response: 
<Response><Error><code>401</code><detailed_error_code>102.100000</detailed_error_code><description>consumer key not present in request</description></Error></Response>

Help me out here, what am I doing wrong and thanks in advance for your help!

**Comment by brianheineman** [comment]
Hello,

Thank you for using the TripIt API.

The `oauth_signature` is a required value that is calculated based on the request being made.  I would recommend using an OAuth1 library to handle calculating this value for you.  Alternatively, you can use one of the client APIs we provide.  For a detailed explanation of how the `oauth_signature` value is calculated and used see https://tools.ietf.org/html/rfc5849#section-3.4.  

Cheers,
-Brian

**Comment by igordossantos** [comment]
All, I received a couple replies, all by email and thanks for your responses. 

I'm now at a stage where I keep getting a "401 Unauthorized" error message.

How can I check if my account is authorized to connect?

Also, could you please let me know if I'm building the array of parameters correctly?




#Variable holding the URL value
$url = 'https://api.tripit.com/oauth/request_token'
echo $url

#Variables that calculate the number of seconds between 01/01/1970 00:00:00 and current UTC time.
#1518112243 is an example of a $timestamp passes to the code being invoked
$StartDate = Get-Date -Date '01/01/1970 00:00:00'
$CurrentDate = Get-Date
$EndDate = $CurrentDate.ToUniversalTime()
$TimeStamp = [math]::floor((New-TimeSpan -Start $StartDate -End $EndDate).TotalSeconds)
$TimeStamp

#This is a variable that I'm using to populate the oauth_nounce value
$nounce = 'qnR8UCqJggD55PohusaBNviGoOJ67HC6Btry4qXLVZc'

#These are my consumer and secrete keys. These are not real values. 
#$consumerkey = '123456789b9d94e1ebbf3739fb3e525123456789'
#$secretkey = '987654321f909d12c8b85f37f478b12987654321'

#This is the part where I hash the $consumerkey with the $secret value
$hmacsha1 = New-Object System.Security.Cryptography.HMACSHA1
$hmacsha1.key = [Text.Encoding]::UTF8.GetBytes($nounce)
$signature1 = $hmacsha1.ComputeHash([Text.Encoding]::UTF8.GetBytes($consumerkey))
$signature1 = [Convert]::ToBase64String($signature1)
echo $signature1 

#This is the part where I hash the $secretkey with the $secret value
$hmacsha2 = New-Object System.Security.Cryptography.HMACSHA1
$hmacsha2.key = [Text.Encoding]::UTF8.GetBytes($nounce)
$signature2 = $hmacsha2.ComputeHash([Text.Encoding]::UTF8.GetBytes($secretkey))
$signature2 = [Convert]::ToBase64String($signature2)
echo $signature2 

#Here's where I put it all together, building the $hdrs array of parameters
$hdrs = @{}
$hdrs.Add('Authorization','Bearer')
$hdrs.Add('oauth_consumer_key', $consumerkey)
$hdrs.Add('oauth_nonce', $nounce)
$hdrs.Add('oauth_signature', '')
$hdrs.Add('oauth_signature_method', 'HMAC-SHA1')
$hdrs.Add('oauth_timestamp', $TimeStamp)
$hdrs.Add('oauth_version', '1.0')
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Invoke-RestMethod -Uri $url -Method Post -ContentType 'application/json' -Headers $hdrs
Invoke-WebRequest -Uri $url -Method Post -ContentType 'application/json' -Headers $hdrs


Error Message:



Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At C:\TripIt\PowerShell\PostPS2.ps1:49 char:1
+ Invoke-RestMethod -Uri $url -Method Post -ContentType 'application/js ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
Invoke-WebRequest : 401102.100000consumer key not present in request
At C:\TripIt\PowerShell\PostPS2.ps1:51 char:1
+ Invoke-WebRequest -Uri $url -Method Post -ContentType 'application/js ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by brianheineman** [comment]
Looking at your example, it appears you are trying to send in individual header values instead of a single `Authorization` header:

```
Authorization: OAuth oauth_nonce="12345678901234567890123456789", oauth_timestamp="1518280715", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="5dbf348aa966c5f7f07e8ce2ba5e7a3badc234bc", oauth_signature="<calculated_signature>"
```

You may want to consider using one of our existing TripIt API clients, or a standard OAuth1 library to compare/verify the implementation you are working on is producing the expected output.

Cheers,
-Brian

**Comment by igordossantos** [comment]
It seems that I'm not creating my signature correctly. I'll continue looking into this. Any tips on how to correctly concatenate and encrypt the signature?

**Comment by brianheineman** [comment]
There are a lot of OAuth1 implementations in various languages.  Probably the easiest thing to do is find a working implementation in a language you are familiar with, and use it as a guide for your own implementation/verification.

Cheers,
-Brian
