### ISSUE TITLE
0 Response from API (token request)

### ISSUE THREAD

**Issue by byronics** [tripit/api#211]
Byron from Tripline here.  We've been using the Tripit API for years and recently, imports on our Production site started failing (no trips returned).  In our testing, we noticed that new Oauth Connection requests (submitted via Curl) are receiving 0 as a response when trying to hit https://api.tripit.com/oauth/request_token. Everything works correctly in both of our dev environments, running the same code as Production.

We haven't updated our Tripit connection code in more than a year.  Has something changed recently that could potentially cause this?

**Comment by brianheineman** [comment]
Hello Byron,

I verified that your consumer is still valid and works with a test client.   I am not aware of any changes that would impact one of your environments but not another.  Are you using the same consumer key/secret in your development environments as you are in production?  Do your development environments make requests to https://api.tripit.com/oauth/request_token ?  

Cheers,
-Brian

**Comment by byronics** [comment]
Hi Brian.  Yeah, we're Curling out to https://api.tripit.com/oauth/request_token 

It seems like the API is now requiring TLS 1_2.  Anything lower will fail.  Our instance that was making the connection was using a lower SSL version...when we updated to force TLS 1_2, the error went away.  I didn't see an announcement about the change and there's nothing in the docs about the requirement.  Is this a new thing?  We didn't start seeing errors until recently.

**Comment by brianheineman** [comment]
We updated our website to inform users that TLS 1.2 is required (https://github.com/tripit/api/issues/191#issuecomment-299257493).  I am glad to hear your integration to our API is working again.

Cheers,
-Brian
