### ISSUE TITLE
Is it possible to get trips for TripIT groups using the web API?

### ISSUE THREAD

**Issue by Subaipca** [tripit/api#213]
Hi there,
I have a TripIT account and I am a member of TripIT organisation group. Can I get the trips for the groups by making a web api call using my account credentials?
Thanks.

**Comment by dave-symons** [comment]
Hi @Subaipca!

Unfortunately our API doesn’t contain support for this feature at this time and our engineering team is currently occupied with infrastructure work that will likely preclude our ability to address this issue for some time. It is a request we’ve heard echoed by other customers though and will certainly take your interest under consideration when we prioritize future features.
