### ISSUE TITLE
how to populate layover and connects to information using API?

### ISSUE THREAD

**Issue by anupshesh** [tripit/api#214]
![tripit](https://user-images.githubusercontent.com/38142549/38440463-83483270-39af-11e8-8a99-5b3fbb5f83ce.png)
You may check the flight reservation using the given confirmation number. 

We are not able to find a way to populate the layover and connects to information using the API. 

Please suggest a solution. Thank you!

**Comment by k-wiz** [comment]
Hi! 
I was able to reproduce this effect; for `Layover` and `Connects To` to be populated, flight segments must be posted as part of the same AirObject in the xml or json document. See the sample create request for an AirObject here -- http://tripit.github.io/api/doc/v1/#request_response_section. 

If segments are posted in separate requests or as part of separate AirObjects, they're not considered part of the same reservation or same flight leg. 

Hope that helps!

**Comment by sharma-hitesh** [comment]
Okay, still not able to make it work.
I even used the same object that the that is used in the sample create request you shared. I just changed the year 2009 to 2019

Here is how it looks:
<img width="902" alt="screen shot 2018-04-18 at 7 23 11 pm" src="https://user-images.githubusercontent.com/4112432/38936394-4a146d14-433e-11e8-9bb5-969f62c0f213.png">

**Comment by anupshesh** [comment]
Okay, still not able to make it work.
I even used the same object that the that is used in the sample create request you shared. I just changed the year 2009 to 2019

Here is how it looks:
<img width="902" alt="tripit" src="https://user-images.githubusercontent.com/38142549/39210514-f15cdeb6-47d6-11e8-85df-f4e5735c5d89.png">

**Comment by sharma-hitesh** [comment]
This works as expected if
All the hops are posted as separate segments (no special fields for hops) AND the time gap between arrival and departure is relatively small
