### ISSUE TITLE
Python getting started with Tokens

### ISSUE THREAD

**Issue by khargy** [tripit/api#215]
I'm using the Python API and I'm trying to make sense of all the tokens...

I started with the "get_request_token.py" and I used the API Key and API Secret... that gave me two tokens called: oauth_token_secret and oauth_token...

I tried using them in get_authorized_token.py and I get either:
"attempted to fetch an access token with an unauthorized request token"
"unable to find authorized request token with key [key]"

Using them directly in example.py didn't work either...

I figure I'm missing a step somewhere...

Thanks,
Ken

**Comment by rrranthony** [comment]
Hi Ken,

Apologies for the slow response! It sounds like the first request you made was something like this:

```
$ python get_request_token.py https://api.tripit.com CONSUMER_KEY CONSUMER_SECRET

{'oauth_token_secret': 'abcd', 'oauth_token': '1234'}  # using fake values here
```

Next, it seems like you attempted the following:

```
$ python get_authorized_token.py https://api.tripit.com CONSUMER_KEY CONSUMER_SECRET OAUTH_TOKEN OAUTH_TOKEN_SECRET

<Response>
  <Error>
    <code>401</code>
    <detailed_error_code>106.300000</detailed_error_code>
    <description>attempted to fetch an access token with an unauthorized request token</description>
  </Error>
</Response>

# Or, if more than 5 minutes elapsed since making the get_request_token request, you would likely see
<Response>
  <Error>
    <code>401</code>
    <detailed_error_code>106.200000</detailed_error_code>
    <description>unable to find authorized request token with key KEY</description>
  </Error>
</Response>
```

If that all sounds accurate, then it looks like the step you're missing is having the user authorize the request token (the `oauth_token` returned by `get_request_token.py`), which will then allow you to get the authorized (access) token (via `get_authorized_token.py`).

As noted in [Step 2 in our API docs](http://tripit.github.io/api/doc/v1/index.html), to have the user authorize the request token, the user should be redirected to the following URL (replacing `1234` and `https://www.your-website.com/` appropriately):

```
https://www.tripit.com/oauth/authorize?oauth_token=1234&oauth_callback_url=https://www.your-website.com/ 
```

Hope this helps. Happy to provide more details if needed!

Regards,
Anthony

**Comment by rrranthony** [comment]
Hi Ken,

Were you able to figure out token authorization and subsequently retrieve an access token? Please let us know if you need any help.

Regards,
Anthony

**Comment by khargy** [comment]
No, but thanks for your help...really oauth is way overkill for what I needed... I just wanted to display my trip info on an LED sign I made. 

Instead of spending too much time on it, I just decided to consume my Calendar Feed using the ICS python library (https://pypi.org/project/ics/).

Thanks,
Ken

**Comment by rrranthony** [comment]
Sounds like a cool project! Please reach out again if you end up needing to use the API in the future!

Regards,
Anthony
