### ISSUE TITLE
Adding a logo image to Note or any other TripIt objectj (?)

### ISSUE THREAD

**Issue by doogie99** [tripit/api#216]
Is it possible to add an image (i.e. a logo) to Note content or any other TripIt objects? In lieu of that, is there any way to subbrand TripIt programmatically?

Thanks,

Doug

**Comment by doogie99** [comment]
Also, is there any way to add any formatting? Boldface, italics, underline, font size, etc?

**Comment by hliss** [comment]
Hi, apologies for the delay here. You're able to add an image to any object! See the `Image` property of the `Object` here: https://api.tripit.com/xsd/tripit-api-obj-v1.xsd.

Any formatting other than newlines is not supported. Thanks!
