### ISSUE TITLE
iOS: where to put TripIt key & secret

### ISSUE THREAD

**Issue by garyhooper** [tripit/api#217]
I'm looking for recommendations as to how to enable access to my TripIt key and secret for my iOS app. Obviously storing them in the app directly is not very secure.

What are common practices?

**Comment by gazure** [comment]
Apologies for the delayed response!

As nothing on the device is ever really secure, we recommend storing API keys and secrets on a remote server that your mobile app can authenticate and retrieve the secure information from. This way the API keys and secrets are not included in your app's binary and if a secret does get compromised by an attacker, it can be easily rotated via the tripit developer portal and deployed to your remote server to roll out the new secret to your mobile installations without issuing a new mobile release.

Obviously this incurs some additional operational costs and concerns, but this is one strategy you can utilize to be more secure with your 3rd party secrets.

Hope this helps!

-Grant

**Comment by nmr8acme** [comment]
@gazure Does the API support "Bearer token" authorization via the OAuth token returned by the sign-in flow? We'd like to be able to make API calls directly from the mobile app.

**Comment by hliss** [comment]
@nmr8acme The TripIt API doesn't support Bearer token (OAuth 2) authentication just quite yet. The authentication method is OAuth 1.0a. Assuming the "sign-in flow" you reference is the authorization flow described at http://tripit.github.io/api/doc/v1/index.html#oauth, you may make direct API requests as described in `Step 4: Accessing Protected Resources` in that section. The older protocol is a bit more complex, but I'd expect your programming language of choice to have a readily available library to make OAuth 1 more accessible while it's still in use. Thanks!

**Comment by nmr8acme** [comment]
Thanks and sorry for the necro. I wanted to avoid embedding the client key in the app. Didn't realize bearer tokens were an OAuth 2 thing, sorry. I'll stand up an API proxy to hold the client key.

**Comment by hliss** [comment]
Worry not!
