### ISSUE TITLE
Requesting Consumer Key and Secret

### ISSUE THREAD

**Issue by LidoDarren** [tripit/api#218]
Hi

We are an accommodation aggregator who manage hotel programs for corporate clients and have a customer who've requested we push itinerary (hotel stay) data through to their member's TripIT accounts. We've been working through your API specs and at the point of requiring a Consumer Key and Secret. 

Can you please get in contact me via email darrenl@lido.com.au to assist with the above query?

Regards,
Darren

**Comment by rrranthony** [comment]
Hi Darren,

Happy to hear that you're planning to use our API! The consumer key and secret are obtained through a self-service process. That is, to obtain a consumer key and secret we require you to have a TripIt account. Once you are signed in, you can navigate to https://www.tripit.com/developer and then click "Register an app". It sounds like "Full API Application" would be appropriate for your use case. Once you fill out the application registration form, you will be issued a consumer key and secret.

Please don't hesitate to reach out for assistance on the above steps or any of the token request and authorization steps!

Regards,
Anthony

**Comment by LidoDarren** [comment]
Hi Anthony,

I’ve done this and have received the Consumer Key and Secret now.

Thanks for your assistance. No doubt I’ll be in touch again if we require anything further.


Kind regards,

Darren Lee

Business Analyst – Client Implementations
The Lido Group - Global Hotel Booking and Payment Solutions
P: +61 2 8585 0833 | F: +61 2 8585 0801|E: darrenl@lido.com.au<mailto:darrenl@lido.com.au> |W: www.lido.com.au<http://www.lido.com.au/>
[HRS_und_LIDO]     [cid:image006.jpg@01D3DCCD.68388FA0]        [cid:image002.jpg@01D3315A.233722F0]

Now here’s the Disclaimer bit… If you got this email and it wasn’t meant for you, let the sender know of their mistake, then delete the info from your memory and your mailbox. Any dodgy ‘opinions’ of the writer expressed within this email don’t necessarily represent those of The Lido Group, neither do the contents form some sort of binding contract.  (Our contracts are made by the Directors and can be spotted because they look like contracts…with signatures and legal stuff).  This email and its content come with a guarantee…that the information contained here may not be error-free; use and forwarding of, or reliance on this information is at your own risk.

**Comment by rrranthony** [comment]
Great! Sounds good!

Regards,
Anthony
