### ISSUE TITLE
Where are all the "other" fields for Activites in the Add to TripIt button?

### ISSUE THREAD

**Issue by sbm12** [tripit/api#22]
I'm trying to implement the AddToTripIt button on my site to integrate activities booked online directly into users' TripIt accounts. I found the sample code (http://tripit.github.com/api/doc/v1/plugins.html#js_api_section) and I can set a date and address for an activity. But I cannot set things like the activity description, supplier details or other, critical fields. It seems that the data structure is defined in the XSD but I cannot find any samples on how to include the data in my code. 

Any additional documentation, samples or guidance would be much appreciated!

**Comment by tariqislam** [comment]
Hi,

I'm very glad to hear that you are trying out our new feature! At the moment, the JavaScript SDK used in the AddToTripIt button only supports a subset of the fields in the XSD, and are described in the API methods (http://tripit.github.com/api/doc/v1/plugins.html#js_api_section). 

Please let me know if you have any other questions.

Tariq Islam
Developer Advocate | TripIt

**Comment by tariqislam** [comment]
Clarification to the documentation:

Four fields were added to the JavaScript SDK, and the documentation has been updated. The new fields are supplierConfirmationNumber, supplierName, bookingSiteConfirmationNumber, and bookingSiteName, and they are available for the Activity, Lodging, Restaurant, and Transport objects.

**Comment by sbm12** [comment]
Where in the documentation have the additional fields been noted? The page at http://tripit.github.com/api/doc/v1/plugins.html#js_api_section still does not mention those additional fields. 

I also hope that at least "description" and "location name" get considered to be included in the very near future; lacking those makes it rather hard to get value from this interface.

**Comment by tariqislam** [comment]
In the JavaScript API section (http://tripit.github.com/api/doc/v1/plugins.html#js_api_section) if you click on each of the travel objects on the left hand side of the table, on the right you will be able to see the methods that are exposed for that object. The new fields that I mentioned should have corresponding getters/setters for them.

As for description and location name, for which travel object are you referring to?

Thanks.

Tariq

Developer Advocate | TripIt

**Comment by sbm12** [comment]
I see the additional documentation there now; thanks.

I am still trying to create an activity event. The supplier name is a rough substitute for description but not quite as good. Such is life.

**Comment by tariqislam** [comment]
I'm interested to know what fields may be useful for your integration. Could you let me know what field, and in what travel object, you may need?

Thanks.

Tariq
Developer Advocate | TripIt

**Comment by sbm12** [comment]
I am only (currently) interested in the Activity objects. For my specific needs today I believe that only "Description" is still missing as a critical field. I could see "Activity Type" being useful but not for my current project as the options there are limited and mine doesn't fit any of them.

The updated documentation suggests that location is now a possible option to include so that one no longer is an issue to me. That said, I haven't tested it yet.

Being able to specify the phone number or URL as the supplier rather than just a name and booking rate would also make it easier to have customers contact me in case of issues along the way so I'd consider those a secondary level of importance versus the others above.

**Comment by tariqislam** [comment]
Thank you for your prompt feedback. We will definitely take this to
consideration, and I'll keep you updated.

Tariq Islam
TripIt  |  Developer Advocate

**Comment by sbm12** [comment]
Likewise, thanks for the quick responses. I would also prioritize the ability to have multiple buttons on a page over most other bits, if you're taking requests. :)

**Comment by tariqislam** [comment]
Hi smb12,

Could you let me know what website you're adding the A2T button? You can send an email to me directly at tariq@tripit.com if you'd like.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi smb12,

I'm pleased to let you know that we have made additions to the Add-to-TripIt plugin:
- For the Activity object, you can add displayName and notes.
- A new Car object can be used for car rental reservations.
- Multiple plugin buttons can be rendered on the same page.

For more details, please visit our documentation page: http://tripit.github.com/api/doc/v1/plugins.html

Thanks.

Tariq
