### ISSUE TITLE
How to access the Android application

### ISSUE THREAD

**Issue by lmjssjj** [tripit/api#222]
What does my android app need to do to access it

**Comment by gazure** [comment]
If you're looking for information on how to use the API, please refer to our documentation at http://tripit.github.io/api/

If you're looking for tips on how to securely store secrets on the android application, we recommend storing API keys and secrets on a remote server that your mobile app can authenticate and retrieve the secure information from. This way the API keys and secrets are not included in your app's binary and if a secret does get compromised by an attacker, it can be easily rotated via the tripit developer portal and deployed to your remote server to roll out the new secret to your mobile installations without issuing a new mobile release. This incurs some additional operational costs and concerns, but this is one strategy you can utilize to be more secure with your 3rd party secrets.

Hope this helps!

-Grant
