### ISSUE TITLE
Unable to obtain user authorization

### ISSUE THREAD

**Issue by mcarbaugh** [tripit/api#223]
I have successfully generated a token (Oauth Step 1) using the consumer key/secret but I am having trouble redirecting to:

[https://www.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>]

As far as I can tell, I've followed the documentation exactly. Is there an additional step I have to take to make the redirect link work?

Thanks in advance.

This is the message I see in the window:
![image](https://user-images.githubusercontent.com/17512350/45446244-0038c100-b692-11e8-9ef3-9bfe0d0caf7a.png)

**Comment by mcarbaugh** [comment]
Issue appears to be returning a 102.6 error code.

**Comment by gazure** [comment]
102.6 means we couldn't find the request token at authorization time, the most common cause would be attempting to authorize the request token more than 5 minutes after requesting it (request tokens are only valid for 5 minutes).

If you're getting this error and you know that the request token and secret is less than 5 minutes old, feel free to email us at api-support@tripit.com with your specific account info (oauth consumer name, account email, request tokens, etc.) and we might able to dig through logs for your situation.

**Comment by mcarbaugh** [comment]
@gazure  thank you for the response.

The original issue I ran into was unrelated to the 102.6 error code. I simply forgot to include an appropriate protocol in the oauth callback url. I thought the issue was oauth related. All fixed!

**Comment by gazure** [comment]
Glad you got it fixed!
