### ISSUE TITLE
How to connect to excel adds in? 

### ISSUE THREAD

**Issue by radit28** [tripit/api#228]
Is there any way step by steps to connect trip it to excel? Since currently TRIP it unable to export data to excel eventhough it is trip it for team. 

Open flight is great having facilities to export it to excel but they don't capture Passengers name and booking code, which important if it will be use for company wide.

**Comment by lundbrianh** [comment]
hi @radit28,
Sorry, we do not currently have any examples for doing that.  If you design a pattern that works well, i'm sure the community would be thankful if you gave even a cursory description here!

The one thing I will point out is that our API supports XML and JSON response formats using the `format` request parameter (e.g. https://api.tripit.com/v1/list/trip?format=json`).  Valid values for that are `json` and `xml`.  `xml` is the default, so omitting it returns XML.

Thanks for reaching out, and please let don't hesitate to ask if you run into issues connecting to the API.
