### ISSUE TITLE
Multiple AddToTripIt buttons on the same page?

### ISSUE THREAD

**Issue by sbm12** [tripit/api#23]
Is it possible to have multiple AddToTripIt buttons on the same page, each with different parameters? The API documentation seems to suggest that there can be only one but I'm hoping that is an oversight or just a simplified version.

**Comment by tariqislam** [comment]
At this point, only one button per page is supported. We will work on supporting multiple buttons per page.

Thanks.

Tariq 
Developer Advocate | TripIt
