### ISSUE TITLE
Filter="traveler",  value="all" not working properly

### ISSUE THREAD

**Issue by timroesner** [tripit/api#231]
I am making a request to the api using the following url: "https://api.tripit.com/v1/list/object/type/air/traveler/all/format/json" as you can see I want to query all flights no matter if the user is a traveler or not. However with this request I only get trips that the user is NOT a traveler on.

**Comment by timroesner** [comment]
Getting all trips from the api now. Not sure what caused the glitch, but it must have been on your end. Leaving this open so you can investigate.

**Comment by hliss** [comment]
Hi @timroesner, I think I know what you were briefly experiencing, and it was indeed fixed quickly as you noticed. Apologies that you saw such responses! Thanks for posting the heads up so we know the impacts. Cheers!
