### ISSUE TITLE
Comprehensive Schema

### ISSUE THREAD

**Issue by stillinbeta** [tripit/api#232]
One thing the API documentation is lacking is a comprehensive list of what objects have what fields. I would like to see what all possible members of every object type is, and whether those fields are mandatory or optional.

The ideal would be a machine-consumable format [like swagger](https://swagger.io/), but even an HTML table would be a huge improvement

**Comment by d-w-wilson-jr** [comment]
This is a great idea and will be forwarded on as a recommendation.

**Comment by dave-symons** [comment]
Closing as this is not a bug.
