### ISSUE TITLE
Requesting token always gives invalid signatures error

### ISSUE THREAD

**Issue by WaseemDevicebee** [tripit/api#239]
I am struggling with API integration. Stuck in first step when Requesting token. Below  is my request example please help me to get it working.
for oauth_consumer_key i am providing API Key from created app on TripIt, and generating signature with Secret key.

**Signature Base String**
POST&https%3A%2F%2Fapi.tripit.com%2Foauth%2Frequest_token%26oauth_consumer_key%3D9a01baa98575fe0f4072295fcf275d7117606411%26oauth_nonce%3D1568187437djkl%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1568187437%26oauth_version%3D1.0
**base64-encoded Signature string**
bHtHqXnl8ov0ftQKgvtpyQLLwhY=

**Request**
requestURL: 'https://api.tripit.com/oauth/request_token'
paramDict: '["oauth_signature": "bHtHqXnl8ov0ftQKgvtpyQLLwhY%3D", "oauth_timestamp": "1568187437", "oauth_signature_method": "HMAC-SHA1", "oauth_consumer_key": "9a01baa98575fe0f4072295fcf275d7117606411", "oauth_nonce": "1568187437djkl", "oauth_version": 1.0]'

**Response**
responseData= <Response><Error><code>401</code><detailed_error_code>104.100000</detailed_error_code><description>invalid signature</description></Error></Response>

**Comment by hliss** [comment]
Hi @WaseemDevicebee,

I think you may be URL encoding part of the base string rather than the parameters. The base string you pasted starts with:
`POST&https%3A%2F%2Fapi.tripit.com%2Foauth%2Frequest_token%26oauth_consumer_key`...
but should look like:
`POST&https%3A%2F%2Fapi.tripit.com%2Foauth%2Frequest_token%oauth_consumer_key`...

Hope this helps get through this authentication step!

**Comment by WaseemDevicebee** [comment]
Thanks @hliss for replying.
I tried with above correction still same result. Below is my updated request details. Any further help would be appreciated.

**Signature Base String**
POST&https%3A%2F%2Fapi.tripit.com%2Foauth%2Frequest_token&oauth_consumer_key%3D9a01baa98575fe0f4072295fcf275d7117606411%26oauth_nonce%3Dfd1568293947cd3%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1568293947%26oauth_version%3D1.0

**base64-encoded Signature string**
krIvuAZ2u28QxfuPI/XR1ve8ujI=

**Request**
requestURL: 'https://api.tripit.com/oauth/request_token'
paramDict: '["oauth_version": 1.0, "oauth_timestamp": "1568293947", "oauth_signature": "krIvuAZ2u28QxfuPI%2FXR1ve8ujI%3D", "oauth_nonce": "fd1568293947cd3", "oauth_signature_method": "HMAC-SHA1", "oauth_consumer_key": "9a01baa98575fe0f4072295fcf275d7117606411"]'

**Response**
responseData= <Response><Error><code>401</code><detailed_error_code>104.100000</detailed_error_code><description>invalid signature</description></Error></Response>

**Comment by hliss** [comment]
Hi, are you still experiencing this error? The base string looks correct. To continue troubleshooting such request failures, feel free to contact api-support@tripit.com with any extra details you may not want to share in a public forum.

**Comment by hliss** [comment]
Request has been resolved!
