### ISSUE TITLE
How to differentiate Held and Purchased trip

### ISSUE THREAD

**Issue by Jincyv** [tripit/api#24]
Hi,

We are adding only purchased/ticketed trip to tripit now.We also need to add held trip to tripit.
Are you using any criteria for differentiating purchased/ticketed or held trip or simply displaying all trip  whether it is held or purchased.

This is the format we are using  for sending request to tripit in the case of purchased/ticketed  itineraries.
&lt;CrsRequest&gt;
&lt;AirObject&gt;
&lt;Image&gt;
&lt;url&gt;http://www.orbitzforbusiness.net/site/img/chrome/nav/ofbLogoSmall.gif&lt;/url&gt;
&lt;/Image&gt;
&lt;booking_date&gt;2012-11-18&lt;/booking_date&gt;
&lt;booking_site_conf_num&gt;&lt;/booking_site_conf_num&gt;
&lt;booking_site_name&gt;OrbitzforBusiness&lt;/booking_site_name&gt;
&lt;booking_site_phone&gt;112345&lt;/booking_site_phone&gt;
&lt;booking_site_url&gt;&lt;/booking_site_url&gt;
&lt;record_locator&gt;ABC&lt;/record_locator&gt;
&lt;supplier_conf_num&gt;ASDRT&lt;/supplier_conf_num&gt;
&lt;total_cost&gt;90.01&lt;/total_cost&gt;
&lt;Segment&gt;
&lt;StartDateTime&gt;
&lt;date&gt;2013-07-02</date&gt;
&lt;time&gt;14:31:00</time&gt;
&lt;/StartDateTime&gt;
&lt;EndDateTime&gt;
&lt;date&gt;2013-07-02&lt;/date&gt;&lt;time&gt;15:39:00&lt;/time&gt;
&lt;/EndDateTime&gt;
&lt;start_airport_code&gt;LAS&lt;/start_airport_code&gt;
&lt;end_airport_code&gt;LAX&lt;/end_airport_code&gt;
&lt;marketing_airline&gt;AS&lt;/marketing_airline&gt;
&lt;marketing_flight_number&gt;123&lt;/marketing_flight_number&gt;
&lt;seats&gt;6C&lt;/seats&gt;
&lt;service_class&gt;Coach&lt;/service_class&gt;
&lt;/Segment&gt;
&lt;Traveler&gt;&lt;first_name&gt;&lt;/first_name&gt;
&lt;last_name&gt;&lt;/last_name&gt;&lt;/Traveler&gt;
&lt;/AirObject&gt;
&lt;/CrsRequest&gt;

If Tripit differentiating purchased or held trip,can we use &lt;is_Purchased&gt;true or false &lt;/is_Purchased&gt; element for this.
- What is the purpose of this tag &lt;is_Purchased&gt; element in the Air Object.
- Can the value ‘false’ be sent if the trip is on hold and ‘true’ be sent if a trip is ticketed/purchased? 
- If the Is_Purchased element is used for something else, is there some other way to accomplish distinguishing a held trip from a ticketed/purchased trip?
-  Would you have an example of how this element looks in TripIt?

Please help us to proceed further

**Comment by tariqislam** [comment]
Hi,

The "is_purchased" field is really up to you to determine how you'd like to use it, i.e. you may use it to differentiate between purchased/held. Usually what we have seen is that a "is_purchased"=false is usually sent with a CancellationDateTime field (indicating when this held reservation will be cancelled if not purchased), and when the user purchases the ticket, the "is_purchased" is set to true and CancellationDateTime set to null.

I don't have an example of how the element looks like, but I encourage you to create test objects, set "is_purchased" to true and see how it behaves in the UI.

Thanks.

Tariq
TripIt | Developer Advocate
