### ISSUE TITLE
Support for Numerical IATA Codes

### ISSUE THREAD

**Issue by azampagl** [tripit/api#242]
Currently the validation for IATA codes forces alpha characters.

Exception Message: TripItRequest failed. XML did not validate with the xsd: Element 'end_airport_code': [facet 'pattern'] The value 'M17' is not accepted by the pattern '[A-Z][A-Z][A-Z]'.

Please add support for numerical values for airports such as https://www.airnav.com/airport/M17

**Comment by hliss** [comment]
Hi @azampagl, it appears that codes like the the `M17` example are FAA codes, not IATA. Some FAA codes conflict with IATA codes. As an example, Phoenix-Mesa Gateway Airport has IATA code `AZA`, but FAA code `IWA`. IATA code `IWA` is assigned to Ivanovo Yuzhny Airport in Russia. TripIt sticks to IATA codes as the source of truth, and doesn't currently include data for general aviation only airports (such as M17) which do not have IATA codes. Hopefully that helps clarify the behavior.
