### ISSUE TITLE
Requesting OAUTH for application

### ISSUE THREAD

**Issue by JaktensTid** [tripit/api#248]
Hi, I need OAUTH token for application 
02fa41d3-7db1-4254-8f35-9ba35ae00de8
Please respond to my email - jaktenstid1@gmail.com

Thanks!

**Comment by hliss** [comment]
Hiya, you're able to find the oauth consumer key and secret for your app in the developer portal located at https://www.tripit.com/developer. There is currenlty no intermediate step to enable your OAuth consumer; you're able to use it immediately. To authorize a token for a user, please follow these steps! http://tripit.github.io/api/doc/v1/index.html#oauth
