### ISSUE TITLE
Basic Authentication Fails

### ISSUE THREAD

**Issue by jumphrey77** [tripit/api#25]
Hi,

I created a TripIt account and had the support team enable basic authentication.

I tried the following using the following and I keep getting a 401 error

```
Dim wa As New WebAuthCredential(consumerKey, consumerSecret)

Dim t As TripIt.TripIt = New TripIt.TripIt(wa)

Label1.Text = t.ListTrip().Trip.Length
```

For the consumerKey and consumerSecret I am using my email address and password.

I am also trying with OAuth as follows:

```
Dim cred As New OAuthCredential(consumerKey, consumerSecret, authorizedToken, authorizedTokenSecret)

Dim t As TripIt.TripIt = New TripIt.TripIt(cred)
```

What am I missing?

**Comment by tariqislam** [comment]
Hi,

Did you try the curl example using basic authentication (
http://tripit.github.com/api/doc/v1/index.html#authentication_section) to
check whether your basic authentication works?

You cannot use your email address and password for consumerKey and
consumerSecret when using OAuth, as it is an invalid OAuth cred. What
language are you using, and are you using one of our provided API bindings
for the language?

It would also be useful to list the following for debugging purposes:
- complete url + params
- request & response headers, content

Thanks.

## Tariq Islam

TripIt  |  Developer Advocate

**Comment by jumphrey77** [comment]
I am coding in vb.net and I am using a reference to the tripit_csharp_v1_43360\TripIt.dll

I was just about to post a comment about curl.  I am on a windows machine and downloaded the windows version of curl (not familiar with the utility).  

It does not work.  I type:

```
c:\curl>curl -k -D /dev/tty --user juxxxxx@xxxxx.net:xxxxxxx --url https://api.tripit.com/v1/list/trip
```

and i get back

```
Warning: Failed to open /dev/tty
```

I take out the /dev/tty as follows

```
c:\curl>curl -k -D --user juxxxxx@xxxxx.net:xxxxxxx --url https://api.tripit.com/v1/list/trip
```

and i get

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.comcast.net/">here</a>.</p>
</body></html>
curl: (6) Could not resolve host: https; Host not found
```

**Comment by jumphrey77** [comment]
I used another tool for curl:  Gave me more error info:

With the /dev/tty I still get:

```
Warning: Failed to open /dev/console
```

I tried this:

```
$ curl -k -D --user juxxxxx@xxxxx.net:xxxxxxx https://api.tripit.com/v1/list/trip
```

Got this:

```
<Response><Error>
  <code>401</code>
  <detailed_error_code>102.1</detailed_error_code>
  <description>consumer key not present in request</description>
</Error></Response>
```

**Comment by jumphrey77** [comment]
I got curl to work:

```
$ curl -k -D c:\curl --user juxxxxx@xxxxx.net:xxxxxxx https://api.tripit.com/v1/list/trip
```

I seems that a path of /dev/ttl didn't work so i put in a valid path of c:\curl and it worked.

However, my Application is still not working.

**Comment by tariqislam** [comment]
Glad you got it to work. /dev/tty is a Unix file path that actually
represents the current console (
http://stackoverflow.com/questions/8514735/what-is-special-about-dev-tty),
and this path is not present in Windows. You could probably run the above
code without the -D option, as in:

$ curl -k --user juxxxxx@xxxxx.net:xxxxxxx https://api.tripit.com/v1/list/trip

## Tariq Islam

TripIt  |  Developer Advocate  |  1-415-401-1143  |  tariq@tripit.com

**Comment by jumphrey77** [comment]
My original issue is still not resolved.  I am still getting error at this location in the Tripit.dll.

```
  at System.Net.HttpWebRequest.GetResponse()
  at TripIt.TripIt.DoRawRequest(String verb, String entity, Dictionary`2 urlArgs, Dictionary`2 postArgs) in C:\xxxxx\Desktop\TripIt\tripit_csharp_v1_43360\src\TripIt.cs:line 491
  at TripIt.TripIt.DoRequest(String verb, String entity, Dictionary`2 urlArgs, Dictionary`2 postArgs) in C:\xxxxx\Desktop\TripIt\tripit_csharp_v1_43360\src\TripIt.cs:line 407
  at TripIt.TripIt.ListTrip(Dictionary`2 filter) in C:\xxxxxx\Desktop\TripIt\tripit_csharp_v1_43360\src\TripIt.cs:line 334
  at TripIt.TripIt.ListTrip() in C:\xxxxxxxx\Desktop\TripIt\tripit_csharp_v1_43360\src\TripIt.cs:line 330
  at TripIt30.Form1.Button1_Click(Object sender, EventArgs e) in C:\xxxxxx\documents\visual studio 2010\Projects\TripIt30\TripIt30\Form1.vb:line 47
```

In looking at the System.Net.WebException.Status it is giving me a ProtocolError {7}

**Comment by jumphrey77** [comment]
After many hours of debugging, I think I solved the problem.  Using Fiddler I determined the the Authentication Header was not being sent when using Basic Authentication and thus the constant 401 error.

I had to modify the WebAuthCredentials.cs file as follows.  Maybe I am using teh api incorrectly but this is what I needed to do:

```
public void Authorize(
        WebRequest request,
        string realm,
        string urlBase,
        Dictionary<string, string> args)
    {
        request.PreAuthenticate = true;
        request.Credentials = new NetworkCredential(_username, _password);

        //FIX 11-29-2012
        string authValue = string.Format("{0}:{1}", _username, _password);
        byte[] authBytes = Encoding.UTF8.GetBytes(authValue.ToCharArray());
        request.Headers.Add("Authorization", "Basic " + Convert.ToBase64String(authBytes));

    }
```

One other change that I made comes from the example.cs project.  It is using the ServicePointManager.CertificatePolicy class which is deprecated.  The recommended class is the ServicePointManager.ServerCertificateValidationCallback.  I am using vb.net and to keep it simple I coded as follows:

```
Function CheckCert(obj As [Object], certificate As X509Certificate, chain As X509Chain, errors As SslPolicyErrors)
    Return certificate.Subject.Contains("CN=*.tripit.com")  // or Return true
End Function

ServicePointManager.ServerCertificateValidationCallback = AddressOf CheckCert
```

Hopefully this will help others.  Please let me know if I am using the C# .net API wrong.

Thanks

**Comment by tariqislam** [comment]
Hi,

It seems that the issue is related to http://stackoverflow.com/questions/7091203/c-sharp-network-credentials-not-being-passed-to-server

We will update our binding to include the Authentication header manually, rather than relying on NetworkCredential to do it. Thanks for the debugging!

Tariq
