### ISSUE TITLE
Previously working client now gets 401 error, Invalid Signature

### ISSUE THREAD

**Issue by kgutwin** [tripit/api#250]
I've had a TripIt API client working well for nearly a year now... today, some time after 18:00 UTC, I started receiving the following error:

    <Response><Error><code>401</code><detailed_error_code>104.100000</detailed_error_code><description>Invalid Signature</description></Error></Response>

I have been using the Python library from https://github.com/tripit/python_binding_v1. Has there been any change from the API end, or do I need to rotate my token?

**Comment by hliss** [comment]
Hiya @kgutwin, can you reproduce this error now? The team is constantly deploying, and thanks for bringing this case up.

**Comment by kgutwin** [comment]
Tested just now and the error is resolved. Thanks for the quick response!
