### ISSUE TITLE
login with Facebook/Google when getting oauth code

### ISSUE THREAD

**Issue by fracet** [tripit/api#251]
Hi
we use the Tripit API on [GigsGuide](https://gigs.guide) to let users sync their trips and get concert recommendations.

We have a couple of small issues with obtaining the first consent from the user:

1. Calling "https://www.tripit.com/oauth/authorize?oauth_token=XXXX" opens by default the "Sign up" dialogue box, rather than the "sign in" (to an existing account) which would make more sense. We even tried changing the URL to "https://www.tripit.com/oauth/signIn?oauth_token=XXXX" but it still opens Sign up by default.
2. When logging to the regular Tripit website, users also have the option to login with Facebook/Google. This is, however, not available in the oauth login form. We have a couple of users that are unable to login because their tripit account is linked to their FB account.

Any suggestions on how we can fix these issues?

Thanks
BR
Francesco

**Comment by hliss** [comment]
Hi @fracet,

Super cool idea; love seeing when integrations like these show up!

1. Yeah, default has to be something! We've seen this question before and did evaluate our traffic patterns to decide what the default should be. See https://github.com/tripit/api/issues/197#issuecomment-415940773. But in there is a workaround! Same disclaimer applies -- can't guarantee it'll always work, but you should be able to achieve your desired flow that way.
2. Definitely on the road map, but probably not coming very soon. Advice to your users would be to set a password (probably needs to be via https://www.tripit.com/account/forgotPassword) to use to login when linking, or to log into TripIt first via Facebook/etc in their browser before initiating consent in your app.

Hope this helps you! Cheers.

**Comment by fracet** [comment]
hi @hliss 
thanks... you can tell I have spent many lonely nights at hotel bars on my business trips ;) Hopefully we can get more Tripit users to sign up to our service (or maybe Tripit could integrate us directly? :D)

The islogin=1 trick worked... Hopefully, the social logins will work soon too.

Thanks
BR
Francesco
