### ISSUE TITLE
Error getting while adding <is_purchased> element

### ISSUE THREAD

**Issue by Jincyv** [tripit/api#26]
Hi,
We  posted  our  queries in https://github.com/tripit/api/issues/24. Thank you for your response.
So as per your suggestion we are trying to use &lt;is_Purchased&gt;true or false &lt;/is_Purchased&gt; at the end of &lt;Traveler&gt;&lt;/Traveler&gt; element.But we are getting respnse from tripit as 
 HTTP status = 400
&lt;Response&gt;
&lt;Error&gt;
&lt;code&gt;400&lt;/code&gt;
&lt;description&gt;XML did not validate with the xsd: Element 'is_purchased': This element is not expected. Expected is ( Traveler ).&lt;/description&gt;

Please help us to proceed further.
Thanking You.

**Comment by tariqislam** [comment]
Hi,

Can you post the entire xml object you are sending?

Thanks.

Tariq

**Comment by Jincyv** [comment]
Hi ,
This is our request format,we added is_purchased  at the end of &lt;supplier_conf_num/&gt; then we are able to add trip successfully to tripit.

&lt;CrsRequest&gt;<br>
&lt;AirObject&gt;<br>
&lt;Image&gt;<br>
&lt;url&gt;<a href="http://www.orbitzforbusiness.net/site/img/chrome/nav/ofbLogoSmall.gif&amp;lt;/url">http://www.orbitzforbusiness.net/site/img/chrome/nav/ofbLogoSmall.gif&amp;lt;/url</a>&gt;<br>
&lt;/Image&gt;<br>
&lt;booking_date&gt;2012-11-18&lt;/booking_date&gt;<br>
&lt;booking_site_conf_num&gt;&lt;/booking_site_conf_num&gt;<br>
&lt;booking_site_name&gt;OrbitzforBusiness&lt;/booking_site_name&gt;<br>
&lt;booking_site_phone&gt;112345&lt;/booking_site_phone&gt;<br>
&lt;booking_site_url&gt;&lt;/booking_site_url&gt;<br>
&lt;record_locator&gt;ABC&lt;/record_locator&gt;<br>
&lt;supplier_conf_num&gt;ASDRT&lt;/supplier_conf_num&gt;<br>
&lt;is_purchased&gt;false&lt;/is_purchased&gt;<br>

&lt;total_cost&gt;90.01&lt;/total_cost&gt;<br>
&lt;Segment&gt;<br>
&lt;StartDateTime&gt;<br>
&lt;date&gt;2013-07-02&lt;/date&gt;
&lt;time&gt;14:31:00&lt;/time&gt;<br>
&lt;/StartDateTime&gt;<br>
&lt;EndDateTime&gt;<br>
&lt;date&gt;2013-07-02&lt;/date&gt;&lt;time&gt;15:39:00&lt;/time&gt;<br>
&lt;/EndDateTime&gt;<br>
&lt;start_airport_code&gt;LAS&lt;/start_airport_code&gt;<br>
&lt;end_airport_code&gt;LAX&lt;/end_airport_code&gt;<br>
&lt;marketing_airline&gt;AS&lt;/marketing_airline&gt;<br>
&lt;marketing_flight_number&gt;123&lt;/marketing_flight_number&gt;<br>
&lt;seats&gt;6C&lt;/seats&gt;<br>
&lt;service_class&gt;Coach&lt;/service_class&gt;<br>
&lt;/Segment&gt;<br>
&lt;Traveler&gt;&lt;first_name&gt;&lt;/first_name&gt;<br>
&lt;last_name&gt;&lt;/last_name&gt;&lt;/Traveler&gt;<br>
&lt;/AirObject&gt;<br>
&lt;/CrsRequest&gt;

That is when we hold an itinerary and trying to send that to tripit,it is displayed in tripit site with "Not Purchased" element at the end and in the case of purchased itinerary,it is  dispalyed as before.

Would you think that, it will be okay or do we need to do any modification?

Kindly advise.
Thanking You,
Jincy

**Comment by tariqislam** [comment]
Hi,

You have an error in the xml tag (not sure if it's because of github's html encode/decode), here is the version that works for me:

``` xml
<Request>
<AirObject>
<Image>
<url>http://www.orbitzforbusiness.net/site/img/chrome/nav/ofbLogoSmall.gif</url>
</Image>
<booking_date>2012-11-18</booking_date>
<booking_site_conf_num></booking_site_conf_num>
<booking_site_name>OrbitzforBusiness</booking_site_name>
<booking_site_phone>112345</booking_site_phone>
<booking_site_url></booking_site_url>
<record_locator>ABC</record_locator>
<supplier_conf_num>ASDRT</supplier_conf_num>
<is_purchased>false</is_purchased>
<total_cost>90.01</total_cost>
<Segment>
<StartDateTime>
<date>2013-07-02</date>
<time>14:31:00</time>
</StartDateTime>
<EndDateTime>
<date>2013-07-02</date>
<time>15:39:00</time>
</EndDateTime>
<start_airport_code>LAS</start_airport_code>
<end_airport_code>LAX</end_airport_code>
<marketing_airline>AS</marketing_airline>
<marketing_flight_number>123</marketing_flight_number>
<seats>6C</seats>
<service_class>Coach</service_class>
</Segment>
<Traveler><first_name></first_name>
<last_name></last_name></Traveler>
</AirObject>
</Request>
```

Also, if you change the is_purchased to true in the above xml, it worked in my testing to set the "Is purchased" flag for the trip item.

Thanks.

Tariq
