### ISSUE TITLE
HTML Flight Tracker (Map) From Current Itinerary

### ISSUE THREAD

**Issue by ReedLogistics** [tripit/api#265]
Hi all, 
I'm wondering if it's possible to use Tripit's API to fetch my current itinerary, via API, and display my flights on a map, I can embed onto my sites. I am an air courier and would be using this for clients to know whether I am available, AND/OR if I'm in their area if they wanted to hire me. I was hoping for a cut-and-dry situation like embedding TripIt's API into Mapbox. But I have little-no experience with this stuff.

Your help is appreciated.

**Comment by printscreen** [comment]
Hi @ReedLogistics 

Yes, the Tripit API does allow you to pull current trip information. You will need to create a new application at https://www.tripit.com/developer. Once you have an application, you will need to authorize the application to access your account. Once it has authorization, you can do basic Trip operations such as listing current trips. As you can see, there are a few more steps than just a normal REST API with an authorization token. It behaves like an OAuth application, so it is not as cut and dry as other APIs.

Here is a link to the documentation
http://tripit.github.io/api/

**Comment by ReedLogistics** [comment]
Thank you. But, how do I implement this?

**Comment by printscreen** [comment]
Thanks for your response. Besides reading through the API documentation referenced, we can recommend a few resources to learn about API development such as [Udemy.com](https://www.udemy.com/courses/search/?q=rest+api&src=sac&kw=Api). The Tripit API is using OAuth version 1. [OAuth 1 Docs](https://oauth1.wp-api.org/docs/basics/Auth-Flow.html) will help you how you authorize an application to use the API.
