### ISSUE TITLE
problem includding tripit plugin

### ISSUE THREAD

**Issue by developer-arzion** [tripit/api#28]
Hi everyone! When I include the tripit plugin ("//www.tripit.com/js/sdk/tripit_sdk.js") as the documentation sais, the jquery included by tripit plugin, overlaps with my own inclusion of jquery causing that some funcionalities, that were working fine, stops working. any ideas about this? is this happening to anyone else?

thanks!

**Comment by tariqislam** [comment]
Hi,

I will look into this issue immediately, and will keep you updated.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi,

We have a fix on the work for this issue, and will push the fix out the first chance we get next year.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi,

This issue has been resolved and the fix is in production. Please let me know if you notice anything else awry.

Thanks.

Tariq
