### ISSUE TITLE
web plugin features

### ISSUE THREAD

**Issue by xuduo18** [tripit/api#29]
While reading the web plugin doc, i have 2 questions
1. is 'transport' appropriate for Flight ?  the example given uses Car even though the js does not support carObject.  In my opinion it is inappropriate as it is too generic for Flight
2.  Can i use one button to add both Activity and Lodge?   In our app we may have the customer purchase both in one booking.  I hope it does so we can use this web plugin as a shortcut. Would save a lot of $ and time.

Thanks!

**Comment by tariqislam** [comment]
Hi,

Very excited that you are using this new functionality.
1. Transport is used primarily for a transportation object (shuttles, bus, etc), and not for car rental or flight -- we do not support car or flight yet in this plugin.
2. At the moment, each button only submits one travel object. We do plan to add the functionality for multiple travel object submissions through a single button early next year.

If you have any other questions, please let me know. Thanks.

Tariq

**Comment by xuduo18** [comment]
That's good to know. Interestingly your document uses 'transport' as a car rental example. So i guess that's a bit confusing. 

Do you know if the plugin will be enhanced in Q1 or later? So we can decide if we develop it by ourselves or just wait for the new version. :-)

**Comment by tariqislam** [comment]
Good catch -- yes, the documentation was misleading. Essentially, a Transport object should be some form of transportation other than a car rental (bus, shuttle service, etc). For car rentals, we have the Car object. I have updated the online documentation to reflect this.

At the moment, however, the Add-to-TripIt plugin does not support Car (rental) objects. We hope to add this functionality by end of January next year.

Thanks.

Tariq

**Comment by xuduo18** [comment]
Great - by the end of Jan!

We allow our customers to book Hotel, Air, Car, Activities in one booking process. The confirmation page would show all 4 sections.  What we want to achieve is to add a 'tripit' button for customers to add 4 booking info to tripit API.

Should we expect this to be available by end of Jan?   Need to know so we can estimate our own development effort in case web plugin is not a fit.

Thank you!

**Comment by tariqislam** [comment]
I would add the following functionality by end of Jan:
- Car reservations
- Ability to send multiple travel objects through one A2T button.

I can't promise on Air yet, it's a bit more complex.

Thanks.

## Tariq Islam

TripIt  |  Developer Advocate

**Comment by tariqislam** [comment]
Hi,

I'm pleased to let you know that we have made additions to the Add-to-TripIt plugin:
- For the Activity object, you can add displayName and notes.
- A new Car object can be used for car rental reservations.
- Multiple plugin buttons can be rendered on the same page.

For more details, please visit our documentation page: http://tripit.github.com/api/doc/v1/plugins.html

Thanks.

Tariq
