### ISSUE TITLE
Question about TripIt API Terms of Service

### ISSUE THREAD

**Issue by russbear** [tripit/api#3]
I submitted the following question to TripIt Customer Service, but was referred to this site to post the question. 

I'm a TripIt Pro user, frequent traveler and iPhone developer.  I would like to start developing an iOS app using the TripIt API. Before I start full development of the app I want to make sure that I don't conflict with one of the paragraphs in the Terms of Service for the API, specifically:

F. Prohibitions. You agree not to do any of the following:
i. Use any TripIt API for any application that replicates or attempts to replace the essential user experience of TripIt.com.

The app I want to develop would display TripIt data to the customer while they are traveling, but in a unique manner different from the current TripIt web site and IOS app. It would offer functionality/information not currently available.  

The app would not have the look and feel of the existing TripIt iPhone app or web site and would not exactly duplicate the functionality.

Please let me know if my app would violate the terms of service for the API. Thanks!

**Comment by tariqislam** [comment]
Hi russbear,

Please check your email in order to take this conversation offline.

Regards,

## Tariq Islam

Developer Advocate
