### ISSUE TITLE
"Invalid Signature" while trying to obtain authorized access token

### ISSUE THREAD

**Issue by felixrieseberg** [tripit/api#30]
Hi guys,

I'm currently trying to implement TripIt in one of my Windows 8 apps. Using Microsoft's WebAuthenticationBroker, I have no problems obtaining a request token and sending the user to authorization.

However, when I try to obtain an access token, the request fails with "invalid signature". Since the same method is fine for the other two steps, I have no idea what's going on. I'm obviously doing something wrong, maybe you guys can point me to it?

Here's my request POST (I changed the consumer key though)

<pre>
POST https://api.tripit.com/oauth/access_token HTTP/1.1
Accept: */*
Authorization: OAuth oauth_consumer_key="06ac4ac2018b939f0e5c3f72cc1bbd6e2e4547e1", oauth_token="5267d4a2413e3d2544dee94b2c18adafb7821752", oauth_token_secret="3fb99af0879908814db461668e9dc545cda3f85e", oauth_nonce="579242313", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1356700441", oauth_version="1.0", oauth_signature="sATz0M3XWunXVMVF6OTXPjr4RYk%3D"
If-Modified-Since: Mon, 27 Mar 1972 00:00:00 GMT
Cache-Control: no-cache
Pragma: no-cache
Accept-Language: en-GB,en;q=0.5
UA-CPU: AMD64
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; MSAppHost/1.0)
Host: api.tripit.com
Content-Length: 0
Connection: Keep-Alive
Cookie: BIGipServertripit-web=1895942922.20480.0000
</pre>

Here's the signature base string:

<pre>
POST&https%3A%2F%2Fapi.tripit.com%2Foauth%2Faccess_token&oauth_consumer_key%3D06ac4ac2018b939f0e5c3f72cc1bbd6e2e4547e1%26oauth_nonce%3D579242313%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1356700441%26oauth_token%3D5267d4a2413e3d2544dee94b2c18adafb7821752%26oauth_token_secret%3D3fb99af0879908814db461668e9dc545cda3f85e%26oauth_version%3D1.0
</pre>

Thanks in advance!

**Comment by felixrieseberg** [comment]
Small addition: I verified that the signature seems to be correct using this guide (as recommended per TripIt API documentation): http://hueniverse.com/oauth/guide/authentication/

**Comment by tariqislam** [comment]
Hi,

It seems that your signature base string is wrong. It should not contain oauth_token_secret. As an example, here is my working signature base string:

POST&https%3A%2F%2Fapi.tripit.com
%2Foauth%2Faccess_token
&oauth_consumer_key%3D[CONSUMER_KEY]
%26oauth_nonce%3D94570fb19cc7ab78cdff2bfb5adc19db
%26oauth_signature_method%3DHMAC-SHA1
%26oauth_timestamp%3D1356982662
%26oauth_token%3D[OAUTH_TOKEN]
%26oauth_version%3D1.0

Looking at the documentation here:

http://oauth.net/core/1.0/#signing_process

the section "Normalized Request Parameters" mentions, in the first bullet point, having parameters in the OAuth HTTP Authorization header. If you follow the OAuth HTTP Authorization header, you'll see that the oauth_token_secret is not there.

Let me know if you have any issues.

Thanks.

Tariq

**Comment by felixrieseberg** [comment]
Hi,

I can't get it to work using the same signature base string. I'm currently looking at your Python implementation, trying to figure out differences looking at the code side-by-side. I'll report back!

Thanks so far,
Felix

**Comment by tariqislam** [comment]
Closing this issue due to no recent feedback.
