### ISSUE TITLE
SignIn rendering issue in Windows 8 WebAuthenticationBroker.

### ISSUE THREAD

**Issue by LoungeFlyZ** [tripit/api#31]
Hi there,

Currently whenever the following Authorization URLs are rendered using the WebAuthenticationBroker helper in Windows 8 (WebView control) there is a problem with the Sign In button rendering.

https://m.tripit.com/oauth/authorize
https://www.tripit.com/oauth/authorize

Attached is an example of what the mobile one looks like during an OAuth flow.

![TripIt](https://f.cloud.github.com/assets/1360936/37878/97c3992e-54b3-11e2-84f4-7b5be94e061e.png)

It looks like a simple CSS or JS issue when used in a WebView control on Windows 8. 

Is this a known issue? or possible to get fixed?  It's not stopping me from building my app ... but it isnt great telling users they might see a blank box show where the sign in button should be.

Thanks,

-Chris.

**Comment by tariqislam** [comment]
Hi Chris,

We will look into a fix for this -- we haven't heard of this issue before.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi Chris,

Would you be able to send me your project code that shows the error above, so we can reproduce the error? You may email the code to tariq@tripit.com

Thanks.

Tariq

**Comment by LoungeFlyZ** [comment]
Thanks Tariq,

I will package up a small sample app and email it over to you that demonstrates the issue.  Note however that you will need a Win 8 machine in order to try it out.

Thanks,

-Chris.

**Comment by ghosh9691** [comment]
I am facing the same issue! Surprisingly, in the month of December, I think this was working just fine.

**Comment by ghosh9691** [comment]
Is there any progress on this issue? I find it weird that the page displays correctly in IE10, Chrome and other browsers, but is not showing correctly in WebAuthenticationBroker which lauches a new webhost under the covers...

**Comment by tariqislam** [comment]
Sorry, no updates yet. We are still looking into the issue. I will keep you posted ASAP when this is solved.

Thanks.

Tariq

**Comment by LoungeFlyZ** [comment]
This is still an issue.  It is also an issue on Windows Phone 8 now also.

**Comment by LoungeFlyZ** [comment]
Any update?  Its been 6 months! :)

**Comment by tariqislam** [comment]
Hi,

I will try and prioritize this within our timeline for a sooner fix, my sincere apologies for the delay!

Tariq

**Comment by LoungeFlyZ** [comment]
Just noticed this looks like it is fixed now.

**Comment by tariqislam** [comment]
Fixed as per LoungeFlyZ, hence closing.
