### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by LoungeFlyZ** [tripit/api#34]
Hiya,

I was wondering if there was anywhere we could subscribe to that would notify us when an API changes.  For example I just found there are some new flight status codes that are not included in the documentation page ... but are in the XSD.  

Basically any time the XSD changes it would be great if we could be notified as it may break apps.

Thanks,

-CJ.

**Comment by tariqislam** [comment]
Hi Chris,

I understand the need to follow code changes more strictly, and all our changes to the XSD have always been backward compatible. Our online API documentation (http://tripit.github.com/api/) is usually up-to-date with any API code changes, but this may be an instance where an XSD change was made before documentation changes, my apologies for that. For the future, it may be easiest if you follow our documentation repository (https://github.com/tripit/api) through GitHub and hence will be notified of any documentation changes.

Best regards,

Tariq

**Comment by LoungeFlyZ** [comment]
Thanks Tariq,

In this case the change wasn't strictly backwards compatible.  Adding new flight status codes to the XSD means we people that consume the app need to handle situations when it receives data that doesn't match the previous version of the XSD and thus issues.

I'll follow via github ... but please be extra mindful there are consumers of your API that prefer not to be broken.

Thanks.
