### ISSUE TITLE
Default to Sign-in page when using OAuth

### ISSUE THREAD

**Issue by ghosh9691** [tripit/api#35]
When I attempt to use OAuth to get a user to authorize my application, the page shown by tripit.com is the "sign up" page. I have to switch it to the "sign in" page. What can I do in order to not show the "sign up" page? Btw, this is a C# application using the WebAuthenticationBroker from .NET

**Comment by tariqislam** [comment]
Hi,

We do not provide any option to change to login page for a user during the OAuth flow, as this is not a standard OAuth1 functionality. Please do note that even form the sign-up page, if a user has an account, he/she will be signed in instead of going through the signup flow.

Thanks.

Tariq

**Comment by kuroshhashemi** [comment]
I second this request.  Bad UX to send to sign up instead of sign in.  If anything, send to Sign In with option for user to change to sign up
