### ISSUE TITLE
C# binding missing FlightStatusCodes

### ISSUE THREAD

**Issue by ghosh9691** [tripit/api#37]
The official C# binding for the tripit API is missing FlightStatusCodes 405 thru 408. This causes an XmlSerialization exception to be thrown when attempting to download trip data that contain these flight status codes.

Please add these missing flight status codes to the binding.

Thanks!

**Comment by tariqislam** [comment]
Thank you for the bug report, will get this done!

Tariq

**Comment by tariqislam** [comment]
Hi,

Please recompile the C# binding after first doing a 'make clean'. This will download the latest tripit-api-obj-v1.xsd from TripIt and add in the missing FlightStatusCodes.

Thanks.

Tariq
