### ISSUE TITLE
Notice in the API code

### ISSUE THREAD

**Issue by aksharjamgaonkar** [tripit/api#42]
Hi  all,

Iam trying to get familar with the API, however iam not sure what these notices are.

any help would be appriciated.

Please forgive me if this question seems very silly. iam a novice at this

Notice: Undefined variable: argv in C:\xampp\htdocs\tripit_php_v1_33427\example.php on line 21

Notice: Undefined variable: argv in C:\xampp\htdocs\tripit_php_v1_33427\example.php on line 22
Usage: api_url consumer_key consumer_secret access_token access_token_secret

**Comment by tariqislam** [comment]
Hi,

It seems like you are using the php binding. Have you created a dev account with Tripit (https://www.tripit.com/developer)? If you have created a dev application, you then need to go through the OAuth flow and follow the 3 steps (http://tripit.github.com/api/doc/v1/index.html#authentication_section). For step 1, use the file get_request_token.php, and for step 3, use the file get_authorized_token.php. You can then make an API call using the example.php file.

Thanks.

Tariq

**Comment by aksharjamgaonkar** [comment]
Hi  tariq, Thanks a lot for your reply....i have created a dev account and i will go through the steps you suggested.
Thanks a lot for your reply.really appriciated

**Comment by tariqislam** [comment]
No worries, let me know if you have any other questions!

Tariq
