### ISSUE TITLE
java.lang.ClassCastException - Request.java line 71

### ISSUE THREAD

**Issue by pwatt01** [tripit/api#43]
I kept on getting the error 
java.lang.ClassCastException: $Proxy0 cannot be cast to org.apache.http.message.BasicHttpResponse
even when the API call was successful. I found that changing the line
BasicHttpResponse response = (BasicHttpResponse) httpClient.execute(request);
to
HttpResponse response = (HttpResponse) httpClient.execute(request);

rectified the issue. Are you able to test and update the source if needed?

**Comment by tariqislam** [comment]
Hi,

Thank you for the bug report. Before I make changes to the source, could you give me a few details on this issue:
- Java version
- OS

Thanks.

Tariq

**Comment by pwatt01** [comment]
Thanks for your reply Tariq.

I am not at that PC at the moment, so i cannot give you exact details, but i do know that i used Windows 7 64bit and Java 1.7. Ill get back to you with the exact version later on if you want.

Regards

Peter

**Comment by tariqislam** [comment]
Peter,

The patch has been uploaded to git. Thanks for the help!

Tariq
