### ISSUE TITLE
how to use get_request_token.php to obtain an unauthorized request token

### ISSUE THREAD

**Issue by aksharjamgaonkar** [tripit/api#44]
Hi All,

Iam trying to implement the php version and make a API call. Iam a bit bit confused any help would be really appreciated.

Iam reading the documentation "http://tripit.github.com/api/doc/v1/index.html"  and here it states that 

To obtain a request token POST the following request parameters to the URL:  make a POST request to https://api.tripit.com/oauth/request_token with parameters. Iam doing that but iam getting error "invalid signature".

Also how can i use "get_request_token.php" to do the same.any help on this will be really appriaciated.

**Comment by aksharjamgaonkar** [comment]
I have also tried to use the http://hueniverse.com/2008/10/beginners-guide-to-oauth-part-iv-signing-requests/ to genrate the oauth_signature but still iam getting same error. Please help.

**Comment by aksharjamgaonkar** [comment]
Hi All,

Iam able to get the oauth_token and oauth_token_secret, by commenting,
if (count($argv) < 4) {
    print "Usage: " . $argv[0] . " api_url consumer_key consumer_secret\n";
    exit;
 }

and hardcoding 
$api_url = "https://api.tripit.com"; 
$oauth_consumer_key = "";
$oauth_consumer_secret = "";

but is this the rite way.....????

how can i dynamically generate this instead of hard coding and using "get_request_token.php".

any help would be appreciated.

**Comment by tariqislam** [comment]
Hi,

if you comment out:
`if (count($argv) < 4) {
print "Usage: " . $argv[0] . " api_url consumer_key consumer_secret\n";
exit;
}`

Then you would have to hardcode those variables for get_request_token.php to work. Otherwise you can call it from the command line:
`$ php get_request_token.php https://api.tripit.com <oauth_consumer_key> <oauth_secret>

I am not sure what you mean by the 'correct way'. This specific PHP script here simply shows you what method calls you need to make using the TripIt and OAuthConsumerCredential classes (provided by our PHP API binding) to get the request token. Similarly, the get_authorized_token.php works in the same way, as an example.

Please note that our API binding does all the signing of the request for OAuth1, you don't have to deal with oauth signatures and such.

You may want to look at the following blog post about using our API binding:

http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html

The blog post refers to the Python API binding, but that is very similar to the PHP binding.

Please let me know if you have any other questions.

Tariq

**Comment by aksharjamgaonkar** [comment]
HI Tariq, 

Thanks a lot for your reply. What is the way to implement the same thing in a web application, For eg there i cannot make use of command line. 

Then do i have to use curl or any other method .

Please suggest.

**Comment by tariqislam** [comment]
Edit:
Changed the following line in the second code fragment below:
Old: $oauth_token = $_GET('oauth_token');
New: $oauth_token = $request_token;

Hi,

Sorry I don't have an example code that ties the entire process (all steps) together, but at a higher level it could look like this (I haven't verified this code):

``` php
// Assume this file is called from http://my.site.com/init_tripit_oauth.php
// File name: init_tripit_oauth.php

$oauth_consumer_key = 'ABC';
$oauth_consumer_secret = 'SECRET123';

// First get the oauth request token:
$oauth_credential = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret);
$tripit = new TripIt($oauth_credential, $api_url);
$response = $tripit->get_request_token(); 
// Extract request token and request token secret from the response string (MOCKUP, NOT ACTUAL WORKING CODE)
$response = explode("&", $response);
$request_token = explode("=", $response[0]);
$request_token = $request_token[1];
$request_token_secret = explode("=", $response[1]);
$request_token_secret = $request_token[1];

// Then redirect the user to authorize the TripIt app:
$callback_url = 'http://my.site.com/oauth_callback.php';

$location = 'https://www.tripit.com/oauth/authorize?oauth_token=' . $request_token . '&oauth_callback=' . $callback_url;
header( 'Location: ' . $location );
```

The user will now be prompted to authorize your app with the TripIt API. Once the user approves this, he/she will be redirected to your callback url, http://my.site.com/oauth_callback.php. You can now get the authorized access token for that user.

``` php
// Assume this file is called from http://my.site.com/oauth_callback.php
// File name: oauth_callback.php

$oauth_token = $request_token;
$oauth_token_secret = $request_token_secret; // This is the one you got earlier when getting a request

$oauth_credential = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret, $oauth_token, $oauth_token_secret);

$tripit = new TripIt($oauth_credential, $api_url);
print serialize($tripit->get_access_token()) . "\n";
```

Hope this helps.

Tariq

**Comment by aksharjamgaonkar** [comment]
Thanks a lot Tariq ill check for this and let you know if i face any issues
really appreciate your quick response...thanks a lot once again

**Comment by aksharjamgaonkar** [comment]
Hi Tariq,

I have managed to implement the the code and its working now. I have two questions,

1) Please let me know if can share this.

2) is there any way we can do this in the API,

iam a user of tripit and i have created a account and allow the application to modify my trip data, Next time is it possible to identify programatically if a user has allowed access to tripit data and if not redirect him for authorization else don't redirect and skip the redirect step.

Thanks a lot in advance.

**Comment by tariqislam** [comment]
Hi,

Yes, you can share the code. For the second question, OAuth is the mechanism that allows you as a 3rd party developer to access data about a given user once that user gives you permission. Once a user gives permission to your app, you don't need to take the user through the OAuth flow again, since you can use the OAuth access token and secret you obtained in Step 3 to make API calls. Please read the following for a detailed overview of OAuth: 

http://hueniverse.com/oauth/guide/workflow/

Thanks.

Tariq

**Comment by aksharjamgaonkar** [comment]
Hi Tariq,

Thanks a lot for your reply. It was of great help. Ill share my code in some time iam still trying to fine tune a bit. 

Thanks again.

**Comment by aksharjamgaonkar** [comment]
This is the first file which you load in your browser. i have named this files as initiaterequest.php

<?php
session_start();

// Step 1
include_once('tripit.php');

$api_url = "https://api.tripit.com";
$oauth_consumer_key = "XXXX";
$oauth_consumer_secret = "XXXX";

$oauth_credential = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret);

$tripit = new TripIt($oauth_credential, $api_url);

$oauthToken = serialize($tripit->get_request_token());

// Add it in session for the after approval page to access it
$_SESSION["request_token"] = $oauthToken;

$var = unserialize($oauthToken);

// Step 2 , send user to confirming the application
$link = 'https://www.tripit.com/oauth/authorize?oauth_token='.$var["oauth_token"].'&oauth_callback=http://localhost:8000/tripit_php_v1_33427/afterapproval.php';

header('Location: '.$link);
?>

Then the next file is named as afterapproval.php

<?php
session_start();
include_once('tripit.php');

$request_token  = unserialize($_SESSION['request_token']); 

// Step 3
$api_url = "https://api.tripit.com";
$oauth_consumer_key = "XXXX";
$oauth_consumer_secret = "XXXX";
$request_token_var = $request_token['oauth_token'];
$request_token_secret = $request_token['oauth_token_secret'];
$cSession = curl_init(); 
$postVar = array('API_URL'=>'https://api.tripit.com','API_KEY' => $oauth_consumer_key,'API_SECRET'=>$oauth_consumer_secret,'REQUEST_TOKEN' => $request_token_var,'REQUEST_TOKEN_SECRET' => $request_token_secret);
curl_setopt($cSession,CURLOPT_URL,"http://localhost:8000/tripit_php_v1_33427/get_authorized_token.php");
curl_setopt($cSession,CURLOPT_RETURNTRANSFER,true);
curl_setopt($cSession,CURLOPT_HEADER, false); 
curl_setopt($cSession, CURLOPT_POST, true);
curl_setopt($cSession,CURLOPT_POSTFIELDS,$postVar); 
$result=curl_exec($cSession);
curl_close($cSession);
$outh_authtoken = unserialize($result);

// Logic to create the Itneray on the fly

// Step 4

$oauth_access_token = $outh_authtoken['oauth_token'];
$oauth_access_token_secret = $outh_authtoken['oauth_token_secret'];

// Create an OAuth Credential Object
$oauth_cred = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret, $oauth_access_token, $oauth_access_token_secret);

// Create a new TripIt object
$t = new TripIt($oauth_cred, $api_url);

// Create a new trip
print "Create a new test trip to New York: \n";
$xml='<Request><Trip><start_date>2009-12-17</start_date><end_date>2009-12-27</end_date><display_name>Test: New York, NY, December 2009</display_name><is_private>true</is_private><primary_location>New York, NY</primary_location></Trip></Request>';
$r = $t->create($xml);
print_r($r);

print "Get my list of travel objects in upcoming trips: \n";
$r = $t->list_trip();
print_r($r);
// The first trip in the list
print_r($r->Trip[0]);

// End logic 
?>
</html>

**Comment by aksharjamgaonkar** [comment]
Hi tariq,

I have shared my code above, please let me know if there are any suggestion or improvements i can make above.

Thanks in advance.

**Comment by tariqislam** [comment]
Hi,

A couple of comments here:

``` php
$_SESSION["request_token"] = $oauthToken;
```

In the above, you are saving your request token and request token secret into the $_SESSION, which is then saved into a cookie in the browser. In essence, it is ok to share the request token with the user since you have to direct them to log into tripit with that token, but you should not save the request token secret in a browser cookie... perhaps save it in your backend database.

``` php
curl_setopt($cSession,CURLOPT_URL,"http://localhost:8000/tripit_php_v1_33427/get_authorized_token.php");
curl_setopt($cSession,CURLOPT_RETURNTRANSFER,true);
curl_setopt($cSession,CURLOPT_HEADER, false); 
...
```

You should not need to call that file (get_authorization_token.php)  using curl... the logic in that file should be in your afterapproval.php file.
Hence:

``` php
<?php
session_start();
include_once('tripit.php');

$request_token = unserialize($_SESSION['request_token']); // like I said above, you shouldn't be saving request token secret in a session

// Step 3
$api_url = "https://api.tripit.com";
$oauth_consumer_key = "XXXX";
$oauth_consumer_secret = "XXXX";
$request_token_var = $request_token['oauth_token'];
$request_token_secret = $request_token['oauth_token_secret'];

$oauth_credential = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret, $request_token_var, $request_token_secret);

$tripit = new TripIt($oauth_credential, $api_url);
$access_token = serialize($tripit->get_access_token());
...
...
```

Hope this helps.

Tariq

**Comment by aksharjamgaonkar** [comment]
Hi Tariq,

Thanks a lot for your suggestions i will definitely incorporate that in my code, also i had used session for example purpose ill surely make use of database.

Thanks again for your prompt suggestions and help. I really appreciate that.

**Comment by tariqislam** [comment]
No worries!

Tariq
