### ISSUE TITLE
 Access Request Failed Please go back to the application or website where you began the process and try again.

### ISSUE THREAD

**Issue by aksharjamgaonkar** [tripit/api#45]
Hi All,

Iam getting this  error when i redirect user for the second step 
"Step 2: Obtain User Authorization".

Access Request Failed
Please go back to the application or website where you began the process and try again.

What iam i doing wrong. Any help on this  would be appriciated.

**Comment by tariqislam** [comment]
Hi,

Please look at the following blog post:

http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html

It should guide you through the details of getting authorization and making the API call.

Thanks.

Tariq

**Comment by cemre** [comment]
My old app that's worked for a couple years suddenly started giving this error. The tripit PHP library I was using was old (the 2010 version), I updated it with the new one and things are working again :)
