### ISSUE TITLE
Attaching pdf, documents with plans / trips

### ISSUE THREAD

**Issue by aksharjamgaonkar** [tripit/api#47]
Hi ,

Is there any way i can attach documents to a trip / plan via the tripit API. 
Any suggestion or a workaround would be really appreciated.

Thanks in advance.

**Comment by tariqislam** [comment]
Hi,

We do not have any mechanism to attach documents via the API. In a trip object we do have "Notes" that can be added, but you would have to parse the pdf text on your end and then send the data as plain text in the Note object.

Thanks.

Tariq

**Comment by aksharjamgaonkar** [comment]
Thanks tariq for your prompt reply.

**Comment by rtm** [comment]
Still want this feature after five years.

**Comment by michael-ferioli** [comment]
Me too.  India issues electronic visas and I want to attach a PDF to the trip and I cannot. 👎

**Comment by Richardgriff** [comment]
One option is to convert the PDF to a JPG and upload it as a photo
