### ISSUE TITLE
Email Format to send to plans@tripit.com

### ISSUE THREAD

**Issue by aksharjamgaonkar** [tripit/api#49]
Hi Tariq,

Is there any sample email format which i can send to plans@tripit.com to see how a trip and its plans get created. I have successfully created a trip and plans using Tripit API but i want to check the same by sending emails to plans@tripit.com.

The main reason behind this is i want to attach a document to my trip and using API currently i cannot attach a document.

any help on this would be really appreciated.

Thanks in advance,

**Comment by tariqislam** [comment]
Hi,

TripIt parses a few thousand different formats of reservations, from airline confirmation emails to car reservation emails, hotel reservations, etc. One example of how an email is parsed would be if you go to opentable.com and make a reservation, then forward that email, you'll be able to see what plans and trip objects are extracted from that email. It would help to know what your application is doing in order to give better recommendations. Feel free to email me at tariq@tripit.com instead of posting in this public forum.

Thanks.

Tariq

**Comment by aksharjamgaonkar** [comment]
Hi Tariq,

Thanks again....i will definitely mail you.

**Comment by andrewshadura** [comment]
Do you support Structured Data (schema.org)?

**Comment by hliss** [comment]
@andrewshadura Hi, we're not currently able to support schema.org via email. But to also answer @aksharjamgaonkar as well, check out our standard [confirmation email format](https://tripit.zendesk.com/hc/en-us/articles/226108747-Vendor-confirmation-email-support) available for such testing use. Thanks for the question!

**Comment by andrewshadura** [comment]
Well, that is very language specific and vendor specific (uses TripIt as a
part of the markup), unlike schema.org. Is supporting schema.org a part of
at least the long-term plans?

-- 
Cheers,
  Andrew

**Comment by hliss** [comment]
Hi @andrewshadura, it's certainly always on the table. Preliminary investigations, however, have surfaced that emails using schema.org formatting haven't generally provided as rich data as a user would expect TripIt to extract for their itinerary. We're continuing to keep eyes on it!

**Comment by andrewshadura** [comment]
If I were you, between no data and slightly incomplete data I'd certainly
choose slightly incomplete data. But fine, it's up to you.

-- 
Cheers,
  Andrew

**Comment by amitjaju82** [comment]
USe this prompt on any AI App and then copy paste the response in email and send to plans@tript.com

Act as a GDS (Global Distribution System) expert. I need to convert a travel itinerary into the raw "Worldspan/Galileo Print" format so I can import it into TripIt.

Rules for Conversion:
1. Strip all conversational text, headers, and labels.
2. Output ONLY the code block in the specific format below.
3. Use the exact spacing and line structure shown in the example.
4. Calculate the Day and Month (e.g., 01JUL) based on the input dates.
5. Use "HK[number of passengers]" for the status code (e.g., HK1 for solo, HK4 for four people).

Use this schema as your template:
---
1. [LASTNAME]/[FIRSTNAME] 2. [LASTNAME]/[FIRSTNAME] ...
1 [AIRLINE_CODE] [FLIGHT_NUM][CLASS_CODE] [DDMMM] [ORIGIN][DEST] HK[COUNT] [DEP_TIME] [ARR_TIME] /E
2 [AIRLINE_CODE] [FLIGHT_NUM][CLASS_CODE] [DDMMM] [ORIGIN][DEST] HK[COUNT] [DEP_TIME] [ARR_TIME] /E
*ALL FLIGHTS CONFIRMED*
TKT: [ANY_13_DIGIT_NUMBER]
PNR: [PNR_CODE]
---

Example Output (for reference):
1. ABBOTT/JOHN
1 DL 893Q 01FEB DFWATL HK1 0700 1019 /E
*ALL FLIGHTS CONFIRMED*
TKT: 0062481234102
PNR: ABCK58

My Raw Itinerary:
[PASTE YOUR NEW EMAIL HERE]
