### ISSUE TITLE
how to find out flight info using flight no. and airline code

### ISSUE THREAD

**Issue by diaspark58** [tripit/api#5]
hello,

right now i have got completely locked while integrating tripit api in my android app.
in my app i want to enable the user for making a simple flight look up request on the basis of airline code and flight no. directly.
i have already gone through api documentation several times but didn't find any thing regarding this.
is there something i am missing ? or tripit doesn't provide such kind of functional support.
any help will deeply be appreciated. THANKS IN ADVANCE.

**Comment by tariqislam** [comment]
Hi diaspark58,

I'm sorry but we don't provide a public interface to resolve carrier and flight number into flight information.

Regards,

## Tariq Islam

Developer Advocate
Tripit.com

**Comment by diaspark58** [comment]
hi tariqislam,

THANK YOU :)
