### ISSUE TITLE
TripIt Pro Data returning undocumented flight status values

### ISSUE THREAD

**Issue by petele** [tripit/api#51]
I've noticed a couple of flight's returning undocumented flight_status values for TripIt Pro users.  For example, earlier today I saw 406 for one flight.  Can we get these documented please?

Thanks!

**Comment by tariqislam** [comment]
Hi Pete,

The flight status codes (including 406) are documented on our XSD (https://api.tripit.com/xsd/tripit-api-obj-v1.xsd). Perhaps you have an old copy of the XSD?

Thanks.

Tariq

**Comment by petele** [comment]
Awesome thanks - I hadn't actually looked at that.

I was looking at http://tripit.github.com/api/doc/v1/index.html#pro_data_section where they're not listed.

**Comment by tariqislam** [comment]
My fault as well, I overlooked that documentation section. Will change it there too.
