### ISSUE TITLE
Which profile is "my profile"?

### ISSUE THREAD

**Issue by scottdweber** [tripit/api#52]
Hello,

When I request a list of Trips from the API, it returns one or more user Profiles.  Is there a "right" way to determine if a particular Profile is the profile of the logged in user?

For example, maybe "is_client" indicates this?  But the meaning of "is_client" is undocumented.  Another possibility might be to check the value of activity_feed_url for the word "private" instead of "public"?  But it seems that activity_feed_url is not guaranteed to be there for every Profile.

There must be a right way to do this...

Thanks,
Scott

**Comment by scottdweber** [comment]
Hi Tariq,

Thanks for the help.  This should be exactly what I need.  Can I safely cache the profile_ref for the duration of the user's authenticated session?  Or is the profile_ref volatile?

Thanks again,
Scott

**Comment by tariqislam** [comment]
Hi Scott,

Actually I was wrong in my first answer above (I deleted it so as not to confuse others): you SHOULD use the "is_client" field since that notes that the profile is for the OAuth user on whose behalf you are making the call. Sorry for the confusion!

Tariq
