### ISSUE TITLE
last_modified not always updated on transport object 

### ISSUE THREAD

**Issue by petele** [tripit/api#53]
When I changed the Carrier Name and Departure Location Name on a Ground Transportation (via the web UI), and then query the API, the last_modified for the object doesn't get updated to indicate the object has been updated.

**Comment by tariqislam** [comment]
Hi,

I tested this functionality out and was unable to reproduce your issue: I made changes to those fields individually, and the last_modified field in the trip (via /v1/get/trip/id/<id> call) was changed.

Thanks.

Tariq

**Comment by petele** [comment]
Hmmm, I've changed this object about 4 or 5 times now, and it's still returning the same last_modified (which I believe is the date the item was created).

Here's the object I'm getting back:

``` javascript
[{"is_tripit_booking": "false", "display_name": "Ground Transportation", "is_client_traveler": "true", "relative_url": "/reservation/show/id/187933995", "Segment": [{"confirmation_num": "49238", "EndDateTime": {"date": "2013-09-01", "timezone": "America/New_York", "utc_offset": "-04:00", "time": "15:45:00"}, "start_location_name": "Google NYC", "id": "570332157", "StartDateTime": {"date": "2013-09-01", "timezone": "America/New_York", "utc_offset": "-04:00", "time": "15:00:00"}, "StartLocationAddress": {"city": "New York", "zip": "10011", "country": "US", "longitude": "-74.0020894", "state": "NY", "address": "111 8th Avenue, New York, NY 10011, USA", "latitude": "40.7406578"}, "EndLocationAddress": {"city": "Newark", "zip": "07114", "country": "US", "longitude": "-74.17821", "state": "NJ", "address": "Newark Airport", "latitude": "40.68987"}, "detail_type_code": "G", "carrier_name": "Ground Link", "end_location_name": "Newark Airport"}, {"confirmation_num": "49238", "EndDateTime": {"date": "2013-09-05", "timezone": "America/New_York", "utc_offset": "-04:00", "time": "13:30:00"}, "start_location_name": "Newark Airport", "id": "570332160", "StartDateTime": {"date": "2013-09-05", "timezone": "America/New_York", "utc_offset": "-04:00", "time": "12:30:00"}, "StartLocationAddress": {"city": "Newark", "zip": "07114", "country": "US", "longitude": "-74.17821", "state": "NJ", "address": "Newark Airport", "latitude": "40.68987"}, "EndLocationAddress": {"city": "New York", "zip": "10011", "country": "US", "longitude": "-74.0020894", "state": "NY", "address": "111 8th Avenue, New York, NY 10011, USA", "latitude": "40.7406578"}, "detail_type_code": "G", "carrier_name": "Ground Link", "end_location_name": "Google NYC"}], "is_display_name_auto_generated": "true", "last_modified": "1363122303", "is_purchased": "true", "trip_id": "67249728", "id": "187933995"}]
```

I'm using the Python API client, and responding to a plans_changed notification from TripIt for this event, I then do a t.get_trip(trip_id) for the specified trip and parse through each of the response objects.

**Comment by tariqislam** [comment]
Hi Pete,

Could you send me an email (tariq@tripit.com) with the following details so we can trace this behavior:
- Your OAuth Consumer, OAuth Token used
- Email address of account, Trip id, Reservation id.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Hi Pete,

The issue has been resolved, and the 'last_modified' value for each travel object should correctly reflect when that specific travel object was changed.

Thanks.

Tariq
