### ISSUE TITLE
Invalid signature error

### ISSUE THREAD

**Issue by vijaysureshkumar** [tripit/api#55]
Hi,

We are getting "401104.Invalid signature" for all calls to the Tripit API. The app is marked active on tripit. We also tried to refresh the API secret.. didnt help.
![tripit-1](https://f.cloud.github.com/assets/2889681/313292/b9d1db7a-97a7-11e2-825c-3d384f7ad125.png)

Pl help! 

thanks
Vijay

**Comment by tariqislam** [comment]
Hi,

Have you looked at the following issue that has been solved?

https://github.com/tripit/api/issues/54

Thanks.

Tariq

**Comment by vijaysureshkumar** [comment]
Hi Tariq,

Yes and we are already using https://api.tripit.com without the slash at the end. Any other ideas? thanks!

**Comment by tariqislam** [comment]
Hi,

Please send me the following information at my email, tariq@tripit.com:
- Your app's consumer key, and OAuth user token against which you are making API call
- Request url, OAuth signature string
- All request headers
- All response headers
- All response content
- When (date, time, timezone) the request was made (and error seen)
- What language and binding are you using?
- If you are using the PHP binding that we provided, please send me the tripit.php file.

Thanks.

Tariq

**Comment by tariqislam** [comment]
Problem was solved by updating the user's PHP binding to the latest version -- https://github.com/tripit/php_binding_v1
