### ISSUE TITLE
tripit api create object

### ISSUE THREAD

**Issue by dharamchag** [tripit/api#56]
I am trying to integrate tripit api using java.
I am able to retrieve trips from tripit api but unable to create trip object to post trip on tripit,

can any one send me snippet @ dharamchag88@gmail.com
or can do some help about this.

thanks in advance.

**Comment by tariqislam** [comment]
Hi,

Have you looked at out Java API binding (https://github.com/tripit/java_binding_v1)?
Inside, you'll see Example.java (https://github.com/tripit/java_binding_v1/blob/master/Example.java) which creates a Trip object.

Thanks.

Tariq

**Comment by dharamchag** [comment]
thanks for the reply.
Can u give me example to replace tripit on tripit.

Do  I need to have access token for that ?

**Comment by tariqislam** [comment]
Hi,

I'm sorry I don't understand what you mean by "replace tripit on tripit", can you please clarify? Also, you do need an access token to make API calls. Also, please make sure you are familiar with the OAuth1 flow (http://hueniverse.com/oauth/guide/). 

Thanks.

Tariq

**Comment by tariqislam** [comment]
Closing due to no response.
