### ISSUE TITLE
how can I creat tripit object with the help of access token provided?

### ISSUE THREAD

**Issue by dharamchag** [tripit/api#57]
I am able to create tripit object when I tried to integrate with tripit but after some time If want to post tripit with the help of access token I am not ablt to post and giving me error. below given is snippet for posting trips with create object.

Response r;

```
    String accessToken = socialnetwork.getAccessToken(userid,socialnetwork.getSocialNetworkId("Tripit"));

Credential cred = new OAuthCredential("391327d54d014e2b1f137e86ff1755cc9f66630b","9653d44f5a1320ba0429773b1c5a84b2a9c1d45d",accessToken.split(",")[0],accessToken.split(",")[1]);
    Client client = new Client(cred);
    Map<String, String> createMap = new HashMap<String, String>();
    createMap.put("xml", "<Request><Trip><start_date>2013-04-09</start_date><end_date>2013-04-27</end_date><primary_location>Jamnagar, NY</primary_location></Trip></Request>");
    r = client.create(createMap);
    System.out.println(r);
    System.out.println("done");
```

getting error some thing like this.
<Response><Error><code>401</code><detailed_error_code>106.100000</detailed_error_code><description>invalid token key: dc5eedf67cd9e9a2646b47c26b65a02e25bbbe9b</description></Error></Response>

please help if any one know, thanks in advance.
and u can send me snippet @ dharamchag88@gmail.com

**Comment by tariqislam** [comment]
Hi,

I would need more information to help you out with this matter. Please send me an email at tariq@tripit.com with the following details:
- What language are you using, and are you using our provided API binding; if you are using our API binding, when did you last update it
- Your app's consumer key, and OAuth user token against which you are making API call
- Request url, OAuth signature string
- All request headers
- All response headers
- All response content
- When (date, time, timezone) the request was made (and error seen)
- How often does the API call fail
- Anything else that may help me debug

Thanks.

Tariq

**Comment by tariqislam** [comment]
Closing due to no response.
