### ISSUE TITLE
how could I post trips in tripit with the help of previously generated access token ?

### ISSUE THREAD

**Issue by dharamchag** [tripit/api#58]

**Comment by tariqislam** [comment]
Hi,

Without any specific details, I can only point you to our documentation page (http://tripit.github.io/api/doc/v1/index.html#method_create) which shows how to create travel objects. Please note that an access token is always needed when making API calls, as shown in the OAuth1 specification (see http://hueniverse.com/oauth/guide/ for a guide to OAuth1).

Thanks.

Tariq
