### ISSUE TITLE
JSON AirObject

### ISSUE THREAD

**Issue by wannabehero** [tripit/api#61]
Hello.
You have a big breach in your API on JSON examples.

I'm trying to create AirObject using JSON. How can I construct valid JSON object ? (as far as I understand - we can't just have multiple "Segment" keys in one object).

My current data is following:

``` javascript
{
    "AirObject":{
        "Segment":{
            "StartDateTime":{
                "date":"2013-04-18",
                "time":"23:30:00"
            },
            "marketing_airline":"DL",
            "marketing_flight_number":"1",
            "end_city_name":"London",
            "EndDateTime":{
                "date":"2013-04-19",
                "time":"11:50:00"
            },
            "start_city_name":"New York"
        },
        "is_client_traveler":"true"
    }
}
```

This is your server response: 

``` javascript
{"Error":{"code":400,"description":"JSON did not validate with the xsd"}}
```

Btw, my POST arguments are "format=json&json=...."
API resource: /create

Please, do not refer to any authorization (signature) issues - I can create a sample "Trip" object using your single example from http://tripit.github.io/api/doc/v1/index.html#method_create
And I get success response (the trip is created)

Thank you in advance.

Best regards, 
Sergey Pronin

**Comment by wannabehero** [comment]
Oh. Occasionally, I found the solution.

"is_client_traveler" appeared to be a BAD field in the JSON.

Please, be so kind and provide some really useful info in you API documentation.

Regards,
Sergey Pronin.

**Comment by tariqislam** [comment]
Hi Sergey,

We are working on documentation on the API, and better debugging info when a request fails so that you can figure out what's going on sooner. Please let me know if you have other questions.

Thanks.

Tariq
