### ISSUE TITLE
Replace an air segment.

### ISSUE THREAD

**Issue by gthompson333** [tripit/api#65]
Hi,

Is it possible to replace an air segment?

Since there doesn't seem to be a Tripit object type specifying a segment, I'm guessing not.

I'm thinking I will have to first delete the segment, than create a new one.

Thanks

**Comment by gthompson333** [comment]
Ah, I discovered how to replace a segment.  

I specified to replace an air object, and provided the air object ID.  Within the JSON payload, I provided the new segment info, and Tripit seemed to figure out which segment to affect server-side.  Probably based on the date info, I'm figuring.

Now I have to figure out how to delete a segment.

**Comment by tariqislam** [comment]
Hi,

My apologies that the information was not in our API documentation (http://tripit.github.io/api/doc/v1/index.html#method_delete) but you can perform a segment delete using the /v1/delete/segment/id/<ID> endpoint.

For replacing a segment, it is recommended that you submit the entire existing payload for that object, and include any changes/additions to the segment section.

Thanks.

Tariq
