### ISSUE TITLE
Tripit OAuth sign out

### ISSUE THREAD

**Issue by gthompson333** [tripit/api#66]
Hi,

I'm implementing an iPhone Tripit client app, using your api. I'm able to sign in, and retrieve Tripit data with no problems.

I recently converted my app to use the browser based OAuth sign in pattern, rather than the webview pattern. I'm using your objective c binding example project as reference. I'm still able to sign in and retrieve data. The issue I'm having is signing out and then signing back in. After signing out and tapping the sign in button, the app switch to the browser occurs, as expected. But then, an app switch back to my app occurs immediately, without showing the Tripit sign in web page at all. The same issue seems to be reproduceable in your example app also.

Any suggestions? I will continue to investigate. Thanks.

**Comment by tariqislam** [comment]
Hi,

My apologies I do not have any ideas in this case, were you able to resolve the issue? And if so, if you don't mind, please let me know what you did to resolve it.

Thanks.

Tariq

**Comment by gthompson333** [comment]
Hi Tariq,

It would seem, after signing out, the server still recognizes my app as being signed in, for a period of time.  Immediately after signing out, when I attempt to sign in, the server will immediately issue a request token, without waiting for account credentials.  If I wait for a period of time after signing out, say 10 minutes or so, then attempt to sign in, the server responds correctly, and presents the sign in web page.

In addition, interestingly enough, Apple recently rejected my app, for using the browser based sign in method.  Apple requested that I use the webview instead.  I've appealed the decision, and am awaiting a reply.  I don't know why they rejected my app, since there are other apps, already in the store, that use the browser based sign in method.  I will let you know what Apple's response is.

Thanks,

Greg

**Comment by tariqislam** [comment]
Thanks Greg. That's interesting that browser-based OAuth is not being allowed... very strange. Do let me know what happens please...

Tariq

**Comment by tariqislam** [comment]
Hi Greg,

Any updates from your end?

Regards,

Tariq

**Comment by gthompson333** [comment]
Hi Tariq,

I did not hear anything from Apple on this.  I think it may be one of those things that depends on the reviewer.  All I can really say at this point, is that if an app switch to the browser, for sign in occurs, there is a chance that the app will get rejected.  I believe the app review guidelines do state that an app should not app-switch if there is an alternative method.

By the way, Tariq, my app, TravelDax, is now in the app store.  I hope it abides by all of Tripit's requirements for API usage.  Would it be possible for Tripit to take a look, and hopefully include it as apps that work with Tripit?  That is, Tripit's website has a page listing all of the apps that work with Tripit.

If I hear anything from Apple, I will, of course, respond ASAP.

Cheers,

Greg

**Comment by tariqislam** [comment]
Hi Greg,

We shall definitely look at it and see what we can do to include it in that page.

Thanks for the update.

Tariq

**Comment by gthompson333** [comment]
Thanks much, Tariq.

The latest version includes an in-app purchase item, to view the user's Tripit Pro data.  It might help Tripit score a few Tripit Pro subscriptions.

Greg

**Comment by yamek** [comment]
Hello,

I'm having the same "issue" with browser based authentication...
On my site, there is a link to export information into TripIt, the first time the user clicks it, it is successfully redirected to TripIt login page and back when the user logs in. The problem is that in a period of time, if the user clicks it again, TripIt immediately redirects back, and I need it to ask again for security credentials (as it may be another user).

I've been searching about it, and some sites (like Facebook and Twitter) allow this by specifying a request parameter when asking for the request token.

Thanks

**Comment by tariqislam** [comment]
Hi,

It seems like what Facebook and Twitter are doing is an additional enhancement to OAuth1's flow in order to support some kind of sign-in functionality from an external site. At this point we do not have plans to support this sign-in functionality in OAuth1, but we will consider it for OAuth2 when we develop it in the near future.

Thanks!

Tariq

**Comment by jramsdale** [comment]
I'd like to request a "force_login" feature as well. Depending on a browser cookie is incorrect behavior on a shared computer and leads to a poor user experience in addition to being a possible security risk. Fitbit and Untappd also support this behavior as an option but many sites force login on every OAuth interaction.

**Comment by tariqislam** [comment]
We will take this into request as a feature.

Thanks.

Tariq
