### ISSUE TITLE
Limit on list/trip results

### ISSUE THREAD

**Issue by keavy** [tripit/api#67]
I noticed that only 5 trips are returned when fetching trips (e.g. from https://api.tripit.com/v1/list/trip/past/true).

I would like to fetch all past trips.

Could you advise how to remove or increase the limit? I couldn't find any mention of it in the documentation.

**Comment by tariqislam** [comment]
Hi,

I believe what you are noticing is our pagination feature, that automatically kicks in when viewing past trips. Take a look at this documentation, it should show you how to increase the limit:

http://tripit.github.io/api/doc/v1/index.html#pagination

Tariq
