### ISSUE TITLE
node.js and OAuth API

### ISSUE THREAD

**Issue by jamesyd** [tripit/api#69]
Sorry, I closed the original by mistake, so I am reposting:

Hi,

Are their any samples on how to get the OAuth stuff working under node.js? I can get the basic authorization going (oddly, without base 64
encoding), but the OAuth tries give me server errors that it can't procee the request.

Below is my code and then the response I get ... I realize I have left some things out, but was thinking I would get a different response.

var https = require('https');
var util = require('util');
var parseString = require('xml2js').parseString;
var xml = "Hello xml2js!"
//parseString(xml, function (err, result) {
// console.dir(result);
//});

var options = {
hostname: 'api.tripit.com',
//port: 443,
path: '/oauth/request_tokn',
method: 'POST',
//auth: 'Basic ZGVubWFya0B0cmlwaXQuY29tOnNlY3JldHBhc3N3b3Jk'
//auth: 'jamesyd@yahoo.com:sierra6n'
headers: {'oauth_consumer_key':'<hidden>'',
'oauth_nonce' : ' ', 
'oauth_signature' : ' ',
'oauth_signature_method' : 'HMAC-SHA1 ',
'oauth_timestamp' : ' '}
};

var req = https.request(options, function(res) {
console.log("statusCode: ", res.statusCode);
console.log("headers: ", res.headers);

res.on('data', function(d) {
process.stdout.write(d);
parseString( d, function(err, result) {
//console.log(result); // this only goes 2 deep on the XML stuff ...
console.log(util.inspect(result, false, null)); // displays all levels
});
});
});
req.end();

req.on('error', function(e) {
console.error(e);
});

Output:

$ node oauth.js
statusCode: 411
headers: { server: 'AkamaiGHost',
'mime-version': '1.0',
'content-type': 'text/html',
'content-length': '222',
expires: 'Wed, 19 Jun 2013 00:04:43 GMT',
date: 'Wed, 19 Jun 2013 00:04:43 GMT',
connection: 'close' }

Bad Request
Bad Request
Your browser sent a request that this server could not understand.

Reference #7.9db31bb8.1371600283.68d5af1

---

thanks.

**Comment by jamesyd** [comment]
So, no info on how to use this in node.js?

**Comment by tariqislam** [comment]
Hi,

Unfortunately at this moment we do not have any documentation or API binding for node.js. Given that, I usually find it helpful to get an open-source OAuth library (https://github.com/ciaranj/node-oauth perhaps) and then inspect the OAuth calls being made by looking at one of our existing bindings (https://github.com/tripit/php_binding_v1 perhaps) and making sure the same URL parameters and headers are sent by the two libraries. The details of our OAuth process are at http://tripit.github.io/api/doc/v1/index.html#authentication_section.

Thanks.

Tariq
