### ISSUE TITLE
Error 401 106.1 - invalid token key - after a successful authorisation

### ISSUE THREAD

**Issue by schofs** [tripit/api#7]
OK, this is really doing my head in!
Am trying to use the PHP Bindings for Tripit that I've downloaded from github.

So far I've:
- Set up my developer account and got the consumer token and secret
- requested (and successfully received) an unauthorised request token and secret
- used the token to call the https://www.tripit.com/oauth/authorize page, which I click grant and am sent to the callback url. All good

Now I try to call the API access_token api, using the following code:

`$oauth_consumer_key = 'consumer-key-here';
$oauth_consumer_secret = 'consumer-secret-here';
$request_token = 'request-token-here';
$request_token_secret = 'token-secret-goes-here';
$api_url = 'https://api.tripit.com/access_token';
$oauth_credential = new OAuthConsumerCredential($oauth_consumer_key, $oauth_consumer_secret, $request_token, $request_token_secret);
$tripit = new TripIt($oauth_credential, $api_url);
print serialize($tripit->get_access_token()) . "\n";`

And I always get back the following (which varies only by the token key)

`s:186:"<Response><Error><code>401</code><detailed_error_code>106.1</detailed_error_code><description>invalid token key: 4bad9458f0a0336ceda0efe18e76fb361bb19b34</description></Error></Response>";`

What am I doing wrong? The application is definitely active, I'm definitely using the right consumer token/key (the ones I did the unauth request with) and I'm definitely using the token and secret I got from the previous api.

**Comment by tariqislam** [comment]
Hi schofs,

The value for $api_url should be 'https://api.tripit.com'. It is an optional parameter, so just construct your $tripit object without it, i.e.

$tripit = new TripIt($oauth_credential);

## Tariq Islam

Developer Advocate
Tripit

**Comment by schofs** [comment]
Ahhhh perfect. All working now - thanks!

**Comment by tariqislam** [comment]
No worries.

## Tariq Islam

TripIt  |  Developer Advocate

On Sat, Jun 16, 2012 at 5:14 AM, schofs <
reply@reply.github.com
