### ISSUE TITLE
Tripit Groups

### ISSUE THREAD

**Issue by jamesyd** [tripit/api#70]
Hi,
Is there still no support for getting all trips for members of a Group without needing to know the names/id's of all people in the group?

thanks.

**Comment by tariqislam** [comment]
Hi,

Yes there is no API endpoint for getting all trips for a group member.

Thanks.

Tariq

**Comment by jamesyd** [comment]
OK. How about 'Team Members' or if we could get a list of a users 'connections' ? Any of this possible.

Thanks,
JIm
