### ISSUE TITLE
2-Legged OAuth scheme returns "(401) Unauthorized Error" even if the customer has already authorized the Consumer Application

### ISSUE THREAD

**Issue by iltravel** [tripit/api#72]
Hi,

We are trying to implement “2-legged OAuth” scheme with TRIPIT CRS API. We have implemented the things exactly as mentioned in its documentation. But every time we send a request, we are getting an error response as “The remote server returned an error: (401) Unauthorized.”. 

We have registered an application with TripIT named “ILTravel”. Its details are as follows.
1.  Consumer Name : ILTravel
2.  Consumer Account ID : ILTravel@idealake.com
3.  Consumer public key: b13e274287bd4369619c3402327c0121923f7cb0

We have a customer which has already authorized the “ILTravel” application. We achieved it via web based 3-legged OAuth. The customer account id is mangesh_t@idealake.com. 

As per the documentation, the consumer “ILTravel” is now able to make a successful call on the behalf of this customer. But, when we attempted to list all the trips pertaining to this customer, we received an error as “(401) Unauthorized”. 

Since, customer has already authorized this consumer, we assume that the application does not need to request the access token for this customer using https://api.tripit.com/oauth/access_token request. We assume that, the use of 2-legged OAuth with the “xoauth_requestor_id” is to prevent need to store the customer’s access tokens with us and send them in every request. Kindly correct us if we are wrong. 

Can you please guide use to implement 2-legged OAuth with the “xoauth_requestor_id”?
Following are the details of the request and our development environment for your debugging purpose. 

Development Environment
1.  Operating System: 32 Windows-7 
2.  Development tool: Microsoft Visual Studio 2010
3.  Application: ASP.NET web application, Framework 3.5 
4.  Classes used for CRS API implementation: WebRequest and WebResponse 

followings are the request details >>

Base Signature String 
POST&https%3A%2F%2Fapi.tripit.com%2Fv1%2Flist%2Ftrip&oauth_consumer_key%3Db13e274287bd4369619c3402327c0121923f7cb0%26oauth_nonce%3Dc5a350b84bf5e63018b1f28400d44f8b%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1372311216%26oauth_token_secret%3Def93c228b877b85a0b32d522ea1977da5e86905a%26oauth_version%3D1.0%26xoauth_requestor_id%3Dmangesh_t%2540idealake.com

Key used to create 3DHMAC-SHA1
Key=consumer_seceret& 
Also checked with, Key=consumer_seceret&consumer_seceret 

Authorization Header 
OAuth realm="https://api.tripit.com/v1/list/trip",
oauth_consumer_key="b13e274287bd4369619c3402327c0121923f7cb0",
oauth_nonce="c5a350b84bf5e63018b1f28400d44f8b",
oauth_timestamp="1372311216",
oauth_signature_method="HMAC-SHA1",
oauth_version="1.0",
xoauth_requestor_id="mangesh_t%40idealake.com",
oauth_token_secret=Consumer_secret,
oauth_signature="bdIqCwnODUsjT%2FZsdEPZ7M%2B1xoY%3D"

Note:
1.  Line breaks are add for readability  
2.  “oauth_token_secret” is passed the actual value of the consumer_secret.  

We have tried sending the “xoauth_requestor_id” as a separate request header also. But still it is returning the “401 unauthorized error”. if we pass the customer’s access tokens in Authorization Header, we receive a successful response. 

Kindly help us in implementing the “xoauth_requestor_id” with 2-legged OAuth.

**Comment by tariqislam** [comment]
Hi,

Thank you for the detailed information. Were you able to make a normal API call on behalf of the user? As I am understanding, your user went through the OAuth1 flow and granted permissions to your app. You then obtained the user's token and secret. After that, were you able to make a call to, say https://api.tripit.com/v1/list/trip?

We provide API bindings for various languages (https://github.com/tripit/). Unfortunately we don't have a .NET API binding at this point.

Thanks.

Tariq

**Comment by iltravel** [comment]
Hi Tariq,

Your understanding is right.  

The user went through the OAuth1 flow (i.e 3-Legged OAuth) and granted permissions to my app. after that I obtained user's access token using "https://api.tripit.com/oauth/access_token" and stored them in to my DB. My app was then able to make a call to "https://api.tripit.com/v1/list/trip" on the behalf of user by passing its access tokens in authorization header of the request. If i am not mistaken, this is the implementation for TRIPIT Public API with 3-Legged OAuth. This flow is absolutely working fine. 

After that i decided to try the TRIPIT CRS API. We assumed that, using the 2-legged OAuth with the “xoauth_requestor_id”, my app is no longer need to send the user's access token in authorization header of each requests. 

So we used same application to make the request on the behalf of the same user but with 2-legged OAuth. For the sake of simplicity, we tried making a call to "https://api.tripit.com/v1/list/trip". We created the request authorization header  exactly as mentioned in documentation and made a call, but received 401 unauthorized error. Below is an example of it.

Authorization Header (in a call to CRS API)
OAuth realm="https://api.tripit.com/v1/list/trip",
oauth_consumer_key="b13e274287bd4369619c3402327c0121923f7cb0",
oauth_nonce="c5a350b84bf5e63018b1f28400d44f8b",
oauth_timestamp="1372311216",
oauth_signature_method="HMAC-SHA1",
oauth_version="1.0",
xoauth_requestor_id="mangesh_t%40idealake.com",
oauth_token_secret=Consumer_secret,
oauth_signature="bdIqCwnODUsjT%2FZsdEPZ7M%2B1xoY%3D" 

kindly note that,  
1. The "oauth_token" is not passed in the header
2. The "oauth_token_secret" is assigned to the value of consumer secret 

When we made a successful "https://api.tripit.com/v1/list/trip" call to Public TripIT API, we always passed "oauth_token" and "oauth_token_secret". These are assigned to the value of the access token and token secret respectively. Below is an example of it.

Authorization Header (in a successful call to Public Trip IT)
OAuth realm="https://api.tripit.com/v1/list/trip",
oauth_consumer_key="b13e274287bd4369619c3402327c0121923f7cb0",
oauth_nonce="ea327ed6f0fb3f856a657c34b69f64a0",
oauth_timestamp="1372483559",
oauth_signature_method="HMAC-SHA1",
oauth_version="1.0",
oauth_token="f17c877347eb9c436344d285125a282662ed2b24",
oauth_token_secret="01c9dd6c9f80d48bfd1400666fa1d5b27a28d210",
oauth_signature="BNdizOu%2FT%2Bs4sbIJrOqULyob%2B9Y%3D"

So we are quite unsure about,
1. whether we are passing the correct authorization header with CRS API 
or
2. our assumption is wrong about "xoauth_requestor_id" that using it, app will no longer need to send the user's access token in Authorization Header.
or 
3. "https://api.tripit.com/v1/list/trip" is not supported with CRS API. 

Kindly help. 

Since, RESTful API calls can be made through .Net applications, it doesn't matters to us whether .NET API binding for TRIP IT CRS API is available or not.

**Comment by tariqislam** [comment]
Hi,

We have two sets of APIs, the main API (http://tripit.github.io/api/doc/v1/index.html) and the CRS API (http://tripit.github.io/api/doc/v1/crs.html). The main API uses the 3-legged (normal) OAuth for initial authentication, and the API endpoints are listed in the link provided. The CRS API uses the 2-legged OAuth, and it has two endpoints (crsLoadReservations and crsDeleteReservations) as shown in the link provided as well. The xoauth_requestor_id only applies to CRS API calls.

Hope this helps!

Tariq

**Comment by iltravel** [comment]
Hi Tariq,

Thanks for your explanation. At least one thing is clear that the 2-legged OAuth can not be used with the main api's end points. But we are still confused about the use of "xoauth_requestor_id".

Now, we will talk only about CRS API's crsLoadReservations. We need to use the "xoauth_requestor_id", so that there will not be any need of passing the user's access token in the crsLoadReservations request.

So we implemented the 2-legged OAuth as described in "http://tripit.github.io/api/doc/v1/crs.html" and attempted to call crsLoadReservations. But the response  returned as "401 Unauthorized". The detailed error was "invalid token key:".

Following is the sample Authorization header: 
OAuth realm="https://api.tripit.com/v1/crsLoadReservations",
oauth_consumer_key="b13e274287bd4369619c3402327c0121923f7cb0",
oauth_nonce="ad61d568efea512a62952c95f2f1a96c",
oauth_timestamp="1372854261",
oauth_signature_method="HMAC-SHA1",
oauth_version="1.0",
xoauth_requestor_id="mangesh_t%40idealake.com",
oauth_token_secret=consumer secret key,
oauth_signature="H7rtPyonzkh%2F842zp9kPikobQ9U%3D"

*****\* Note that the "oauth_token" is not passed as it is no where mentioned in document. Even if it is passed blank value the Unauthorized error is returned by API end point.

Do we still need to pass oauth_token and oauth_token_secret with xoauth_requestor_id in 2-legged OAuth? Because  when we are passing oauth_token and oauth_token_secret with the values of the user's access token, crsLoadReservations works fine. If we passed only user's access tokens without "xoauth_requestor_id" still crsLoadReservations works fine.  

So we are quite confused about "xoauth_requestor_id". If we still need to pass the user's access tokens in the request's authorization header then whats the use of "xoauth_requestor_id" is. 

Either our understanding is wrong or we are missing something in the authorization header.

Can you please give us a example of the authorization header that can explain us what need to be passed along with the "xoauth_requestor_id" in 2-legged OAuth.

Thanks,
Mangesh Kudalkar

**Comment by tariqislam** [comment]
Hi Mangesh,

My apologies for the delayed reply. It seems that your application "ILTravel" is not set up by us to use our 2-legged OAuth. Please send an email to api-support@tripit.com requesting 2-Legged OAuth.

Thanks.

Tariq
