### ISSUE TITLE
Create trip using Spring Social

### ISSUE THREAD

**Issue by rajkumarpb** [tripit/api#75]
I am using Spring Social for TripIt and no issue in getting trips for that user. But when i try to create new trip, i am getting NullPointerException. Can someone help me with this. Has any one done this successfully before? 
My code is:

public boolean createTrip(JSONObject tripInfo) {
        String url = "POST&https://api.tripit.com/v1/create?format=json";
        String temp = "{\"Trip\":{\"start_date\":\"2009-12-09\",\"end_date\":\"2009-12-27\",\"primary_location\":\"New York, NY\"}}";  
        url = URLEncoder.encode(url);
        getRestTemplate().postForObject(url, temp, String.class);
        return false;
}

**Comment by tariqislam** [comment]
Hi,

I haven't used Spring Social, but some things I am seeing here (perhaps I am wrong):
- The POST data (temp variable) should be of the format "format=json&json={JSON_DATA}", and this should then be url-encoded before posting. Hence:

String temp = URLEncoder.encode("format=json&json=" + ""{\"Trip\":{\"start_.......}");

Also, the url is https://api.tripit.com/v1/create without the format query parameter.

Hopefully this helps.

Tariq

**Comment by rajkumarpb** [comment]
This is not helping. I can do it with regular java binding way, but since we are using Spring, it would be nice to go with Spring Social. It reduce a lot of work for us. Can you please give me an example/link which implemented this in Spring Social?

**Comment by tariqislam** [comment]
Sorry, unfortunately I do not have, or am aware of, a Spring Social implementation to TripIt API. Perhaps if you ask StackOverflow someone may have an answer for you.

Thanks.

Tariq

**Comment by rajkumarpb** [comment]
Ok. Thought trip it support will have spring social implementation.  Thanks for your time tariq.

**Comment by tariqislam** [comment]
No problem.

Tariq
