### ISSUE TITLE
Using OAUTH Server-side/automatically with PHP?

### ISSUE THREAD

**Issue by MabelLiangDC** [tripit/api#77]
Hi!

We are trying to have Tripit sync with another application.  The client wants this to happen periodically, behind the scenes.  There is a single corporate account - there will be a hard-coded username and password.  So we are trying to figure out how to authorize the request token without user interaction.

We are using PHP.

Thanks! 

-- Mabel :-)

**Comment by tariqislam** [comment]
Hi Mabel,

For each user that you'd like to sync up their TripIt data to your application, that user would have to explicitly grant permission to your application by going through the OAuth flow. There is no way around this unfortunately.

Hope this helps.

Tariq
