### ISSUE TITLE
Error using provided PHP get_request_token

### ISSUE THREAD

**Issue by ronaldbradford** [tripit/api#79]
Using the provided script in github, I am getting the error "invalid token key".  I have been unable to find any information that detailed this script. Any help is greatly appreciated.

Here are the reproducible steps.

$ git clone git clone https://github.com/tripit/php_binding_v1.git
$ cd php_binding_v1

From https://www.tripit.com/developer/edit/id/1525572

$ CONSUMER_KEY="***_"  # API Key from 
$ CONSUMER_SECRET="**_*" # API Secret

$ php get_request_token.php https://api.tripit.com/v1/ ${CONSUMER_KEY} ${CONSUMER_SECRET}
s:151:"<Response><Error><code>401</code><detailed_error_code>106.100000</detailed_error_code><description>invalid token key: </description></Error></Response>";

**Comment by tariqislam** [comment]
The url is wrong. Try this:

$ php get_request_token.php https://api.tripit.com ${CONSUMER_KEY} ${CONSUMER_SECRET}

**Comment by ronaldbradford** [comment]
Thanks. That solved the first problem!
