### ISSUE TITLE
Detect a connecting flight in an AirObject?

### ISSUE THREAD

**Issue by miroslavw** [tripit/api#8]
Hello,

Is it possible to detect whether a trip segment is a connection? I can't find a node in the XML flagging or grouping segments as such. Am I missing something or do I have to use some date/time tests to verify? Any suggestion would be gratefully appreciated.

Thanks in advance,

Miro

**Comment by tariqislam** [comment]
Hi miroslavw,

We do not expose whether a trip segment is a connection. However, you could imply in your application that a segment is a connection, e.g. a connection could be defined whereby a traveler lands in airport X and then takes off from airport X within a certain time window. We perform this implying logic on our website when viewing trips, using a time window of 4 hours at an airport.

Thanks.

Tariq Islam
TripIt  |  Developer Advocate

**Comment by miroslavw** [comment]
Thank You Tariq. I was wondering what your suggested time window would be. I will employ this.

**Comment by tariqislam** [comment]
No worries.

Tariq

**Comment by alexbird** [comment]
Hi Tariq,

Some users of our app have noticed that the trips they export to TripIt do not show the final destination when listed on the Trips page at TripIt.  These appear to be trips with longer stopovers, e.g. overnight.  I assume this is due to the 4 hour window.
Is there a way to add a final destination to a trip?  We currently just create an Air object with the relevant segments in it.

Cheers,
Alex

**Comment by tariqislam** [comment]
Hi Alex,

Yes, you are correct on the 4 hour window -- when an air trip item is sent to us, if there currently does not exist a trip for that user, we determine the final destination of that new trip based on the first air segment that has >4 hours stop-over (unless it is the last air segment).

In your situation, you have a couple of ways to go around this, each with its caveat:

`1. 
- Create an Air object - the return object will contain a trip id.
- Query that trip (v1/get/trip/id/<TripIt Object ID>), and see if the final destination on the trip is your desired final destination.
- If it is not the desired final destination (missing/invalid), replace the trip object (v1/replace/trip/id/<TripIt Object ID>) with the correct final destination value.
  Caveat:
- These two cases apply when there exists a trip that overlaps the Air object date range:
  - The user may have set the final destination him/herself, and you may potentially overwrite it with an incorrect value.
  - The final destination may have been set by some other travel object other than yours, and if you overwrite that when you create the Air object, it may be incorrect.

2.
- Create a new Trip object (v1/create) with the correct final destination. You will obtain a trip id in the return object.
- Create an Air object, and reference the created trip id above.
  Caveat:
- The Air object will not go through the TripIt magic of merging with any other trip (within that date time) that may exist for that traveler. In this regard, there is a potential for any other travel objects that are created through the API may not end up on the same trip (created above) in case some other pre-existing trip exists in the same date range.`

Please let me know if you have other questions.

Tariq
