### ISSUE TITLE
Implement tripit in my asp.net application

### ISSUE THREAD

**Issue by Anirban8** [tripit/api#80]
I have API Secret  ,API Key  ,user name and password .Using those thing how can i implement tripit login from my asp.net web application

**Comment by tariqislam** [comment]
Hi,

You would have to implement an OAuth1 flow to get access to a TripIt user's travel data. You may be able to use an existing OAuth1 client (located at http://oauth.net/code/) for your programming language if it is available. If it is not available, please take a look at this blog post (http://blog.andydenmark.com/2009/03/how-to-build-oauth-consumer.html) that describes how to go ahead building an OAuth1 client. Also please look at our OAuth1 section (http://tripit.github.io/api/doc/v1/index.html#authentication_section) for details on its implementation.

Thanks.

Tariq

**Comment by Anirban8** [comment]
how to get oauth_consumer_key and oauth_token for my project.Please help me to get those two value.
