### ISSUE TITLE
.Please help me to find oauth_consumer_key and oauth_token value for my application

### ISSUE THREAD

**Issue by Anirban8** [tripit/api#82]
how to get oauth_consumer_key and oauth_token for my project.Please help me to get those two value.

**Comment by tariqislam** [comment]
Hi,

Please go through our documentation (http://tripit.github.io/api/doc/v1/index.html#authentication_section) where this process is outlined. You can use one of our API bindings (https://github.com/tripit/) for the language of your choice, so you don't have to worry about OAuth1 internal details.

Thanks.

Tariq
