### ISSUE TITLE
Timezone for Trip

### ISSUE THREAD

**Issue by keavy** [tripit/api#84]
The Trip response includes no timezone reference, and the start and end dates _just_ a date string, no timezone information.

The dates aren't much use if they're inaccurate without the correct timezone.

Am I missing something? I can see in the docs that a timezone is included for other objects, like Note or the segments of an AirObject. Why not for Trip?

**Comment by tariqislam** [comment]
Hi,

The issue of timezones on a trip item comes from the fact that users are not required to set their home location in TripIt. Hence, the trip itself has no timezone. However, trip objects have time zones, and these are derived from addresses within  the trip objects.

Hope this helps.

Tariq
