### ISSUE TITLE
How do I test the plugin offline?

### ISSUE THREAD

**Issue by ebensen** [tripit/api#85]
I am trying to implement the TripIt plug-in. I am signed up for an application key and whatnot. The problem is, for obvious reasons I don't do development on the production web servers, and like to know something works before its deployed. 

When I try and test my implementation locally (ASP.NET hitting 'localhost') I get "Registered domain does not match obtained domain".

How do I test this thing before deploying it to production servers? I must be missing something as this has to be a consideration...

Thanks

**Comment by tariqislam** [comment]
Hi,

At this point we don't have a methodology to test the plugin offline, unfortunately. Very sorry about that.

Tariq
