### ISSUE TITLE
Note field text that contains html chars shown with the chars at TripIt page

### ISSUE THREAD

**Issue by olegBakli** [tripit/api#86]
Hi,
I am software engineer at Galor company. In the past we have implemented Flight, Hotel, Activity Services integration and now we implemented Transport Service integration with TripIT, by sending an email message, according to TripIT documentation.
However, sometimes we send a note at Transport Information Notes field that contains a HTML characters, please see text file attached.
This text comes from one of our Transport suppliers, so we can't change it.
The result is that all HTML special characters are shown in Notes section on TripIt page.
Can you assist us with this issue ? maybe there is additional field that can show HTML chars as Browsers do ?
Thanks,

**Comment by tariqislam** [comment]
Hi,

This seems to be an integration with our email parsing system. For these kinds of questions, please contact our help support at the url https://www.tripit.com/uhp/feedback

Thanks.

Tariq
