### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by mattmbk** [tripit/api#87]
I am getting a connection refused from a specific machine in my production environment. Is it possible that the machine is blocked?

From the problem machine:
$ wget https://api.tripit.com/oauth/request_token
--2013-09-05 10:40:05--  https://api.tripit.com/oauth/request_token
Resolving api.tripit.com... 23.7.115.135
Connecting to api.tripit.com|23.7.115.135|:443... failed: Connection refused.

From a different production machine:
$ wget https://api.tripit.com/oauth/request_token
--2013-09-05 10:44:45--  https://api.tripit.com/oauth/request_token
Resolving api.tripit.com... 23.7.115.135
Connecting to api.tripit.com|23.7.115.135|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authorization failed.

Thanks in advance,
Matt

**Comment by tariqislam** [comment]
Hi,

We are having a maintenance window and updating our application on the server right at this moment. Perhaps that is the error you are seeing? We should be live shortly.

Tariq

**Comment by mattmbk** [comment]
I don't believe it is an upgrade downtime issue because it is only occurring on one machine.

Is it possible that one of our IP addresses is being blocked by the network or the application?

**Comment by tariqislam** [comment]
I cannot tell whether we have your machine blocked, since you haven't specified any IP addresses of what is potentially blocked and what is going through.

**Comment by mattmbk** [comment]
Right. Rather than post them on github can you please email me at matt at zdirect dot com? Thanks.

**Comment by tariqislam** [comment]
Please send the info to tariq@tripit.com.

Thanks.

Tariq
