### ISSUE TITLE
Basic Guidance Please?

### ISSUE THREAD

**Issue by janhausultimate** [tripit/api#89]
Greetings.  First let me say I'm not the developer of the application, I'm seeking a quick start to help drive a solution :-)

I'm certain I had seen some discussion and an example on this a while ago, however cannot find my notes now.

The reservation confirmations comply with TripIt. If the customer forwards to plans@tripit.com, everything is working fine.

Can someone tell me, (high level requirements, please)
What is required to enable the confirmation email to be sent directly to TripIt on behalf of the user? Are there any examples available which I can point to?

Thanks so much!

**Comment by tariqislam** [comment]
Hi,

Please look at the following details for confirmation email formatting:

http://help.tripit.com/entries/23260071-Add-to-TripIt-button-standard-confirmation-email-format-for-vendors

Thanks.

Tariq

**Comment by janhausultimate** [comment]
Hello, Tariq

I had seen that, what I was looking for was a method to send on the back end on behalf of the user.
I thought I had seen an application developer provide some examples in the past

Ultimate Regards,

Jan M. Harris,  Business and Technology Development
Austin Ultimate Sedans
