### ISSUE TITLE
C# GetRequestToken 401 unauthorized error

### ISSUE THREAD

**Issue by gilens1979** [tripit/api#9]
Hi,

I have downloaded C# code for TripIt API, and i have also registered an application and i have AppId and AppSecret
And when i try to call GetRequestToken with AppId and AppSecret i'm receiving constantly 401 unauthorized error.

This is my code below!

AppId and AppSecret are ok, just don't know what else do i need to do ?

```
    public static void Main(string[] args)
    {
        System.Net.ServicePointManager.CertificatePolicy = new TrustAllCertificatesPolicy();

        string consumerKey = "22136598af4ea36e7aeb3889ea6cbf57300d24ba";
        string consumerSecret = "88852f05e0998e881bebde709f2501dcac555e38";

        Credential credential = new OAuthCredential(
            consumerKey, consumerSecret);

        TripIt t = new TripIt(credential);

        OAuthCredential authorizedCredential = t.GetRequestToken();

        Console.WriteLine("Request Token: " + authorizedCredential.Token);
        Console.WriteLine("Token Secret:  " + authorizedCredential.TokenSecret);
    }
```

**Comment by tariqislam** [comment]
Hi gilens1979,

I'm looking at the issue and hope to get back to you within a day or two.

Thanks.

Tariq
TripIt | Developer Advocate

**Comment by tariqislam** [comment]
Hi gilens1979,

It seems like the system clock in your host is way off, hence the requests coming to our server are invalidated. After you update your system clock, the OAuth requests should come through. Please let me know in case they don't.

Thanks.

Tariq
TripIt | Developer Advocate

**Comment by gilens1979** [comment]
Sorry, but this didn't solve the problem.
My computer is set to sync time with windows time server, so it is always up to date.

When i checked c# code that you provided, i saw that post params are not provided to server.
I have tried to send them, but still it didn't solve the problem. Maybe I'm sending it wrong way or something else, but still C# code is not working.

Thanks for reply,
Igor

**Comment by tariqislam** [comment]
Hi Igor,

Could you send me your code so I can test it on my end? Also, any
params/instructions that are needed. Please send code to tariq@tripit.com

Thanks.

## Tariq Islam

TripIt  |  Developer Advocate  |  1-415-401-1143 x7143  |  tariq@tripit.com

On Sat, Jul 7, 2012 at 4:05 PM, gilens1979 <
reply@reply.github.com

**Comment by vinthefantastic1** [comment]
What was the resolution for this issue? I am having the same error with the downloaded C# code.

`namespace TripIt.Example {

    class GetRequestToken {
        public static void Main(string[] args) {
            System.Net.ServicePointManager.CertificatePolicy = new TrustAllCertificatesPolicy();
            
            if (args.Length < 3) {
                Console.WriteLine("Usage: GetRequestToken.exe api_url consumer_key " +
                    "consumer_secret");
                return;
            }
            
            string apiUrl = args[0];
            string consumerKey = args[1];
            string consumerSecret = args[2];
            
            Credential credential = new OAuthCredential(
                consumerKey, consumerSecret);
            
            TripIt t = new TripIt(credential, apiUrl);
            
            OAuthCredential authorizedCredential = t.GetRequestToken();
            
            Console.WriteLine("Request Token: " + authorizedCredential.Token);
            Console.WriteLine("Token Secret:  " + authorizedCredential.TokenSecret);
        }
    }

}`
