### ISSUE TITLE
Integration of flight API

### ISSUE THREAD

**Issue by PRASHANT01** [tripit/api#91]
hi.. Tariq m new in application development so i face problem to attach the TripIt api in our application . 
 please can you elaborate me  every singe step how to add it .in our website  from starting. 

 thanks

**Comment by tariqislam** [comment]
Hi,

What language are you writing the application in? Please download the appropriate api binding for your language, if we provide it, here: 
https://github.com/tripit/

After that, you'll have to be familiar with the OAuth1 flow to get people to authenticate your application:
http://tripit.github.io/api/doc/v1/index.html#authentication_section

Please also look at the OAuth1 introduction here:
http://hueniverse.com/2007/10/beginners-guide-to-oauth-part-i-overview/

After you have a user's OAuth1 token/secret, you can start making API calls to TripIt:
http://tripit.github.io/api/doc/v1/index.html#resource_section

Hope this helps.

Tariq
