### ISSUE TITLE
Error sending trip . Try again later

### ISSUE THREAD

**Issue by GONEAPPLE** [tripit/api#94]
Hello.  I am an enduser.  I was using a button (add to tripit button) to add my agenda into tripit.  When I tried, i got the above error.  I did copy & paste the direct link but can't get it to work.  I submitted as email to your team, but can't find why this doesn't work. They suggested this forum.  Any suggestions.

https://www.speedishuttle.com/service/tripit?SITEID=sp1&Action=request_token&RESID=SP1480110

**Comment by tariqislam** [comment]
Hi,

This seems to be like an integration issue with SpeediShuttle. I have sent their team an email about the issue, and hopefully they should start to resolve it shortly.

Best regards,

Tariq

**Comment by GONEAPPLE** [comment]
Hello.  I really appreciated this email.  Did you hear back from their team ?  I am still getting the same error from the link?

Thanks.

**Comment by tariqislam** [comment]
Hi,

I actually sent them two emails on different dates to get this done. I will try one more time... hopefully 3rd time's the charm.

Tariq

**Comment by tariqislam** [comment]
Hi @GONEAPPLE ,

Please let me know if this is still an issue. Otherwise, I am closing it as assumed it is fixed.

Thanks.

Tariq
