### ISSUE TITLE
Using shared itinerary link and API

### ISSUE THREAD

**Issue by Elya** [tripit/api#97]
Hi,

We're developing a web site where we would like to get trips and locations information from the TripIt by using the provided API.

We would like users import theirs  trip data from the TripIt to our site so we can get theirs trips information by using the API  and process the data.

As far as we understood the API allows to access the information only being authorized and we can get data only for the authorized member? 
I'm wondering is there any way we can  get some other user's trips data?

I see there is shared link in TripIt with allows to share the the trip itinerary with everyone.
Is there any way we can use that shared link and trip It API and get trips information for the user who generated the link ? 

The shared link looks like "https://tripit.com/p/5EFFD5095F71BE4893D35C54628AB528". And I'd like to know the last part after /p/ - is this Id of something that we can use and get data ?

To clarify, we would like users to copy the shared itinerary link (or maybe export theirs data into some document) and paste the link (or import document) to our website where we process the imported data (e.g. by using the API to get the information based on input). 

I'd like to know is there any way to do this with TripIt?

Thanks in advance,
Elya

**Comment by tariqislam** [comment]
Hi Elya,

We do not allow access to user's data without their explicit consent. A user would have to give your application access to their data using OAuth.

Hope this helps. Thanks.

Tariq

**Comment by Elya** [comment]
Hi,

Thanks for the replay. That is what I wanted to know. I just wanted to make we need to use OAuth.

**Comment by tariqislam** [comment]
No problem.

Tariq
