### ISSUE TITLE
Access Request Failed

### ISSUE THREAD

**Issue by LoungeFlyZ** [tripit/api#98]
Hi,

One of my applications that has been working for a months recently (not exactly sure when) started giving users "Access Request Failed" when trying to authenticate.

It is my Windows 8 app.  My Windows Phone app continues to let users in fine.

I'm totally confused as to what might be wrong given it was working.  I got some support emails about it not working and sure enough i get the same error now.

What is the best way to debug this?  

Thanks,

Chris.

**Comment by tariqislam** [comment]
Hi Chris,

I'm not aware of any changes at our end. Is the "Access Request Failed" occurring when they are trying to OAuth? Could you give some more details or screenshots with the steps for me to debug?

Thanks.

Tariq

**Comment by LoungeFlyZ** [comment]
Thanks Tariq,

Its not just my Win8 app (My Trips).  It also looks like the exact same thing is happening with other Win8 trip it clients too. (TripHub)

First you get the sign in screen (with the fixed button by the way ... which is great thx):
![image](https://f.cloud.github.com/assets/1360936/1547779/49cfeb2e-4dae-11e3-84bc-413478160109.png)

But then once you have logged in you get this:
![image](https://f.cloud.github.com/assets/1360936/1547787/a6a912a8-4dae-11e3-9266-59d6900a27a3.png)

Exactly teh same things happens with the TripHub app which makes me think its something else.

Thanks,

-Chris.

**Comment by LoungeFlyZ** [comment]
One more thing... I just found out that this seems to only be occurring when using the mobile login screen. 

e.g. https://m.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>

The above will result in the "Access Request Failed" screen.

However switching to the desktop login screen it works:
https://www.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>

So for some reason when using the mobile login screen it fails.  This isnt good since on Win8 the desktop screen is too wide for the browser window that pops up in the authentication broker:

![image](https://f.cloud.github.com/assets/1360936/1547825/338f1874-4db0-11e3-9c96-54cdcca03b93.png)

**Comment by tariqislam** [comment]
Thank you for the details, Chris. I will get on fixing/debugging it immediately.

Also, my apologies for the time it took to fix the previous Win8 login issue.

Thanks!

Tariq

**Comment by LoungeFlyZ** [comment]
Any news Tariq?  Im going to have to make an emergency update to my app if this cant be resolved at your end soon.  I have users who are trying to use the app and cant right now.

Please let me know if this will be fixed shortly or if i need to revert to using the worse desktop experience.  

Thanks.

**Comment by tariqislam** [comment]
Hi Chris,

I have been unable to reproduce this issue. I just tested OAuth using the mobile site, and it worked without issues. I'm not sure how I can debug it on this end, given both the mobile and the web authorization pages work for me. Please let me know if you have ideas.

Thanks.

Tariq

**Comment by LoungeFlyZ** [comment]
Hi Tariq,

Are you using Windows 8.1 and the authentication broker control?  It might be environment specific somehow.

Given its not just effecting my application i get the feeling like its not the code i am using.

The Windows 8 sample i sent you previously should show this.  Please reply to my email with that sample and i will check it for you if you like.

I am currently getting a bunch of users asking when it will be fixed.  I really don't want to have to use the desktop formatted authentication screen if at all possible. 

Thanks,

Chris.

**Comment by tariqislam** [comment]
Hi Chris,

Would you mind sending me the sample app again? I seemed to have misplaced
it.

Thanks!

## Tariq Islam

TripIt  |  Developer Advocate  |  1-415-401-1143  |  tariq@tripit.com

**Comment by stmalia** [comment]
Hey guys - just bought a surface pro 2 & I have this exact issue when trying to sync up My Trips with TripIt.  Any progress on a fix?

**Comment by graboskyc** [comment]
Windows 8.1 Dell Venue Pro tablet and have this issue in My Trips. Windows Phone 8 version does not have the issue. I am waiting to purchase the app until resolved.

**Comment by tariqislam** [comment]
Hi Chris,

We made a few changes to our OAuth process. Unfortunately we don't formally support Windows 8, hence if you don't mind checking with your app, that would be highly appreciated.

Thanks.

Tariq
