### ISSUE TITLE
Tripit plugin doesn't behave well

### ISSUE THREAD

**Issue by hanselLastima** [tripit/api#99]
Hello,

I can't reopen my previous issue(https://github.com/tripit/api/issues/93), so I'll just create this: 

Here's a link with details about the issue: 
http://jsfiddle.net/EQcdG/

Best regards,
Hans

**Comment by tariqislam** [comment]
This is pretty awesome, thanks for setting that up. We will look into the issues at hand. Could you please provide some test details where you have seen the plugin fail:
- OS and browser used

Thanks!

Tariq

**Comment by hanselLastima** [comment]
This is my environment: 
OS: Linux Mint 16 Cinnamon 64-bit
Browser: Google Chrome

**Comment by tariqislam** [comment]
Thank you for the update, Hans. At the moment we support the major browsers (Chrome, FF, IE, Safari) but only on Windows and Mac, and we have fixed a few bugs that were outstanding on those browsers. I will try and see if we can support Linux as well.

**Comment by tariqislam** [comment]
Hi Hans,

Unfortunately at the moment we will not be able to support Linux. Please let me know if you find any issues with the plugin on Windows or Mac.

Best,

Tariq
